// MobileAPI calls (see lib/mobile/main.asm:_MobileAPI)
enum {  // increases by 2?
    MOBILEAPI_00,
    MOBILEAPI_01,
    MOBILEAPI_02,
    MOBILEAPI_03,
    MOBILEAPI_04,
    MOBILEAPI_05,
    MOBILEAPI_06,
    MOBILEAPI_07,
    MOBILEAPI_08,
    MOBILEAPI_09,
    MOBILEAPI_0A,
    MOBILEAPI_0B,
    MOBILEAPI_0C,
    MOBILEAPI_0D,
    MOBILEAPI_0E,
    MOBILEAPI_0F,
    MOBILEAPI_10,
    MOBILEAPI_11,
    MOBILEAPI_12,
    MOBILEAPI_13,
    MOBILEAPI_14,
    MOBILEAPI_15,
    MOBILEAPI_16,
    MOBILEAPI_17,
    MOBILEAPI_SETTIMER,
    MOBILEAPI_19,
    MOBILEAPI_1A,
    MOBILEAPI_1B,
    MOBILEAPI_1C,
    MOBILEAPI_1D,
    MOBILEAPI_1E,
    MOBILEAPI_1F,
    MOBILEAPI_20,
    MOBILEAPI_21,
};

// MobileEZChatCategoryPointers indexes (see mobile/fixed_words.asm)
enum {
    EZCHAT_POKEMON,
    EZCHAT_TYPES,
    EZCHAT_GREETINGS,
    EZCHAT_PEOPLE,
    EZCHAT_BATTLE,
    EZCHAT_EXCLAMATIONS,
    EZCHAT_CONVERSATION,
    EZCHAT_FEELINGS,
    EZCHAT_CONDITIONS,
    EZCHAT_LIFE,
    EZCHAT_HOBBIES,
    EZCHAT_ACTIONS,
    EZCHAT_TIME,
    EZCHAT_FAREWELLS,
    EZCHAT_THISANDTHAT,
};

#define NUM_KANA 45  // length of SortedPokemon table (see mobile/fixed_words.asm)

#define MOBILE_LOGIN_PASSWORD_LENGTH 17
#define MOBILE_PHONE_NUMBER_LENGTH 20

// Maximum amount of time allowed for mobile battles each day
#define MOBILE_BATTLE_ALLOWED_SECONDS 0
#define MOBILE_BATTLE_ALLOWED_MINUTES 10

// Trade corner request size
// DION addr $1e + request $8 + Name $5
// + party struct $30 + OT $5 + NICK $5
// + JP Mail struct $2a
#define MOBILE_EMAIL_LENGTH 0x1e
#define TRADE_CORNER_TRADE_INFO_LENGTH 8
#define TRADE_CORNER_CANCEL_REQUEST_LENGTH MOBILE_EMAIL_LENGTH + TRADE_CORNER_TRADE_INFO_LENGTH
#define TRADE_CORNER_RECEIVE_TRADE_LENGTH PLAYER_NAME_LENGTH - 1 + PARTYMON_STRUCT_LENGTH + PLAYER_NAME_LENGTH - 1 + MON_NAME_LENGTH - 1 + MAIL_STRUCT_LENGTH
#define TRADE_CORNER_TRADE_REQUEST_LENGTH TRADE_CORNER_CANCEL_REQUEST_LENGTH + TRADE_CORNER_RECEIVE_TRADE_LENGTH

#define EASY_CHAT_MESSAGE_WORD_COUNT 4
#define EASY_CHAT_MESSAGE_LENGTH EASY_CHAT_MESSAGE_WORD_COUNT * 2 // every word uses 2 bytes
#define PHONE_NUMBER_LENGTH 8
#define PHONE_NUMBER_DIGITS_QUANTITY PHONE_NUMBER_LENGTH * 2 // Two digits are saved per byte (1x 0-10 digit per nybble).
#define PHONE_NUMBER_DIGITS_MIN_REQUIRED_QUANTITY 6
#define NUM_CARD_FOLDER_ENTRIES 40
#define CARD_FOLDER_ENTRY_LENGTH PLAYER_NAME_LENGTH * 2 + 2 + 2 + 1 + PHONE_NUMBER_LENGTH + EASY_CHAT_MESSAGE_LENGTH
