void DebugColorPicker(void);
// void DebugColor_InitMonOrTrainerColor(void);
// void DebugColor_InitMonColor(void);
// void DebugColor_InitTrainerColor(void);
// void DebugColor_InitColor(void);
// void DebugColor_InitVRAM(void);
// void DebugColor_LoadGFX(void);
// void DebugColor_InitPalettes(void);
// void Palette_DebugBG(void);
// void Palette_DebugOB(void);
// void DebugColorMain(void);
// void DebugColor_InitScreen(void);
// void DebugColor_LoadRGBMeter(void);
// void DebugColor_SetRGBMeter(void);
// void DebugColor_UpdateScreen(void);
// void DebugColor_UpdatePalettes(void);
// void DebugColor_PrintHexColor(void);
// void DebugColor_Joypad(void);
// void DebugColor_SelectColorBox(void);
// void DebugColor_ChangeRedValue(void);
// void DebugColor_ChangeGreenValue(void);
// void DebugColor_ChangeBlueValue(void);
// void DebugColor_UpdateRGBColor(void);
// void DebugColor_PreviousRGBColor(void);
// void DebugColor_NextRGBColor(void);
// void DebugColor_InitTMHM(void);
// void DebugColor_TMHMJoypad(void);
// void DebugColor_PrintTMHMMove(void);
// void DebugColor_CalculatePalette(void);
// void DebugColor_CalculateRGB(void);
// void DebugColor_BackupSpriteColors(void);
// void DebugColor_LoadPalettes_White_Col1_Col2_Black(void);
// void DebugColor_FillBoxWithByte(void);
// void DebugColor_PushSGBPals(void);
// void v_DebugColor_PushSGBPals(void);
// void DebugColor_PlaceCursor(void);
// void DebugColor_AreYouFinishedString(void);
// void DebugColor_UpArrowGFX(void);
// void DebugColor_GFX(void);
void TilesetColorPicker(void);
// void DebugTileset_DrawColorSwatch(void);
// void DebugColor_DrawAttributeSwatch(void);
// void v_DebugColor_DrawSwatch(void);
// void DebugTileset_LoadRGBMeter(void);
// void DebugTileset_LoadPalettes(void);
// void DebugColorMain2(void);
// void DebugTileset_UpdatePalettes(void);
// void DebugTileset_Joypad(void);
// void DebugTileset_SelectColorBox(void);
// void DebugTileset_ChangeRedValue(void);
// void DebugTileset_ChangeGreenValue(void);
// void DebugTileset_ChangeBlueValue(void);
// void DebugTileset_UpdateRGBColor(void);
// void DebugTileset_PreviousRGBColor(void);
// void DebugTileset_NextRGBColor(void);
// void DebugTileset_CalculatePalette(void);
//#include "gfx/debug/bg.pal"
//#include "gfx/debug/ob.pal"
//#include "gfx/debug/up_arrow.2bpp"
//#include "gfx/debug/color_test.2bpp"
