void HDMATransferAttrmapAndTilemapToWRAMBank3(void);
void HDMATransferTilemapToWRAMBank3(void);
void HDMATransferTilemapToWRAMBank3_Conv(void);
void HDMATransferAttrmapToWRAMBank3(void);
void HDMATransferAttrmapToWRAMBank3_Conv(void);
void ReloadMapPart(void);
void ReloadMapPart_Conv(void);
void Mobile_ReloadMapPart(void);
void Function1040d4(void);
void Function1040fb(void);
void OpenAndCloseMenu_HDMATransferTilemapAndAttrmap(void);
void OpenAndCloseMenu_HDMATransferTilemapAndAttrmap_Conv(void);
void Mobile_OpenAndCloseMenu_HDMATransferTilemapAndAttrmap(void);
void Mobile_OpenAndCloseMenu_HDMATransferTilemapAndAttrmap_Conv(void);
void CallInSafeGFXMode(void);
void CallInSafeGFXMode_Conv(void(*hl)(void));
void HDMATransferToWRAMBank3(void);
void HDMATransferToWRAMBank3_Conv(uint8_t* hl);
void WaitDMATransfer(void);
void HDMATransfer_Wait127Scanlines_toBGMap(void);
void HDMATransfer_Wait127Scanlines_toBGMap_Conv(uint16_t hl);
void HDMATransfer_Wait123Scanlines_toBGMap(void);
void HDMATransfer_Wait123Scanlines_toBGMap_Conv(uint16_t hl);
void HDMATransfer_NoDI(void);
void HDMATransfer_Wait123Scanlines(void);
void HDMATransfer_Wait123Scanlines_Conv(uint16_t hl, uint16_t de, uint8_t c);
void HDMATransfer_Wait127Scanlines(void);
void HDMATransfer_Wait127Scanlines_Conv(uint16_t hl, uint16_t de, uint8_t c);
void v_continue_HDMATransfer(void);
void v_continue_HDMATransfer_Conv(uint16_t hl, uint16_t de, uint8_t c, uint8_t b);
void v_LoadHDMAParameters(void);
void PadTilemapForHDMATransfer(void);
void PadTilemapForHDMATransfer_Conv(uint16_t hl, uint16_t de);
void PadTilemapForHDMATransfer_Conv2(uint8_t* hl, const uint8_t* de);
void PadAttrmapForHDMATransfer(void);
void PadAttrmapForHDMATransfer_Conv(uint16_t hl, uint16_t de);
void PadAttrmapForHDMATransfer_Conv2(uint8_t* hl, const uint8_t* de);
void PadMapForHDMATransfer(void);
void PadMapForHDMATransfer_Conv(uint16_t hl, uint16_t de, uint8_t c);
void PadMapForHDMATransfer_Conv2(uint8_t* hl, const uint8_t* de, uint8_t c);
void HDMATransfer2bpp(void);
void HDMATransfer2bpp_Conv(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void HDMATransfer1bpp(void);
void HDMATransfer_OnlyTopFourRows(void);
void HDMATransfer_OnlyTopFourRows_Conv(void);
