#pragma once

#define FIRST_BATTLE_ANIM_CMD 0xd0
enum {
    anim_obj_command = FIRST_BATTLE_ANIM_CMD,
    anim_1gfx_command,
    anim_2gfx_command,
    anim_3gfx_command,
    anim_4gfx_command,
    anim_5gfx_command,
    anim_incobj_command,
    anim_setobj_command,
    anim_incbgeffect_command,
    anim_battlergfx_2row_command,
    anim_battlergfx_1row_command,
    anim_checkpokeball_command,
    anim_transform_command,
    anim_raisesub_command,
    anim_dropsub_command,
    anim_resetobp0_command, // 0xdf
    anim_sound_command,
    anim_cry_command,
    anim_minimizeopp_command,
    anim_oamon_command,
    anim_oamoff_command,
    anim_clearobjs_command,
    anim_beatup_command,
    anim_0xe7_command,
    anim_updateactorpic_command,
    anim_minimize_command,
    anim_0xea_command,
    anim_0xeb_command,
    anim_0xec_command,
    anim_0xed_command,
    anim_if_param_and_command,
    anim_jumpuntil_command,
    anim_bgeffect_command,
    anim_bgp_command,
    anim_obp0_command,
    anim_obp1_command,
    anim_keepsprites_command,
    anim_0xf5_command,
    anim_0xf6_command,
    anim_0xf7_command,
    anim_if_param_equal_command,
    anim_setvar_command,
    anim_incvar_command,
    anim_if_var_equal_command,
    anim_jump_command,
    anim_loop_command,
    anim_call_command,
    anim_ret_command
};

