void TradeAnimation(void);
void TradeAnimationPlayer2(void);
void RunTradeAnimScript(const uint8_t* de);
bool DoTradeAnimation(void);
void TradeAnim_IncrementJumptableIndex(void);
void TradeAnim_AdvanceScriptPointer(void);
void TradeAnim_End(void);
void TradeAnim_TubeToOT1(void);
void TradeAnim_TubeToPlayer1(void);
void TradeAnim_InitTubeAnim(uint16_t de, uint8_t b, uint8_t a);
void TradeAnim_TubeToOT2(void);
void TradeAnim_TubeToOT3(void);
void TradeAnim_TubeToOT4(void);
void TradeAnim_TubeToPlayer3(void);
void TradeAnim_TubeToPlayer4(void);
void TradeAnim_TubeToPlayer5(void);
void TradeAnim_TubeToOT6(void);
void TradeAnim_TubeToPlayer6(void);
void TradeAnim_TubeToOT8(void);
void TradeAnim_TubeToPlayer8(void);
void TradeAnim_TubeToOT5(void);
void TradeAnim_TubeToOT7(void);
void TradeAnim_TubeToPlayer2(void);
void TradeAnim_TubeToPlayer7(void);
void TradeAnim_GiveTrademonSFX(void);
void TradeAnim_GetTrademonSFX(void);
void TradeAnim_TubeAnimJumptable(uint8_t state);
void TradeAnim_CopyTradeGameBoyTilemap(uint8_t* hl);
void TradeAnim_PlaceTrademonStatsOnTubeAnim(uint8_t a);
void TradeAnim_EnterLinkTube1(void);
void TradeAnim_EnterLinkTube2(void);
void TradeAnim_ExitLinkTube(void);
void TradeAnim_SetupGivemonScroll(void);
void TradeAnim_DoGivemonScroll(void);
void TradeAnim_FrontpicScrollStart(void);
void TradeAnim_TextboxScrollStart(void);
void TradeAnim_ScrollOutRight(void);
void TradeAnim_ScrollOutRight2(void);
void TradeAnim_ShowGivemonData(void);
void TradeAnim_ShowGetmonData(void);
void TradeAnim_AnimateFrontpic(void);
void TradeAnim_GetFrontpic(uint8_t* de, uint16_t dvs, species_t species);
void TradeAnim_GetNicknamename(uint8_t* de, species_t species);
void TradeAnim_ShowGivemonFrontpic(void);
void TradeAnim_ShowGetmonFrontpic(void);
void TradeAnim_ShowFrontpic(const uint8_t* de);
void TradeAnim_Wait80(void);
void TradeAnim_Wait40(void);
void TradeAnim_Wait96(void);
void TradeAnim_Wait80IfOTEgg(void);
void TradeAnim_Wait180IfOTEgg(void);
bool IsOTTrademonEgg(void);
void ShowPlayerTrademonStats(void);
void ShowOTTrademonStats(void);
void TrademonStats_MonTemplate(void);
void TrademonStats_Egg(void);
void TrademonStats_WaitBGMap(void);
void TrademonStats_PrintSpeciesNumber(species_t species);
void TrademonStats_PrintSpeciesName(uint8_t* de);
void TrademonStats_PrintOTName(uint8_t* de, uint8_t caughtData);
void TrademonStats_PrintTrademonID(uint16_t id);
void TradeAnim_RockingBall(void);
void TradeAnim_DropBall(void);
void TradeAnim_Poof(void);
void TradeAnim_BulgeThroughTube(void);
void TradeAnim_AnimateTrademonInTube(struct SpriteAnim* bc);
void TradeAnim_SentToOTText(void);
void TradeAnim_OTBidsFarewell(void);
void TradeAnim_TakeCareOfText(void);
void TradeAnim_OTSendsText1(void);
void TradeAnim_OTSendsText2(void);
void TradeAnim_Wait80Frames(void);
void TradeAnim_BlankTilemap(void);
void TradeAnim_CopyBoxFromDEtoHL(uint8_t* hl, const uint8_t* de, uint8_t b, uint8_t c);
void TradeAnim_NormalPals(void);
void LinkTradeAnim_LoadTradePlayerNames(const uint8_t* hl, const uint8_t* de);
void LinkTradeAnim_LoadTradeMonSpecies(species_t sendmon, species_t getmon);
void TradeAnim_FlashBGPals(void);
void LoadTradeBallAndCableGFX(void);
void LoadTradeBubbleGFX(void);
void TradeAnim_WaitAnim(void);
void TradeAnim_WaitAnim2(void);
void DebugTrade(void);
extern const char TradeGameBoyTilemap[];
extern const char TradeLinkTubeTilemap[];
extern const char TradeArrowRightGFX[];
extern const char TradeArrowLeftGFX[];
extern const char TradeCableGFX[];
extern const char TradeBubbleGFX[];
extern const char TradeGameBoyLZ[];
extern const char TradeLinkCableGFX[];
extern const char TradeBallGFX[];
extern const char TradePoofGFX[];
extern const uint8_t* gTradeAnimAddress;
