void InitSound(void);
void UpdateSound(void);
void PlayMusic(uint16_t);
void PlayMusic2(uint16_t de);
void PlayCry(uint16_t de);
void PlaySFX(uint16_t de);
void WaitPlaySFX(uint16_t de);
void WaitSFX(void);
bool IsSFXPlaying(void);
void MaxVolume(void);
void LowVolume(void);
void MinVolume(void);
void FadeOutToMusic(void);
void FadeInToMusic(void);
void SkipMusic(uint8_t a);
void FadeToMapMusic(void);
void PlayMapMusic(void);
void PlayMapMusicBike(void);
void TryRestartMapMusic(void);
void RestartMapMusic(void);
void PlaceBCDNumberSprite(void);
bool CheckSFX(void);
void TerminateExpBarSound(void);
void ChannelsOff(void);
void SFXChannelsOff(void);
