void ResetMapBufferEventFlags(void);
void ResetMapBufferEventFlags_Conv(void);
void ResetBikeFlags(void);
void ResetBikeFlags_Conv(void);
void ResetFlashIfOutOfCave(void);
void ResetFlashIfOutOfCave_Conv(void);
void EventFlagAction(void);
void EventFlagAction_Conv(uint16_t bit, uint8_t func);
uint8_t EventFlagAction_Conv2(uint16_t bit, uint8_t func);
void FlagAction(void);
void FlagAction_Conv(uint16_t flag, uint16_t bit, uint8_t func);
uint8_t FlagAction_Conv2(uint8_t* flag, uint16_t bit, uint8_t func);
void CheckReceivedDex(void);
bool CheckReceivedDex_Conv(void);
void CheckBPressedDebug(void);
bool CheckBPressedDebug_Conv(void);
void xor_a(void);
uint8_t xor_a_Conv(uint8_t a);
void xor_a_dec_a(void);
uint8_t xor_a_dec_a_Conv(uint8_t a);
void CheckFieldDebug(void);
bool CheckFieldDebug_Conv(void);
