void ResetMapBufferEventFlags(void);
void ResetBikeFlags(void);
void ResetFlashIfOutOfCave(void);
uint8_t EventFlagAction(uint16_t bit, uint8_t func);
uint8_t FlagAction(uint8_t* flag, uint16_t bit, uint8_t func);
bool CheckReceivedDex(void);
bool CheckBPressedDebug(void);
uint8_t xor_a(uint8_t a);
uint8_t xor_a_dec_a(uint8_t a);
bool CheckFieldDebug(void);
