void Get2bppViaHDMA(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void Get1bppViaHDMA(void);
void FarCopyBytesDouble_DoubleBankSwitch(void);
void SafeHDMATransfer(void);
void UpdatePlayerSprite(void);
void LoadStandardFont(void);
void LoadFontsBattleExtra(void);
void LoadFontsExtra(void);
void LoadFontsExtra2(void);
void DecompressRequest2bpp(uint8_t b, uint16_t hl, uint8_t c);
void FarCopyBytes(uint16_t de, uint8_t a, uint16_t hl, uint16_t bc);
void FarCopyBytesDouble(uint16_t de, uint8_t a, uint16_t hl, uint16_t bc);
void Request2bpp(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void Request1bpp(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void Get2bpp(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void Copy2bpp(uint8_t b, uint16_t de, uint16_t hl, uint8_t c);
void Get1bpp(uint16_t hl, uint8_t b, uint16_t de, uint8_t c);
void Copy1bpp(uint16_t hl, uint8_t b, uint16_t de, uint8_t c);
