void Joypad(void);
void ClearJoypad(void);
void ClearJoypad_Conv(void);
void UpdateJoypad(void);
void UpdateJoypad_Conv(void);
void GetJoypad(void);
void GetJoypad_Conv(void);
void GetJoypad_Conv2(void);
void StartAutoInput(void);
void StartAutoInput_Conv2(const uint8_t* hl);
void StopAutoInput(void);
void StopAutoInput_Conv(void);
void StopAutoInput_Conv2(void);
void JoyTitleScreenInput(void);
void JoyWaitAorB(void);
void WaitButton(void);
void WaitButton_Conv(void);
void JoyTextDelay(void);
void JoyTextDelay_Conv(void);
void WaitPressAorB_BlinkCursor(void);
void WaitPressAorB_BlinkCursor_Conv(void);
void SimpleWaitPressAorB(void);
void PromptButton(void);
void PromptButton_Conv(void);
void BlinkCursor(void);
void BlinkCursor_Conv(uint16_t hl);
void BlinkCursor_Conv2(uint8_t* hl);
