void ClearUnusedMapBuffer(void);
void CheckScenes(void);
uint8_t CheckScenes_Conv(void);
void GetCurrentMapSceneID(void);
uint16_t GetCurrentMapSceneID_Conv(void);
void GetMapSceneID(void);
uint8_t* GetMapSceneID_Conv2(uint8_t group, uint8_t map);
void OverworldTextModeSwitch(void);
void OverworldTextModeSwitch_Conv(void);
void LoadMapPart(void);
void LoadMapPart_Conv(void);
void LoadMetatiles(void);
void LoadMetatiles_Conv(void);
void ReturnToMapFromSubmenu(void);
void CheckWarpTile(void);
bool CheckWarpTile_Conv(void);
void WarpCheck(void);
bool WarpCheck_Conv(void);
void GetDestinationWarpNumber(void);
u8_flag_s GetDestinationWarpNumber_Conv(void);
void CopyWarpData(void);
void CopyWarpData_Conv(uint8_t c);
void CheckOutdoorMap(void);
bool CheckOutdoorMap_Conv(uint8_t a);
void CheckIndoorMap(void);
bool CheckIndoorMap_Conv(uint8_t a);
void CheckUnknownMap(void);
void LoadMapAttributes(void);
void LoadMapAttributes_Conv(void);
void LoadMapAttributes_SkipObjects(void);
void LoadMapAttributes_SkipObjects_Conv(void);
void CopyMapPartialAndAttributes(void);
void CopyMapPartialAndAttributes_Conv(void);
void ReadMapEvents(void);
void ReadMapEvents_Conv(bool skipObjectEvents);
void ReadMapScripts(void);
void ReadMapScripts_Conv(void);
void CopyMapAttributes(void);
void CopyMapAttributes_Conv(const struct MapAttr* attr);
void GetMapConnections(void);
void GetMapConnections_Conv(const struct MapAttr* attr);
void GetMapConnection(void);
void GetMapConnection_Conv(struct MapConnectionData* de, const struct MapConnectionData* hl);
void ReadMapSceneScripts(void);
void ReadMapSceneScripts_Conv(const struct MapScripts* hl);
void ReadMapCallbacks(void);
void ReadMapCallbacks_Conv(const struct MapScripts* hl);
void ReadWarps(void);
void ReadWarps_Conv(const struct MapEvents* hl);
void ReadCoordEvents(void);
void ReadCoordEvents_Conv(const struct MapEvents* hl);
void ReadBGEvents(void);
void ReadBGEvents_Conv(const struct MapEvents* hl);
void ReadObjectEvents(void);
void ReadObjectEvents_Conv(const struct MapEvents* hl);
void CopyMapObjectEvents(void);
uint8_t CopyMapObjectEvents_Conv(struct MapObject* hl, const struct ObjEvent* de, uint8_t count);
void ClearObjectStructs(void);
void ClearObjectStructs_Conv(void);
void GetWarpDestCoords(void);
void GetWarpDestCoords_Conv(void);
void LoadBlockData(void);
void ChangeMap(void);
void FillMapConnections(void);
void FillNorthConnectionStrip(uint8_t* de, const uint8_t* hl);
void FillSouthConnectionStrip(uint8_t* de, const uint8_t* hl);
void FillWestConnectionStrip(uint8_t* de, const uint8_t* hl, uint8_t b);
void FillEastConnectionStrip(uint8_t* de, const uint8_t* hl, uint8_t b);
void LoadMapStatus(void);
void LoadMapStatus_Conv(uint8_t a);
void CallScript(void);
uint8_t CallScript_Conv(uint8_t a, uint16_t hl);
uint8_t CallScript_Conv2(Script_fn_t hl);
void CallMapScript(void);
uint8_t CallMapScript_Conv(uint16_t hl);
uint8_t CallMapScript_Conv2(Script_fn_t hl);
void RunMapCallback(void);
void RunMapCallback_Conv(uint8_t a);
void ExecuteCallbackScript(void);
void ExecuteCallbackScript_Conv(Script_fn_t de);
void MapTextbox(void);
void MapTextbox_Conv(const struct TextCmd* text);
void Call_a_de(void);
void GetMovementData(void);
bool GetMovementData_Conv(uint8_t c, const uint8_t* hl);
void GetScriptByte(void);
bool ObjectEvent(script_s* s);
extern const txt_cmd_s ObjectEventText[];
bool BGEvent(script_s* s);
extern const txt_cmd_s BGEventText[];
bool CoordinatesEvent(script_s* s);
extern const txt_cmd_s CoordinatesEventText[];
void CheckObjectMask(void);
uint8_t CheckObjectMask_Conv(uint8_t a);
void MaskObject(void);
void MaskObject_Conv(uint8_t a);
void UnmaskObject(void);
void UnmaskObject_Conv(uint8_t a);
void ComputeROMXChecksum(void);
void ScrollMapUp(void);
void ScrollMapDown(void);
void ScrollMapLeft(void);
void ScrollMapRight(void);
void BackupBGMapRow(void);
void BackupBGMapRow_Conv(tile_t* de, const tile_t* hl);
void BackupBGMapColumn(void);
void BackupBGMapColumn_Conv(tile_t* de, const tile_t* hl);
void UpdateBGMapRow(void);
void UpdateBGMapRow_Conv(uint16_t de);
void UpdateBGMapColumn(void);
void UpdateBGMapColumn_Conv(uint16_t de);
void ClearBGMapBuffer(void);
void LoadTilesetGFX(void);
void LoadTilesetGFX_Conv(void);
void BufferScreen(void);
void BufferScreen_Conv(void);
void SaveScreen(void);
void LoadConnectionBlockData(void);
void SaveScreen_LoadConnection(void);
void SaveScreen_LoadConnection_Conv(uint8_t* hl, const uint8_t* de, uint8_t b, uint8_t c);
void GetMovementPermissions(void);
void GetFacingTileCoord(void);
struct CoordsTileId GetFacingTileCoord_Conv(void);
void GetCoordTile(void);
uint8_t GetCoordTile_Conv(uint8_t d, uint8_t e);
void GetBlockLocation(void);
uint8_t* GetBlockLocation_Conv(uint8_t d, uint8_t e);
void CheckFacingBGEvent(void);
bool CheckFacingBGEvent_Conv(void);
void CheckIfFacingTileCoordIsBGEvent(void);
bool CheckIfFacingTileCoordIsBGEvent_Conv(uint8_t c, uint8_t d, uint8_t e);
void CheckCurrentMapCoordEvents(void);
const struct CoordEvent* CheckCurrentMapCoordEvents_Conv(void);
void FadeToMenu(void);
void FadeToMenu_Conv(void);
void CloseSubmenu(void);
void CloseSubmenu_Conv(void);
void ExitAllMenus(void);
void ExitAllMenus_Conv(void);
void FinishExitMenu(void);
void FinishExitMenu_Conv(void);
void ReturnToMapWithSpeechTextbox(void);
void ReturnToMapWithSpeechTextbox_Conv(void);
void ReloadTilesetAndPalettes(void);
void ReloadTilesetAndPalettes_Conv(void);
void GetMapPointer(void);
uint16_t GetMapPointer_Conv(void);
const struct MapHeader* GetMapPointer_Conv2(void);
void GetAnyMapPointer(void);
uint16_t GetAnyMapPointer_Conv(uint8_t group, uint8_t map);
const struct MapHeader* GetAnyMapPointer_Conv2(uint8_t group, uint8_t map);
void GetMapField(void);
uint16_t GetMapField_Conv(uint16_t offset);
void GetAnyMapField(void);
uint16_t GetAnyMapField_Conv(uint16_t offset, uint8_t group, uint8_t map);
void SwitchToMapAttributesBank(void);
void SwitchToAnyMapAttributesBank(void);
void GetMapAttributesBank(void);
void GetAnyMapAttributesBank(void);
void CopyMapPartial(void);
void CopyMapPartial_Conv2(void);
void SwitchToMapScriptsBank(void);
void SwitchToMapScriptsBank_Conv(void);
void GetMapScriptsBank(void);
uint8_t GetMapScriptsBank_Conv(void);
void GetAnyMapBlocksBank(void);
void GetMapAttributesPointer(void);
const struct MapAttr* GetMapAttributesPointer_Conv2(void);
void GetMapEnvironment(void);
uint8_t GetMapEnvironment_Conv(void);
uint8_t GetMapEnvironment_Conv2(void);
void Map_DummyFunction(void);
void GetAnyMapEnvironment(void);
uint8_t GetAnyMapEnvironment_Conv2(uint8_t group, uint8_t map);
void GetAnyMapTileset(void);
uint8_t GetAnyMapTileset_Conv(uint8_t group, uint8_t map);
uint8_t GetAnyMapTileset_Conv2(uint8_t group, uint8_t map);
void GetWorldMapLocation(void);
uint8_t GetWorldMapLocation_Conv(uint8_t group, uint8_t map);
uint8_t GetWorldMapLocation_Conv2(uint8_t group, uint8_t map);
void GetMapMusic(void);
uint16_t GetMapMusic_Conv2(void);
void GetMapTimeOfDay(void);
uint8_t GetMapTimeOfDay_Conv(void);
void GetMapPhoneService(void);
uint8_t GetMapPhoneService_Conv(void);
void GetPhoneServiceTimeOfDayByte(void);
uint8_t GetPhoneServiceTimeOfDayByte_Conv(void);
void GetFishingGroup(void);
uint8_t GetFishingGroup_Conv2(void);
void LoadMapTileset(void);
void LoadMapTileset_Conv2(void);
void DummyEndPredef(void);

extern uint8_t gCurMapCallbackCount;
extern const struct MapCallback* gCurMapCallbacksPointer;
extern uint8_t gCurMapSceneScriptCount;
extern const Script_fn_t* gCurMapSceneScriptsPointer;
extern uint8_t gCurMapObjectEventCount;
extern const struct ObjEvent* gCurMapObjectEventsPointer;

extern const struct TileAnimFrame* gTilesetAnim;

extern struct BGEvent gCurBGEvent;
extern struct MapConnectionData gMapConnections[4];
