void Load2DMenuData(void);
void StaticMenuJoypad(void);
void ScrollingMenuJoypad(void);
void GetMenuJoypad(void);
uint8_t GetMenuJoypad_Conv(void);
void PlaceHollowCursor(void);
void HideCursor(void);
void PushWindow(void);
void ExitMenu(void);
void ExitMenu_Conv(void);
void InitVerticalMenuCursor(void);
void InitVerticalMenuCursor_Conv(void);
void CloseWindow(void);
void RestoreTileBackup(void);
void RestoreTileBackup_Conv(uint8_t* de);
void PopWindow(void);
void PopWindow_Conv(uint16_t hl);
void GetMenuBoxDims(void);
void GetMenuBoxDims_Conv(uint8_t* w, uint8_t* h);
void CopyMenuData(void);
void CopyMenuData_Conv(void);
void GetWindowStackTop(void);
uint16_t GetWindowStackTop_Conv(void);
void PlaceVerticalMenuItems(void);
void MenuBox(void);
void MenuBox_Conv(void);
void GetMenuTextStartCoord(void);
void GetMenuTextStartCoord_Conv(uint8_t* b, uint8_t* c);
void ClearMenuBoxInterior(void);
void ClearWholeMenuBox(void);
void MenuBoxCoord2Tile(void);
uint8_t* MenuBoxCoord2Tile_Conv(void);
void Coord2Tile(void);
uint8_t* Coord2Tile_Conv(uint8_t c, uint8_t b);
void MenuBoxCoord2Attr(void);
uint8_t* MenuBoxCoord2Attr_Conv(void);
void Coord2Attr(void);
uint8_t* Coord2Attr_Conv(uint8_t c, uint8_t b);
void LoadMenuHeader(void);
void CopyMenuHeader(void);
void CopyMenuHeader_Conv(uint16_t hl);
void StoreMenuCursorPosition(void);
void MenuTextbox(void);
void Menu_DummyFunction(void);
void LoadMenuTextbox(void);
void MenuTextboxBackup(void);
void LoadStandardMenuHeader(void);
void Call_ExitMenu(void);
void VerticalMenu(void);
void GetMenu2(void);
void CopyNameFromMenu(void);
void YesNoBox(void);
void PlaceYesNoBox(void);
void PlaceGenericTwoOptionBox(void);
void v_YesNoBox(void);
void InterpretTwoOptionMenu(void);
void YesNoMenuHeader(void);
void OffsetMenuHeader(void);
void v_OffsetMenuHeader(void);
void DoNthMenu(void);
void SetUpMenu(void);
void DrawVariableLengthMenuBox(void);
void MenuWriteText(void);
void AutomaticGetMenuBottomCoord(void);
void GetMenuIndexSet(void);
void RunMenuItemPrintingFunction(void);
void InitMenuCursorAndButtonPermissions(void);
void GetScrollingMenuJoypad(void);
bool GetScrollingMenuJoypad_Conv(void);
void GetStaticMenuJoypad(void);
void ContinueGettingMenuJoypad(void);
bool ContinueGettingMenuJoypad_Conv(uint8_t a);
void PlaceMenuStrings(void);
void PlaceNthMenuStrings(void);
void GetNthMenuStrings(void);
void MenuJumptable(void);
void GetMenuDataPointerTableEntry(void);
void ClearWindowData(void);
void ClearWindowData_Conv(void);
void MenuClickSound(void);
void MenuClickSound_Conv(uint8_t a);
void PlayClickSFX(void);
void PlayClickSFX_Conv(void);
void MenuTextboxWaitButton(void);
void Place2DMenuItemName(void);
void v_2DMenu(void);
void InterpretBattleMenu(void);
void InterpretMobileMenu(void);
