void Load2DMenuData(const uint8_t* de);
uint8_t StaticMenuJoypad(void);
uint8_t ScrollingMenuJoypad(void);
uint8_t GetMenuJoypad(void);
void PlaceHollowCursor(void);
uint8_t* HideCursor(void);
void PushWindow(void);
void ExitMenu(void);
void InitVerticalMenuCursor(const struct MenuData* data);
void CloseWindow(void);
void RestoreTileBackup(const uint8_t* de);
void PopWindow(void);
void PopWindow_Conv(uint16_t hl);
void PopWindow_Conv2(struct MenuHeader* hl);
void GetMenuBoxDims(uint8_t* w, uint8_t* h);
void CopyMenuData(void);
void CopyMenuData_Conv(void);
const struct MenuData* GetMenuData(void);
void GetWindowStackTop(void);
uint16_t GetWindowStackTop_Conv(void);
void PlaceVerticalMenuItems(void);
void MenuBox(void);
void GetMenuTextStartCoord(const struct MenuData* data, uint8_t* b, uint8_t* c);
void ClearMenuBoxInterior(void);
void ClearWholeMenuBox(void);
uint8_t* MenuBoxCoord2Tile(void);
uint8_t* Coord2Tile(uint8_t c, uint8_t b);
uint8_t* MenuBoxCoord2Attr(void);
uint8_t* Coord2Attr(uint8_t c, uint8_t b);
void LoadMenuHeader(const struct MenuHeader* hl);
void CopyMenuHeader(const struct MenuHeader* hl);
void StoreMenuCursorPosition(uint8_t a);
void MenuTextbox(const struct TextCmd* hl);
void Menu_DummyFunction(void);
void LoadMenuTextbox(void);
void LoadMenuTextbox(void);
void MenuTextboxBackup(const struct TextCmd* hl);
void LoadStandardMenuHeader(void);
void Call_ExitMenu(void);
bool VerticalMenu(void);
void GetMenu2(void);
u8_flag_s GetMenu2_Conv(const struct MenuHeader* hl);
void CopyNameFromMenu(uint8_t a);
bool YesNoBox(void);
bool PlaceYesNoBox(uint8_t b, uint8_t c);
void PlaceGenericTwoOptionBox(void);
bool v_YesNoBox(uint8_t b, uint8_t c);
bool InterpretTwoOptionMenu(void);
// void YesNoMenuHeader(void);
extern const struct MenuHeader YesNoMenuHeader;
void OffsetMenuHeader(const struct MenuHeader* hl, uint8_t d, uint8_t e);
void v_OffsetMenuHeader(const struct MenuHeader* hl, uint8_t d, uint8_t e);
u8_flag_s DoNthMenu(void);
void SetUpMenu(void);
void DrawVariableLengthMenuBox(void);
void MenuWriteText(void);
void AutomaticGetMenuBottomCoord(uint8_t* b, uint8_t* c);
const uint8_t* GetMenuIndexSet(const struct MenuData* data);
void RunMenuItemPrintingFunction(const struct MenuData* data, const uint8_t* de);
void InitMenuCursorAndButtonPermissions(void);
bool GetScrollingMenuJoypad(void);
bool GetStaticMenuJoypad(void);
bool ContinueGettingMenuJoypad(uint8_t a);
void PlaceMenuStrings(const char** strings, uint8_t* de, uint8_t selection);
void PlaceNthMenuStrings(const char** strings, uint8_t* de, uint8_t selection);
void GetNthMenuStrings(void);
u8_flag_s MenuJumptable(void);
void GetMenuDataPointerTableEntry(void);
void ClearWindowData(void);
void MenuClickSound(uint8_t a);
void PlayClickSFX(void);
void MenuTextboxWaitButton(const struct TextCmd* hl);
void Place2DMenuItemName(uint8_t* hl, const char* de);
u8_flag_s v_2DMenu(void);
u8_flag_s InterpretBattleMenu(void);
void InterpretMobileMenu(void);

extern const void* gMenuDataPointer;
