void MobileAPI(uint8_t a, mobile_api_data_s *api);
void ReturnMobileAPI(mobile_api_data_s *api);
void MobileReceive(void);
void MobileTimer(void);
void Function3ed7(void);
tile_t* Function3eea(tile_t* hl, uint8_t b, uint8_t c);
void Function3efd(void);
void Function3f20(void);
void Function3f35(uint8_t* hl, uint8_t b, uint8_t c);
tile_t* MobileHome_PlaceBox(tile_t* hl, uint8_t b, uint8_t c);
void Function3f7c(void);
void Function3f88(const uint8_t* de, uint8_t c);
void Function3f9f(const uint8_t* de, uint8_t c);
