bool UpdatePalsIfCGB(void);
bool UpdateCGBPals(void);
bool ForceUpdateCGBPals(void);
void DmgToCgbBGPals(uint8_t a);
void DmgToCgbObjPals(uint8_t d, uint8_t e);
void DmgToCgbObjPal0(uint8_t a);
void DmgToCgbObjPal1(uint8_t a);
void CopyPals(void* hl, const void* de, uint8_t b, uint8_t c);
void CopyPals_GB(uint16_t hl, uint16_t de, uint8_t b, uint8_t c);
void ClearVBank1(void);
void GSReloadPalettes(void);
void ReloadSpritesNoPalettes(void);
void SwapTextboxPalettes(void);
void ScrollBGMapPalettes(uint8_t c);
