bool IsAPokemon(species_t species);
void DrawBattleHPBar(tile_t* hl, uint8_t d, uint8_t e, uint8_t b, uint8_t c);
void PrepMonFrontpic(tile_t* hl);
void v_PrepMonFrontpic(tile_t* hl);
void PlayStereoCry(species_t species);
void PlayStereoCry2(species_t species);
void PlayMonCry(species_t species);
void PlayMonCry2(species_t species);
void v_PlayMonCry(species_t species);
const struct PokemonCry* LoadCry(species_t a);
int16_t GetCryIndex(species_t index);
void PrintLevel(tile_t* hl, uint8_t lvl);
void PrintLevel_Force3Digits(tile_t* hl, uint8_t a);
void Print8BitNumLeftAlign(tile_t* hl, uint8_t a, uint8_t c);
void GetNthMove(void);
void GetBaseData(species_t species);
uint8_t* GetCurNickname(void);
void GetNickname(const uint8_t* hl, uint8_t a);
