void CountSetBits(void);
uint8_t CountSetBits_Conv(uint16_t hl, uint8_t b);
void GetWeekday(void);
uint8_t GetWeekday_Conv(void);
void SetSeenAndCaughtMon(void);
void SetSeenAndCaughtMon_Conv(dex_t c);
void SetSeenMon(void);
void SetSeenMon_Conv(dex_t c);
void CheckCaughtMon(void);
bool CheckCaughtMon_Conv(dex_t c);
void CheckSeenMon(void);
bool CheckSeenMon_Conv(dex_t c);
void PokedexFlagAction(void);
bool PokedexFlagAction_Conv(uint8_t* hl, dex_t c, uint8_t b);
