#include "../constants.h"
#include "random.h"
#include "math.h"
#include "../engine/battle/core.h"
#if ENHANCEMENT_USE_PCG
#include "../lib/pcg/pcg_basic.h"
#include "../lib/pcg/pcg_basic.c"
#endif

//  A simple hardware-based random number generator (RNG).
//  Two random numbers are generated by adding and subtracting
//  the divider to the respective values every time it's called.
//  The divider is a register that increments at a rate of 16384Hz.
//  For comparison, the Game Boy operates at a clock speed of 4.2MHz.
//  Additionally, an equivalent function is executed in VBlank.
//  This leaves a with the value in hRandomSub.
uint8_t Random(void) {
#if ENHANCEMENT_USE_PCG
    static uint8_t arr[] = {0, 0, 0, 0};
    static int i = 0;
    if(i == 0) {
        uint32_t n = pcg32_random();
        arr[0] = n & 0xff;
        arr[1] = (n >> 8) & 0xff;
        arr[2] = (n >> 16) & 0xff;
        arr[3] = (n >> 24) & 0xff;
    }

    hram->hRandomAdd = arr[i];
    hram->hRandomSub = arr[i + 1];
    i += 2;
    i &= 0x3;
    return hram->hRandomSub;
#else
    uint8_t f = REG_F;

    uint16_t temp;
    temp = (gb_read(rDIV) + hram->hRandomAdd + REG_F_C);
    advance_div();
    REG_F_C = (temp & 0xFF00)? 1 : 0;
    hram->hRandomAdd = (uint8_t)temp;

    temp = (gb_read(rDIV) - hram->hRandomSub - REG_F_C);
    REG_F_C = (temp & 0xFF00)? 1 : 0;
    advance_div();
    hram->hRandomSub = (uint8_t)temp;

    REG_F = f;

    return (uint8_t)(temp & 0xff);
#endif
}

//  _BattleRandom lives in another bank.
//  It handles all RNG calls in the battle engine, allowing
//  link battles to remain in sync using a shared PRNG.
uint8_t BattleRandom(void){
    // LDH_A_addr(hROMBank);
    // PUSH_AF;
    // LD_A(BANK(av_BattleRandom));
    // RST(aBankswitch);

    // CALL(av_BattleRandom);

    // LD_addr_A(wPredefHL + 1);
    // POP_AF;
    // RST(aBankswitch);
    // LD_A_addr(wPredefHL + 1);
    // RET;
    return v_BattleRandom_Conv();
}

//  Return a random number between 0 and a (non-inclusive).
uint8_t RandomRange(uint8_t a){
    // b = $100 % c
    uint8_t b = (uint8_t)(0x100 % a);

// Get a random number
// from 0 to $ff - b.
    uint8_t value;
    do {
        Random();
        value = hram->hRandomAdd;
    } while(value > 0xFF - b);

    return value % a;
}