void Serial(void);
uint8_t* Serial_ExchangeBytes(void* de_, const void* hl_, uint16_t bc);
uint8_t Serial_ExchangeByte(const uint8_t* hl);
bool CheckLinkTimeoutFramesNonzero(void);
// uint8_t SerialDisconnected(uint8_t a);
void Serial_ExchangeSyncBytes(void);
void Serial_PrintWaitingTextAndSyncAndExchangeNybble(void);
void Serial_SyncAndExchangeNybble(void);
void WaitLinkTransfer(void);
void LinkTransfer(void);
void LinkDataReceived(void);
void SetBitsForTimeCapsuleRequestIfNotLinked(void);
