void BattleCommand_BatonPass(void);
void BatonPass_LinkPlayerSwitch(void);
void BatonPass_LinkEnemySwitch(void);
void FailedBatonPass(void);
void ResetBatonPassStatus(void);
void CheckAnyOtherAlivePartyMons(void);
bool CheckAnyOtherAlivePartyMons_Conv(void);
void CheckAnyOtherAliveEnemyMons(void);
bool CheckAnyOtherAliveEnemyMons_Conv(void);
void CheckAnyOtherAliveMons(void);
bool CheckAnyOtherAliveMons_Conv(struct PartyMon* party, uint8_t count, uint8_t curMon);
