typedef struct EZChatWord {
    const char* word;
    uint16_t start;
} ezchatword_s;
bool Function11c05d(struct TextPrintState* state, uint8_t d, uint8_t e);
void Function11c075(uint8_t* de, uint8_t c);
void EZChat_RenderOneWord(struct TextPrintState* st, uint8_t d, uint8_t e);
void EZChat_RenderWords(uint8_t* de, const u8_pair_s* bc);
void Function11c082(void);
void Function11c08f(uint8_t* de, const uint8_t* bc);
const u8_pair_s* EZChat_RenderLine(uint8_t* hl, const u8_pair_s* bc, uint8_t a);
void PrintEZChatBattleMessage(tile_t* de, const uint8_t* bc);
uint8_t GetLengthOfWordAtC608(void);
uint8_t* CopyMobileEZChatToC608(uint8_t d, uint8_t e);
void Function11c1ab(void);
void Function11c1b9(void);
void Function11c254(uint8_t a);
void EZChat_ClearBottom12Rows(void);
void EZChat_MasterLoop(void);
void Function11c35f(void);
void Function11c373(void);
void Function11c38a(void);
extern const char String_11c3bc[];
void EZChatMenu_MessageLocationSetup(tile_t* hl);
void EZChatMenu_MessageSetup(void);
void Function11c3c2(void);
void Function11c3ed(void);
uint8_t Function11c4a5(void);
void Function11c4be(void);
extern const char String_11c4db[];
extern const char String_11c51b[];
void Function11c52c(void);
void Function11c53d(void);
void EZChat_PlaceCategoryNames(void);
void Function11c618(void);
extern const char EZChatString_Stop_Mode_Cancel[];
extern const uint16_t Coords_11c63a[];
void Function11c658(void);
void Function11c675(void);
void Function11c770(void);
void EZChat_DetermineWordCounts(void);
void Function11c7bc(void);
void EZChat_RenderWordChoices(void);
extern const uint16_t Unknown_11c854[];
void Function11c86e(void);
void BCD2String(void);
void MobileString_Page(void);
extern const char MobileString_Prev[];
extern const char MobileString_Next[];
void Function11c8f6(void);
void Function11c95d(void);
bool EZChat_SetOneWord(void);
void EZChatMenu_RerenderMessage(void);
uint8_t EZChatMenu_GetRealChosenWordSize(uint8_t a);
uint8_t EZChatMenu_DirectGetRealChosenWordSize(uint8_t d, uint8_t e);
uint8_t EZChat_GetSelectedCategory(uint8_t a);
uint8_t EZChat_GetWordSize(uint8_t a);
u8_pair_flag_s EZChatGetValidWordsLine(uint8_t a);
extern const uint16_t Unknown_11c986[];
void EZChat_ClearAllWords(void);
void Function11c992(void);
void Function11c9ab(void);
void Function11c9bd(void);
void Function11c9c3(void);
void Function11ca01(void);
void Function11ca19(void);
extern const char String_11ca38[];
extern const char String_11ca57[];
void Function11ca5e(void);
void Function11ca6a(uint8_t a);
void Function11ca7f(const char* de);
void Function11caad(void);
void Function11cab3(void);
extern const char String_11cb1c[];
extern const char String_11cb31[];
void Function11cb52(void);
void Function11cb66(void);
void Function11cbf5(void);
extern const char* const Unknown_11cc01[];
extern const char String_11cc09[];
extern const char String_11cc23[];
extern const char String_11cc42[];
extern const char String_11cc60[];
extern const char* const Unknown_11cc7e[];
extern const char String_11cc86[];
extern const char String_11cc9d[];
extern const char String_11ccb9[];
extern const char String_11ccd4[];
void Function11ccef(void);
void Function11cd04(void);
extern const char String_11cd10[];
void Function11cd20(void);
void Function11cd54(void);
void Function11cdaa(void);
void String_11cdc7(void);
void String_11cdd9(void);
void String_11cdf5(void);
void Function11ce0b(void);
void Function11ce2b(void);
void Unknown_11ceb9(void);
void String_11cf79(void);
void Function11cfb5(void);
extern const uint8_t Unknown_11cfba[];
extern const uint8_t Unknown_11cfbe[];
extern const uint8_t Unknown_11cfc2[];
extern const uint8_t Unknown_11cfc6[];
extern const uint8_t Unknown_11cfca[];
void Function11cfce(const uint8_t* de);
void Function11d035(const uint8_t* de);
void AnimateEZChatCursor(struct SpriteAnim* bc);
void Function11d323(void);
extern const uint16_t Palette_11d33a[];
void EZChat_GetSeenPokemonByKana(void);
void EZChat_GetCategoryWordsByKana(void);
extern const char SelectStartGFX[];
extern const char EZChatSlowpokeLZ[];
extern const char* const MobileEZChatCategoryNames[];
extern const ezchatword_s* const MobileEZChatCategoryPointers[];
extern const u8_pair_s MobileEZChatData_WordAndPageCounts[14];
extern const u16_pair_s EZChat_SortedWords[27];
//#include "data/pokemon/ezchat_order.h"
//#include "gfx/mobile/select_start.2bpp"
//#include "gfx/pokedex/slowpoke.2bpp.lz"
