typedef struct EZChatWord {
    const char* word;
    uint16_t start;
} ezchatword_s;
bool Function11c05d(struct TextPrintState* state, uint8_t d, uint8_t e);
void Function11c075(uint8_t* de, uint8_t c);
void Function11c082(void);
void Function11c08f(uint8_t* de, const uint8_t* bc);
void PrintEZChatBattleMessage(tile_t* de, const uint8_t* bc);
uint8_t GetLengthOfWordAtC608(void);
uint8_t* CopyMobileEZChatToC608(uint8_t d, uint8_t e);
void Function11c1ab(void);
void Function11c1b9(void);
void Function11c254(uint8_t a);
void EZChat_ClearBottom12Rows(void);
void EZChat_MasterLoop(void);
void Function11c35f(void);
void Function11c373(void);
void Function11c38a(void);
void String_11c3bc(void);
void Function11c3c2(void);
void Function11c3ed(void);
void Function11c4a5(void);
void Function11c4be(void);
void String_11c4db(void);
void String_11c51b(void);
void Function11c52c(void);
void Function11c53d(void);
void EZChat_PlaceCategoryNames(void);
void Function11c618(void);
void EZChatString_Stop_Mode_Cancel(void);
extern const uint16_t Coords_11c63a[];
void Function11c658(void);
void Function11c675(void);
void Function11c770(void);
void Function11c7bc(void);
void Unknown_11c854(void);
void Function11c86e(void);
void BCD2String(void);
void MobileString_Page(void);
extern const char MobileString_Prev[];
extern const char MobileString_Next[];
void Function11c8f6(void);
void Function11c95d(void);
void Unknown_11c986(void);
void Function11c992(void);
void Function11c9ab(void);
void Function11c9bd(void);
void Function11c9c3(void);
void Function11ca01(void);
void Function11ca19(void);
void String_11ca38(void);
void String_11ca57(void);
void Function11ca5e(void);
void Function11ca6a(void);
void Function11ca7f(void);
void Function11caad(void);
void Function11cab3(void);
void String_11cb1c(void);
void String_11cb31(void);
void Function11cb52(void);
void Function11cb66(void);
void Function11cbf5(void);
void Unknown_11cc01(void);
void String_11cc09(void);
void String_11cc23(void);
void String_11cc42(void);
void String_11cc60(void);
void Unknown_11cc7e(void);
void String_11cc86(void);
void String_11cc9d(void);
void String_11ccb9(void);
void String_11ccd4(void);
void Function11ccef(void);
void Function11cd04(void);
void String_11cd10(void);
void Function11cd20(void);
void Function11cd54(void);
void Function11cdaa(void);
void String_11cdc7(void);
void String_11cdd9(void);
void String_11cdf5(void);
void Function11ce0b(void);
void Function11ce2b(void);
void Unknown_11ceb9(void);
void String_11cf79(void);
void Function11cfb5(void);
void Unknown_11cfba(void);
void Unknown_11cfbe(void);
void Unknown_11cfc2(void);
void Unknown_11cfc6(void);
void Unknown_11cfca(void);
void Function11cfce(void);
void Function11d035(void);
void AnimateEZChatCursor(void);
void Function11d323(void);
void Palette_11d33a(void);
void EZChat_GetSeenPokemonByKana(void);
void EZChat_GetCategoryWordsByKana(void);
void SelectStartGFX(void);
void EZChatSlowpokeLZ(void);
extern const char* const MobileEZChatCategoryNames[];
extern const ezchatword_s* const MobileEZChatCategoryPointers[];
extern const u8_pair_s MobileEZChatData_WordAndPageCounts[];
void EZChat_SortedWords(void);
//#include "data/pokemon/ezchat_order.h"
//#include "gfx/mobile/select_start.2bpp"
//#include "gfx/pokedex/slowpoke.2bpp.lz"
