typedef struct {
    uint16_t offset;
    uint8_t bytes[6];
} Unknown_8b529_s;
void Function8b342(void);
void Function8b35d(void);
void Function8b363(void);
void Function8b36c(uint8_t* bc);
uint8_t Function8b379(uint8_t* bc, uint8_t e);
void Function8b385(uint8_t* bc, uint8_t d, uint8_t e);
u8_flag_s Function8b391(uint8_t* bc);
bool Function8b3a4(const uint8_t* hl, const uint8_t* bc);
u8_flag_s Function8b3b0(void);
void Function8b3cd(tile_t* hl, uint8_t* bc);
u8_flag_s Function8b3dd(uint8_t* bc, uint8_t* e);
bool Function8b45c(uint8_t* bc);
void Function8b493(uint8_t* bc);
void Jumptable_8b4a0(uint8_t* bc, uint8_t a);
void Function8b4a4(uint8_t* bc);
void Function8b4b8(uint8_t* bc);
tile_t* Function8b4cc(void);
tile_t* Function8b4d8(uint8_t* b, uint8_t* c);
tile_t* Function8b4ea(uint8_t* b, uint8_t* c);
void Function8b4fd(uint8_t* d, uint8_t* b, uint8_t* c);
const Unknown_8b529_s* Function8b50a(const Unknown_8b529_s* hl);
tile_t* Function8b518(tile_t* hl);
uint8_t Function8b521(void);
extern const Unknown_8b529_s Unknown_8b529[];
void Function8b539(void);
bool Function8b555(void);
extern const txt_cmd_s EnterNewPasscodeText[];
extern const txt_cmd_s ConfirmPasscodeText[];
extern const txt_cmd_s PasscodesNotSameText[];
extern const txt_cmd_s PasscodeSetText[];
extern const txt_cmd_s FourZerosInvalidText[];
bool Function8b5e7(void);
extern const txt_cmd_s EnterPasscodeText[];
extern const txt_cmd_s IncorrectPasscodeText[];
extern const txt_cmd_s UnknownText_0x8b64c[];
bool Function8b664(uint8_t* bc);
void Function8b677(void);
void Function8b690(void);
void Function8b6bb(void);
extern const uint16_t Palette_8b6d5[];
void Function8b6ed(void);
void Function8b703(tile_t* hl, uint8_t b, uint8_t c);
void Function8b732(tile_t* hl, uint8_t c);
tile_t* Function8b73e(tile_t* hl, uint8_t a, uint8_t c);
void Function8b744(tile_t* tm, uint8_t b, uint8_t c);
void Function8b75d(void);
void Function8b787(void);
void Function8b788(tile_t* hl, uint8_t c);
void Function8b79e(void);
uint8_t Function8b7bd(void);
void Function8b832(void);
void Function8b83e(void);
void Function8b84b(uint8_t pos);
void Function8b855(void);
extern const struct MenuHeader MenuHeader_0x8b867;
extern const struct MenuData MenuData_0x8b870;
void Function8b880(const struct MenuData *data, tile_t *de);
void Function8b88c(const struct MenuData *data, tile_t *de);
void Function8b8c8(void);
extern const char* const Unknown_8b903[];
extern const char String_8b90b[];
extern const char String_8b919[];
extern const char String_8b92a[];
extern const char String_8b938[];
void Function8b94a(uint8_t a);
uint8_t Function8b960(void);
uint8_t Function8b99f(uint8_t a);
void Function8b9ab(void);
extern const struct MenuHeader MenuHeader_0x8b9ac;
extern const struct MenuHeader MenuHeader_0x8b9b1;
extern const struct MenuData MenuData_0x8b9b9;
extern const struct MenuHeader MenuHeader_0x8b9ca;
extern const struct MenuData MenuData_0x8b9d2;
bool Function8b9e9(void);
extern const uint8_t Unknown_8ba1c[];
extern const uint8_t Unknown_8ba1f[];
