void MobileCheckOwnMonAnywhere(void);
void UnusedFindItemInPCOrBag(void);
bool Function4a94e(void);
extern const txt_cmd_s MobilePickThreeMonForBattleText[];
bool Function4a9c3(void);
bool Function4a9d7(void);
extern const txt_cmd_s MobileUseTheseThreeMonText[];
u8_flag_s Function4aa22(void);
u8_flag_s Function4aa25(void);
u8_flag_s Function4aa34(void);
void Function4aa6e(void);
void Function4aa7a(void);
void Function4aab6(void);
void Function4aad3(void);
bool Function4aafb(void);
bool Function4ab06(void);
u8_flag_s Function4ab1a(void);
bool Function4ab99(uint8_t);
bool Function4aba8(void);
bool Function4abc3(uint8_t a);
void Function4ac58(void);
extern const struct MenuHeader MenuHeader_0x4aca2;
void Function4acaa(void);
void Function4ad17(void);
extern const txt_cmd_s MobileOnlyThreeMonMayEnterText[];
void Function4ad56(void);
void Function4ad60(void);
void Function4ad67(void);
void Function4ad68(void);
extern const char String_4ad88[];
extern const char String_4ad9a[];
extern const char String_4ada0[];
extern const char String_4ada7[];
uint8_t* Function4adb2(void);
void Function4adc2(void);
void Function4adf7(void);
