void StubbedTrainerRankings_HallOfFame2(void);
void StubbedTrainerRankings_MagikarpLength(void);
void StubbedTrainerRankings_BugContestScore(uint16_t score);
void StubbedTrainerRankings_AddToSlotsWinStreak(void);
void StubbedTrainerRankings_EndSlotsWinStreak(void);
void StubbedTrainerRankings_AddToSlotsPayouts(void);
void StubbedTrainerRankings_AddToBattlePayouts(const uint8_t* bc);
void StubbedTrainerRankings_StepCount(void);
void StubbedTrainerRankings_BattleTowerWins(void);
void StubbedTrainerRankings_TMsHMsTaught(void);
void StubbedTrainerRankings_Battles(void);
void StubbedTrainerRankings_WildBattles(void);
void StubbedTrainerRankings_TrainerBattles(void);
void StubbedTrainerRankings_Unused1(void);
void StubbedTrainerRankings_HallOfFame(void);
void StubbedTrainerRankings_WildMonsCaught(void);
void StubbedTrainerRankings_HookedEncounters(void);
void StubbedTrainerRankings_EggsHatched(void);
void StubbedTrainerRankings_MonsEvolved(void);
void StubbedTrainerRankings_FruitPicked(void);
void StubbedTrainerRankings_Healings(void);
void StubbedTrainerRankings_MysteryGift(void);
void StubbedTrainerRankings_Trades(void);
void StubbedTrainerRankings_Fly(void);
void StubbedTrainerRankings_Surf(void);
void StubbedTrainerRankings_Waterfall(void);
void StubbedTrainerRankings_WhiteOuts(void);
void StubbedTrainerRankings_LuckyNumberShow(void);
void StubbedTrainerRankings_PhoneCalls(void);
void StubbedTrainerRankings_Unused2(void);
void StubbedTrainerRankings_LinkBattles(void);
void StubbedTrainerRankings_Splash(void);
void StubbedTrainerRankings_TreeEncounters(void);
void StubbedTrainerRankings_Unused3(void);
void StubbedTrainerRankings_ColosseumWins(void);
void StubbedTrainerRankings_ColosseumLosses(void);
void StubbedTrainerRankings_ColosseumDraws(void);
void StubbedTrainerRankings_Selfdestruct(void);
void StubbedTrainerRankings_Increment4Byte(uint16_t hl);
void StubbedTrainerRankings_Increment3Byte(uint16_t hl);
void StubbedTrainerRankings_Increment2Byte(uint16_t hl);
void StubbedTrainerRankings_Increment1Byte(uint16_t hl);
void StubbedTrainerRankings_Increment(uint16_t v, uint16_t bc);
void UpdateTrainerRankingsChecksum2(void);
void UpdateTrainerRankingsChecksum(void);
uint16_t CalculateTrainerRankingsChecksum(void);
void BackupMobileEventIndex(void);
void RestoreMobileEventIndex(void);
void VerifyTrainerRankingsChecksum(void);
void DeleteMobileEventIndex(void);
void InitializeTrainerRankings(void);
void v_MobilePrintNum(void);
void Mobile_DummyReturnFalse(void);
void SetMobileAdapterStatus(uint8_t c); // Stubbed_Function106314
u8_flag_s Mobile_AlwaysReturnNotCarry(void);
u8_flag_s CheckMobileAdapterStatus(void); // Function106331
void Function10635c(void);
void Function106392(void);
void Function1063cc(void);
void Function1063d8(void);
void Function1063e5(void);
void Function1063f3(void);
void Function106403(void);
void Function106442(void);
void Function106453(void);
void Stubbed_Function106462(void);
void Function106464(void);
void Function10649b(void);
void Function1064c3(void);
void Function1064d8(void);
void asm_1064ed(void);
void Function10650a(void);
extern const char MobileDialingFrameGFX[];
//#include "gfx/mobile/dialing_frame.2bpp"
