bool MainMenu_Mobile(void);
void Function49f0a(void);
void Function49f16(void);
extern const char MobileString1[];
extern const char* MobileStrings2[];
// void String_0x49fe9(void);
void MobileMenu_InitMenuBuffers(void);
void Function4a098(void);
void Function4a0b9(void);
void Function4a0c2(void);
void Function4a100(void);
void asm_4a111(void);
void Function4a118(void);
void Function4a13b(void);
void Function4a149(void);
// void Function4a195(void);
// void asm_4a19d(void);
extern const char String_4a1ef[];
void Function4a20e(void);
void Function4a221(void);
void Function4a239(void);
extern const char* Strings_4a23d[];
bool Function4a28a(void);
void MenuHeader_0x4a346(void);
extern const char String_4a34b[];
extern const txt_cmd_s DeleteSavedLoginPasswordText[];
extern const txt_cmd_s DeletedTheLoginPasswordText[];
extern const struct MenuHeader DeletePassword_YesNo_MenuHeader;
// void MenuData_0x4a36a(void);
void Function4a373(void);
void Function4a39a(void);
void Function4a3a7(void);
void Function4a3aa(void);
void Function4a449(void);
void Function4a485(void);
void Function4a492(void);
bool MainMenu_MobileStudium(void);
void Function4a4c4(void);
// void Function4a545(void);
// void asm_4a54d(void);
// void Function4a5b0(void);
extern const char String_4a5c5[];
extern const char String_4a5cd[];
extern const char String_4a5da[];
extern const char String_4a5e6[];
extern const char String_4a5f2[];
extern const char* Strings_4a5f6[];
void Function4a680(void);
void Function4a6ab(void);
void Function4a6c5(uint16_t de);
tile_t* Function4a6d8(tile_t* hl, uint8_t b, uint8_t c, uint8_t a);