uint8_t InitMobileProfile(uint8_t c);
void Function48157(void);
void asm_4815f(void);
void Function48187(void);
uint8_t Function4820d(void);
void Function48272(void);
extern const char MobileString_PersonalInfo[];
void Function48283(void);
void asm_4828d(void);
void Function48304(void);
bool Function48383(uint8_t a, uint16_t de);
void Function483bb(void);
void Function483e8(const struct MenuData* data, tile_t* de);
void Function4840c(void);
void Mobile12_Bin2Dec(tile_t* hl, uint8_t a);
extern const char MobileProfileString[];
extern const char MobileString_Gender[];
extern const char MobileString_Age[];
extern const char MobileString_Address[];
extern const char MobileString_ZipCode[];
extern const char MobileString_OK[];
extern const char MobileString_ProfileChanged[];
extern const char MobileDesc_Gender[];
extern const char MobileDesc_Age[];
extern const char MobileDesc_Address[];
extern const char MobileDesc_ZipCode[];
extern const struct MenuHeader MenuHeader_0x484f1;
extern const struct MenuData MenuData_0x484f9;
extern const char* Strings_484fb[];
// void String_484fb(void);
// void String_484ff(void);
extern const struct MenuHeader MenuHeader_0x48504;
extern const struct MenuHeader MenuHeader_0x48509;
extern const struct MenuHeader MenuHeader_0x4850e;
extern const struct MenuHeader MenuHeader_0x48513;
extern const struct MenuData MenuData_0x4851b;
extern const char* Prefectures[];
// void Aichi(void);
// void Aomori(void);
// void Akita(void);
// void Ishikawa(void);
// void Ibaraki(void);
// void Iwate(void);
// void Ehime(void);
// void Oita(void);
// void Osakafu(void);
// void Okayama(void);
// void Okinawa(void);
// void Kagawa(void);
// void Kagoshima(void);
// void Kanagawa(void);
// void Gifu(void);
// void Kyotofu(void);
// void Kumamoto(void);
// void Gunma(void);
// void Kochi(void);
// void Saitama(void);
// void Saga(void);
// void Shiga(void);
// void Shizuoka(void);
// void Shimane(void);
// void Chiba(void);
// void Tokyo(void);
// void Tokushima(void);
// void Tochigi(void);
// void Tottori(void);
// void Toyama(void);
// void Nagasaki(void);
// void Nagano(void);
// void Naraken(void);
// void Niigata(void);
// void Hyogo(void);
// void Hiroshima(void);
// void Fukui(void);
// void Fukuoka(void);
// void Fukushima(void);
// void Hokkaido(void);
// void Mie(void);
// void Miyagi(void);
// void Miyazaki(void);
// void Yamagata(void);
// void Yamaguchi(void);
// void Yamanashi(void);
// void Wakayama(void);
void Function48689(void);
void Function486bf(void);
bool Function48725(void);
void Function4873c(void);
void Function4876f(void);
void Function487ec(tile_t* hl);
void Function487ff(tile_t* hl, const uint8_t* de);
extern const char String_4880d[];
u8_flag_s Function4880e(void);
u8_flag_s Function488b4(void);
u8_flag_s Function488b9(void);
extern const char MobileUpArrowGFX[];
extern const char MobileDownArrowGFX[];
void Function488d3(void);
void asm_48922(uint16_t bc, uint16_t de, uint8_t b, uint8_t d, uint8_t inMenu);
void Function4895a(void);
// void Function4896e(uint16_t bc, uint16_t de, uint8_t d);
// void asm_48972(uint16_t bc, uint16_t de, uint8_t b, uint8_t d);
void Function489ea(tile_t* hl);
extern const char String_48a38[];
bool Function48a3a(void);
// void Function48a9a(void);
extern const struct MenuHeader MenuHeader_0x48a9c;
extern const char String_48aa1[];
u8_flag_s Function48ab5(uint8_t* d);
u8_flag_s asm_48bc7(void);
u8_flag_s Function48bd7(uint8_t* d);
u8_flag_s Function48c00(uint8_t a);
u8_flag_s Function48c0d(void);
u8_flag_s Function48c0f(uint8_t a);
void Function48c11(tile_t* hl, uint8_t b, uint8_t d);
void Function48c4d(uint8_t* hl, uint8_t a);
void Function48c5a(uint8_t* hl, uint8_t a);
bool Function48c63(uint8_t* de, uint8_t c);
void Function48c8e(void);
void Function48ca3(void);
void Function48cda(tile_t* de, uint8_t b, uint8_t c);
void Function48cdc(tile_t* hl, uint8_t b, uint8_t c);
void Function48cfd(tile_t* hl, uint8_t b, uint8_t c);
tile_t* Function48d2a(tile_t* hl, tile_t a, uint8_t c);
void Function48d30(void);
void Function48d3d(void);
void Function48d4a(uint8_t* hl);
void Function48d94(uint8_t* hl);
//#include "gfx/mobile/up_arrow.1bpp"
//#include "gfx/mobile/down_arrow.1bpp"
