void Intro_MainMenu();
void IntroMenu_DummyFunction(void);
void PrintDayOfWeek(void);
void NewGame_ClearTilemapEtc(void);
void MysteryGift(void);
void Option(void);
void NewGame(void);
void AreYouABoyOrAreYouAGirl(void);
void DebugRoom(void);
void ResetWRAM(void);
void v_ResetWRAM(void);
void SetDefaultBoxNames(void);
void InitializeMagikarpHouse(void);
void InitializeNPCNames(void);
void InitializeWorld(void);
void LoadOrRegenerateLuckyIDNumber(void);
void Continue(void);
void SpawnAfterRed(void);
void PostCreditsSpawn(void);
void Continue_MobileAdapterMenu(void);
void ConfirmContinue(void);
void Continue_CheckRTC_RestartClock(void);
void FinishContinueFunction(void);
void DisplaySaveInfoOnContinue(void);
void DisplaySaveInfoOnSave(void);
void DisplayNormalContinueData(void);
void DisplayContinueDataWithRTCError(void);
void Continue_LoadMenuHeader(void);
void Continue_DisplayBadgesDexPlayerName(void);
void Continue_PrintGameTime(void);
void Continue_UnknownGameTime(void);
void Continue_DisplayBadgeCount(void);
void Continue_DisplayPokedexNumCaught(void);
void Continue_DisplayGameTime(void);
void OakSpeech(void);
extern const struct TextCmd OakText1[];
extern const struct TextCmd OakText2[];
extern const struct TextCmd OakText3[];
extern const struct TextCmd OakText4[];
extern const struct TextCmd OakText5[];
extern const struct TextCmd OakText6[];
extern const struct TextCmd OakText7[];
void NamePlayer(void);
void GSShowPlayerNamingChoices(void);
void StorePlayerName(void);
void ShrinkPlayer(void);
void Intro_RotatePalettesLeftFrontpic(void);
void IntroFadePalettes(void);
void Intro_WipeInFrontpic(void);
void Intro_PrepTrainerPic(void);
void ShrinkFrame(void);
void Intro_PlacePlayerSprite(void);
void IntroSequence(void);
void StartTitleScreen(void);
void RunTitleScreen(void);
void UnusedTitlePerspectiveScroll(void);
void TitleScreenScene(void);
void TitleScreenNextScene(void);
void TitleScreenEntrance(void);
void TitleScreenTimer(void);
void TitleScreenMain(void);
void TitleScreenEnd(void);
void DeleteSaveData(void);
void ResetClock(void);
void UpdateTitleTrailSprite(void);
void Copyright(void);
// void CopyrightString(void);
extern uint8_t CopyrightString[];
void GameInit(void);
