bool v_2DMenu_(void);
bool v_InterpretBattleMenu(void);
void v_InterpretMobileMenu(void);
void Draw2DMenu(const struct MenuData* data);
bool Get2DMenuSelection(const struct MenuData* data);
bool Mobile_GetMenuSelection(const struct MenuData* data);
uint8_t Get2DMenuNumberOfColumns(const struct MenuData* data);
uint8_t Get2DMenuNumberOfRows(const struct MenuData* data);
void Place2DMenuItemStrings(const struct MenuData* data);
void Init2DMenuCursorPosition(const struct MenuData* data);
void v_StaticMenuJoypad(void);
void v_ScrollingMenuJoypad(void);
uint8_t MobileMenuJoypad(void);
void Function241d5(void);
void MenuJoypadLoop(void);
bool Do2DMenuRTCJoypad(void);
bool Menu_WasButtonPressed(void);
bool v_2DMenuInterpretJoypad(void);
void Move2DMenuCursor(void);
void Place2DMenuCursor(void);
void v_PushWindow(void);
void v_ExitMenu(void);
void RestoreOverworldMapTiles(void);
void Error_Cant_ExitMenu(void);
void v_InitVerticalMenuCursor(const struct MenuData* data);

extern struct MenuHeader gWindowStack[32];
extern uint8_t gTileBackupStack[32][SCREEN_WIDTH * SCREEN_HEIGHT * 2];
extern uint32_t gWindowStackPointer;
