void v_2DMenu_(void);
bool v_2DMenu__Conv(void);
void v_InterpretBattleMenu(void);
bool v_InterpretBattleMenu_Conv(void);
void v_InterpretMobileMenu(void);
void Draw2DMenu(void);
void Draw2DMenu_Conv(const struct MenuData* data);
void Get2DMenuSelection(void);
bool Get2DMenuSelection_Conv(const struct MenuData* data);
void Mobile_GetMenuSelection(void);
bool Mobile_GetMenuSelection_Conv(const struct MenuData* data);
void Get2DMenuNumberOfColumns(void);
uint8_t Get2DMenuNumberOfColumns_Conv(void);
uint8_t Get2DMenuNumberOfColumns_Conv2(const struct MenuData* data);
void Get2DMenuNumberOfRows(void);
uint8_t Get2DMenuNumberOfRows_Conv(void);
uint8_t Get2DMenuNumberOfRows_Conv2(const struct MenuData* data);
void Place2DMenuItemStrings(void);
void Place2DMenuItemStrings_Conv(const struct MenuData* data);
void Init2DMenuCursorPosition(void);
void Init2DMenuCursorPosition_Conv(const struct MenuData* data);
void v_StaticMenuJoypad(void);
void v_StaticMenuJoypad_Conv(void);
void v_ScrollingMenuJoypad(void);
void v_ScrollingMenuJoypad_Conv(void);
void MobileMenuJoypad(void);
void Function241d5(void);
void MenuJoypadLoop(void);
void MenuJoypadLoop_Conv(void);
void Do2DMenuRTCJoypad(void);
bool Do2DMenuRTCJoypad_Conv(void);
void Menu_WasButtonPressed(void);
bool Menu_WasButtonPressed_Conv(void);
void v_2DMenuInterpretJoypad(void);
bool v_2DMenuInterpretJoypad_Conv(void);
void Move2DMenuCursor(void);
void Move2DMenuCursor_Conv(void);
void Place2DMenuCursor(void);
void Place2DMenuCursor_Conv(void);
void v_PushWindow(void);
void v_PushWindow_Conv(void);
void v_ExitMenu(void);
void v_ExitMenu_Conv(void);
void v_ExitMenu_Conv2(void);
void RestoreOverworldMapTiles(void);
void Error_Cant_ExitMenu(void);
void Error_Cant_ExitMenu_Conv(void);
void v_InitVerticalMenuCursor(void);
void v_InitVerticalMenuCursor_Conv(const struct MenuData* data);

extern struct MenuHeader gWindowStack[32];
extern uint8_t gTileBackupStack[32][SCREEN_WIDTH * SCREEN_HEIGHT * 2];
extern uint32_t gWindowStackPointer;
