void PlaceMenuItemName(void);
void PlaceMenuItemQuantity(void);
void PlaceMoneyTopRight(void);
void PlaceMoneyBottomLeft(void);
void PlaceMoneyAtTopLeftOfTextbox(void);
void PlaceMoneyTextbox(void);
void MoneyTopRightMenuHeader(void);
void MoneyBottomLeftMenuHeader(void);
void DisplayCoinCaseBalance(void);
void DisplayMoneyAndCoinBalance(void);
void MoneyString(void);
void CoinString(void);
void ShowMoney_TerminatorString(void);
void StartMenu_PrintSafariGameStatus(void);
void StartMenu_DrawBugContestStatusBox(void);
void StartMenu_PrintBugContestStatus(void);
void FindApricornsInBag(void);
//#include "data/items/apricorn_balls.h"
