void v_Option(void);
extern const char StringOptions[];
// bool Options_TextSpeed(void);
bool Options_BattleScene(void);
bool Options_BattleStyle(void);
bool Options_Sound(void);
bool Options_Print(void);
bool Options_MenuAccount(void);
bool Options_Frame(void);
bool UpdateFrame(void);
// bool Options_Cancel(void);
// bool OptionsControl(void);
void Options_UpdateCursorPosition(void);
