void v_Option(void);
extern const char StringOptions[];
void Options_TextSpeed(void);
bool Options_TextSpeed_Conv(void);
void GetTextSpeed(void);
bool Options_BattleScene(void);
bool Options_BattleStyle(void);
bool Options_Sound(void);
bool Options_Print(void);
void GetPrinterSetting(void);
bool Options_MenuAccount(void);
bool Options_Frame(void);
bool UpdateFrame(void);
void Options_Cancel(void);
bool Options_Cancel_Conv(void);
void OptionsControl(void);
bool OptionsControl_Conv(void);
void Options_UpdateCursorPosition(void);
