void StartMenu(void);
// uint8_t StartMenu_Exit(void);
// uint8_t StartMenu_Quit(void);
// uint8_t StartMenu_Save(void);
// uint8_t StartMenu_Option(void);
// uint8_t StartMenu_Status(void);
// uint8_t StartMenu_Pokedex(void);
// uint8_t StartMenu_Pokegear(void);
// uint8_t StartMenu_Pack(void);
// uint8_t StartMenu_Pokemon(void);
