void TrainerCard(void);
void TrainerCard_IncrementJumptable(void);
void TrainerCard_Quit(void);
void TrainerCard_Page1_LoadGFX(void);
void TrainerCard_Page1_Joypad(void);
void TrainerCard_Page2_LoadGFX(void);
void TrainerCard_Page2_Joypad(void);
void TrainerCard_Page3_LoadGFX(void);
void TrainerCard_Page3_Joypad(void);
void TrainerCard_PrintTopHalfOfCard(void);
void TrainerCard_Page1_PrintDexCaught_GameTime(void);
void TrainerCard_Page2_3_InitObjectsAndStrings(void);
void TrainerCardSetup_PlaceTilemapString(tile_t* hl, const uint8_t* de);
void TrainerCard_InitBorder(tile_t* hl, uint8_t d);
uint8_t TrainerCard_Page2_3_PlaceLeadersFaces(tile_t* hl, uint8_t a);
void TrainerCard_Page1_PrintGameTime(void);
// void TrainerCard_Page2_3_AnimateBadges(void);
// void TrainerCard_Page2_3_OAMUpdate(void);
// void TrainerCard_JohtoBadgesOAM(void);
// void CardStatusGFX(void);
// void LeaderGFX(void);
// void LeaderGFX2(void);
// void BadgeGFX(void);
// void BadgeGFX2(void);
// void CardRightCornerGFX(void);
