void ClearCmdQueue(void);
void HandleCmdQueue(void);
void GetNthCmdQueueEntry(void);
void WriteCmdQueue(void);
bool WriteCmdQueue_Conv(const struct CmdQueue* hl);
void DelCmdQueue(void);
bool DelCmdQueue_Conv(uint8_t b);
void v_DelCmdQueue(void);
void HandleQueuedCommand(void);
void HandleQueuedCommand_Conv(struct CmdQueue* bc);
void CmdQueues_AnonJumptable(void);
void CmdQueues_IncAnonJumptableIndex(void);
void CmdQueues_IncAnonJumptableIndex_Conv(uint8_t* bc);
void CmdQueues_DecAnonJumptableIndex(void);
void CmdQueues_DecAnonJumptableIndex_Conv(uint8_t* bc);
void CmdQueue_Null(void);
void CmdQueue_Type1(void);
void CmdQueue_Type4(void);
void CmdQueue_Type4_Conv(uint8_t* bc);
void CmdQueue_Type3(void);
void CmdQueue_Type3_Conv(uint8_t* bc);
void CmdQueue_StoneTable(void);
void CmdQueue_StoneTable_Conv(struct CmdQueue* bc);
