void ClearCmdQueue(void);
void HandleCmdQueue(void);
void GetNthCmdQueueEntry(void);
bool WriteCmdQueue(const struct CmdQueue* hl);
bool DelCmdQueue(uint8_t b);
void v_DelCmdQueue(uint8_t* bc);
// void HandleQueuedCommand(struct CmdQueue* bc);
void CmdQueues_AnonJumptable(void);
// void CmdQueues_IncAnonJumptableIndex(uint8_t* bc);
// void CmdQueues_DecAnonJumptableIndex(uint8_t* bc);
void CmdQueue_Null(void);
void CmdQueue_Type1(void);
// void CmdQueue_Type4(uint8_t* bc);
// void CmdQueue_Type3(uint8_t* bc);
// void CmdQueue_StoneTable(struct CmdQueue* bc);
