void InitDecorations(void);
void v_PlayerDecorationMenu(void);
void Deco_FillTempWithMinusOne(void);
void CheckAllDecorationFlags(void);
void AppendDecoIndex(void);
void FindOwnedDecosInCategory(void);
void DecoBedMenu(void);
void FindOwnedBeds(void);
void DecoCarpetMenu(void);
void FindOwnedCarpets(void);
void DecoPlantMenu(void);
void FindOwnedPlants(void);
void DecoPosterMenu(void);
void FindOwnedPosters(void);
void DecoConsoleMenu(void);
void FindOwnedConsoles(void);
void DecoOrnamentMenu(void);
void FindOwnedOrnaments(void);
void DecoBigDollMenu(void);
void FindOwnedBigDolls(void);
void DecoExitMenu(void);
void PopulateDecoCategoryMenu(void);
void GetDecorationData(void);
void GetDecorationName(void);
void DecorationMenuFunction(void);
void DoDecorationAction2(void);
uint16_t GetDecorationFlag(uint8_t c);
uint8_t DecorationFlagAction(uint8_t c, uint8_t b);
void GetDecorationSprite(void);
uint8_t GetDecorationSprite_Conv(uint8_t c);
void GetDecoName(void);
const uint8_t* GetDecoName_Conv(const struct Decoration* hl);
void DecoAction_nothing(void);
void DecoAction_setupbed(void);
void DecoAction_putawaybed(void);
void DecoAction_setupcarpet(void);
void DecoAction_putawaycarpet(void);
void DecoAction_setupplant(void);
void DecoAction_putawayplant(void);
void DecoAction_setupposter(void);
void DecoAction_putawayposter(void);
void DecoAction_setupconsole(void);
void DecoAction_putawayconsole(void);
void DecoAction_setupbigdoll(void);
void DecoAction_putawaybigdoll(void);
void DecoAction_TrySetItUp(void);
void DecoAction_SetItUp(void);
void DecoAction_TryPutItAway(void);
void DecoAction_setupornament(void);
void DecoAction_putawayornament(void);
void DecoAction_FinishUp_Ornament(void);
void DecoAction_SetItUp_Ornament(void);
void WhichSidePutOnText(void);
void DecoAction_PutItAway_Ornament(void);
void WhichSidePutAwayText(void);
void DecoAction_AskWhichSide(void);
void QueryWhichSide(void);
void DecoSideMenuHeader(void);
void PutAwayTheDecoText(void);
void NothingToPutAwayText(void);
void SetUpTheDecoText(void);
void PutAwayAndSetUpText(void);
void AlreadySetUpText(void);
void GetDecorationName_c_de(void);
uint8_t DecorationFlagAction_c(uint8_t c, uint8_t b);
uint8_t* GetDecorationName_c(uint8_t c);
void SetSpecificDecorationFlag(void);
void SetSpecificDecorationFlag_Conv(uint8_t c);
uint8_t GetDecorationID(uint8_t c);
void SetAllDecorationFlags(void);
void DescribeDecoration(void);
Script_fn_t DescribeDecoration_Conv(uint8_t b);
void DecorationDesc_Poster(void);
Script_fn_t DecorationDesc_Poster_Conv(uint8_t poster);
bool DecorationDesc_TownMapPoster(script_s*);
bool DecorationDesc_PikachuPoster(script_s*);
bool DecorationDesc_ClefairyPoster(script_s*);
bool DecorationDesc_JigglypuffPoster(script_s*);
bool DecorationDesc_NullPoster(script_s*);
void DecorationDesc_LeftOrnament(void);
Script_fn_t DecorationDesc_LeftOrnament_Conv(void);
void DecorationDesc_RightOrnament(void);
Script_fn_t DecorationDesc_RightOrnament_Conv(void);
void DecorationDesc_Console(void);
Script_fn_t DecorationDesc_Console_Conv(void);
void DecorationDesc_OrnamentOrConsole(void);
Script_fn_t DecorationDesc_OrnamentOrConsole_Conv(uint8_t c);
void DecorationDesc_GiantOrnament(void);
Script_fn_t DecorationDesc_GiantOrnament_Conv(void);
void ToggleMaptileDecorations(void);
void SetPosterVisibility(void);
void SetDecorationTile(void);
void SetDecorationTile_Conv(uint8_t a, uint8_t d, uint8_t e);
void ToggleDecorationsVisibility(void);
void ToggleDecorationVisibility(void);
void ToggleDecorationVisibility_Conv(uint8_t* hl, uint16_t de, uint8_t a);
void v_GetDecorationSprite(void);
uint8_t v_GetDecorationSprite_Conv(uint8_t a);
void PadCoords_de(void);
uint8_t* PadCoords_de_Conv(uint8_t d, uint8_t e);
//#include "data/decorations/attributes.h"
//#include "data/decorations/names.h"
//#include "data/decorations/decorations.h"
