void InitDecorations(void);
uint8_t v_PlayerDecorationMenu(void);
void Deco_FillTempWithMinusOne(void);
void CheckAllDecorationFlags(const uint8_t* hl);
void AppendDecoIndex(uint8_t a);
bool FindOwnedDecosInCategory(const uint8_t* hl, uint8_t c);
u8_flag_s DecoBedMenu(void);
bool FindOwnedBeds(void);
u8_flag_s DecoCarpetMenu(void);
bool FindOwnedCarpets(void);
u8_flag_s DecoPlantMenu(void);
bool FindOwnedPlants(void);
u8_flag_s DecoPosterMenu(void);
bool FindOwnedPosters(void);
u8_flag_s DecoConsoleMenu(void);
bool FindOwnedConsoles(void);
u8_flag_s DecoOrnamentMenu(void);
bool FindOwnedOrnaments(void);
u8_flag_s DecoBigDollMenu(void);
bool FindOwnedBigDolls(void);
u8_flag_s DecoExitMenu(void);
void PopulateDecoCategoryMenu(void);
void GetDecorationData(void);
void GetDecorationName(void);
void DecorationMenuFunction(const char** str, uint8_t* de, uint8_t a);
void DoDecorationAction2(void);
uint16_t GetDecorationFlag(uint8_t c);
uint8_t DecorationFlagAction(uint8_t c, uint8_t b);
void GetDecorationSprite(void);
uint8_t GetDecorationSprite_Conv(uint8_t c);
void GetDecoName(void);
const uint8_t* GetDecoName_Conv(const struct Decoration* hl);
void DecoAction_nothing(void);
void DecoAction_setupbed(void);
void DecoAction_putawaybed(void);
void DecoAction_setupcarpet(void);
void DecoAction_putawaycarpet(void);
void DecoAction_setupplant(void);
void DecoAction_putawayplant(void);
void DecoAction_setupposter(void);
void DecoAction_putawayposter(void);
void DecoAction_setupconsole(void);
void DecoAction_putawayconsole(void);
void DecoAction_setupbigdoll(void);
void DecoAction_putawaybigdoll(void);
bool DecoAction_TrySetItUp(uint8_t* hl);
bool DecoAction_SetItUp(void);
bool DecoAction_TryPutItAway(uint8_t* hl);
void DecoAction_setupornament(void);
void DecoAction_putawayornament(void);
bool DecoAction_FinishUp_Ornament(void);
bool DecoAction_SetItUp_Ornament(void);
extern const txt_cmd_s WhichSidePutOnText[];
bool DecoAction_PutItAway_Ornament(void);
extern const txt_cmd_s WhichSidePutAwayText[];
bool DecoAction_AskWhichSide(const txt_cmd_s* hl);
u8_ptr_pair_s QueryWhichSide(void);
extern const struct MenuHeader DecoSideMenuHeader;
extern const txt_cmd_s PutAwayTheDecoText[];
extern const txt_cmd_s NothingToPutAwayText[];
extern const txt_cmd_s SetUpTheDecoText[];
extern const txt_cmd_s PutAwayAndSetUpText[];
extern const txt_cmd_s AlreadySetUpText[];
void GetDecorationName_c_de(void);
uint8_t DecorationFlagAction_c(uint8_t c, uint8_t b);
uint8_t* GetDecorationName_c(uint8_t c);
void SetSpecificDecorationFlag(void);
void SetSpecificDecorationFlag_Conv(uint8_t c);
uint8_t GetDecorationID(uint8_t c);
void SetAllDecorationFlags(void);
void DescribeDecoration(void);
Script_fn_t DescribeDecoration_Conv(uint8_t b);
void DecorationDesc_Poster(void);
Script_fn_t DecorationDesc_Poster_Conv(uint8_t poster);
bool DecorationDesc_TownMapPoster(script_s*);
bool DecorationDesc_PikachuPoster(script_s*);
bool DecorationDesc_ClefairyPoster(script_s*);
bool DecorationDesc_JigglypuffPoster(script_s*);
bool DecorationDesc_NullPoster(script_s*);
void DecorationDesc_LeftOrnament(void);
Script_fn_t DecorationDesc_LeftOrnament_Conv(void);
void DecorationDesc_RightOrnament(void);
Script_fn_t DecorationDesc_RightOrnament_Conv(void);
void DecorationDesc_Console(void);
Script_fn_t DecorationDesc_Console_Conv(void);
void DecorationDesc_OrnamentOrConsole(void);
Script_fn_t DecorationDesc_OrnamentOrConsole_Conv(uint8_t c);
void DecorationDesc_GiantOrnament(void);
Script_fn_t DecorationDesc_GiantOrnament_Conv(void);
void ToggleMaptileDecorations(void);
void SetPosterVisibility(void);
void SetDecorationTile(void);
void SetDecorationTile_Conv(uint8_t a, uint8_t d, uint8_t e);
void ToggleDecorationsVisibility(void);
void ToggleDecorationVisibility(void);
void ToggleDecorationVisibility_Conv(uint8_t* hl, uint16_t de, uint8_t a);
void v_GetDecorationSprite(void);
uint8_t v_GetDecorationSprite_Conv(uint8_t a);
void PadCoords_de(void);
uint8_t* PadCoords_de_Conv(uint8_t d, uint8_t e);
//#include "data/decorations/attributes.h"
//#include "data/decorations/names.h"
//#include "data/decorations/decorations.h"
