void OverworldLoop(void);
void DisableEvents(void);
void EnableEvents(void);
void CheckBit5_ScriptFlags2(void);
void DisableWarpsConnxns(void);
void DisableCoordEvents(void);
void DisableStepCount(void);
void DisableWildEncounters(void);
void EnableWarpsConnxns(void);
void EnableCoordEvents(void);
void EnableStepCount(void);
// void EnableWildEncounters(void);
// bool CheckWarpConnxnScriptFlag(void);
// bool CheckCoordEventScriptFlag(void);
// bool CheckStepCountScriptFlag(void);
// bool CheckWildEncountersScriptFlag(void);
// void StartMap(void);
// void EnterMap(void);
void UnusedWait30Frames(void);
// void HandleMap(void);
// void MapEvents(void);
void MaxOverworldDelay(void);
// void ResetOverworldDelay(void);
// void NextOverworldFrame(void);
// void HandleMapTimeAndJoypad(void);
// void HandleMapObjects(void);
// void HandleMapBackground(void);
// void CheckPlayerState(void);
// void v_CheckObjectEnteringVisibleRange(void);
// bool PlayerEvents(void);
// u8_flag_s CheckTrainerBattle_GetPlayerEvent(void);
// u8_flag_s CheckTileEvent(void);
// bool CheckWildEncounterCooldown(void);
// void SetUpFiveStepWildEncounterCooldown(void);
void SetMinTwoStepWildEncounterCooldown(void);
void Dummy_CheckScriptFlags2Bit5(void);
// u8_flag_s RunSceneScript(void);
// u8_flag_s CheckTimeEvents(void);
// u8_flag_s OWPlayerInput(void);
// u8_flag_s CheckAPressOW(void);
// void PlayTalkObject(void);
// u8_flag_s TryObjectEvent(void);
// void ObjectEventTypeArray(void);
// u8_flag_s TryBGEvent(void);
// u8_flag_s BGEventJumptable(uint8_t a);
// bool CheckBGEventFlag(void);
// u8_flag_s PlayerMovement(void);
// void PlayerMovementPointers(void);
// u8_flag_s CheckMenuOW(void);
// bool StartMenuScript(script_s* s);
// bool SelectMenuScript(script_s* s);
// bool StartMenuCallback(script_s* s);
// bool SelectMenuCallback(script_s* s);
// u8_flag_s CountStep(void);
// bool DoRepelStep(void);
// void DoPlayerEvent(void);
extern const Script_fn_t PlayerEventScriptPointers[];
// bool InvalidEventScript(script_s* s);
void UnusedPlayerEventScript(void);
// bool HatchEggScript(script_s* s);
// bool WarpToNewMapScript(script_s* s);
// bool FallIntoMapScript(script_s* s);
// bool LandAfterPitfallScript(script_s* s);
// bool EdgeWarpScript(script_s* s);
// bool ChangeDirectionScript(script_s* s);
void WarpToSpawnPoint(void);
// u8_flag_s RunMemScript(void);
bool LoadScriptBDE(Script_fn_t de);
// u8_flag_s TryTileCollisionEvent(void);
// u8_flag_s RandomEncounter(void);
// bool WildBattleScript(script_s* s);
bool CanUseSweetScent(void);
// bool v_TryWildEncounter_BugContest(void);
void ChooseWildEncounter_BugContest(void);
bool TryWildEncounter_BugContest(void);
// bool DoBikeStep(void);
//#include "constants.h"
#include "scripting.h"
//#include "data/wild/bug_contest_mons.h"
#include "cmd_queue.h"
