void RunMapSetupScript(void);
void ReadMapSetupScript(void);
void EnableTextAcceleration(void);
void ActivateMapAnims(void);
void SuspendMapAnims(void);
void LoadMapObjects(void);
void MapSetup_DummyFunction(void);
void ResetPlayerObjectAction(void);
void SkipUpdateMapSprites(void);
void CheckUpdatePlayerSprite(void);
void FadeOutMapMusic(void);
void ApplyMapPalettes(void);
void FadeMapMusicAndPalettes(void);
void ForceMapMusic(void);
//#include "data/maps/setup_scripts.h"
//#include "data/maps/setup_script_pointers.h"
