void CanObjectMoveInDirection(void);
bool CanObjectMoveInDirection_Conv(struct Object* bc);
void WillObjectBumpIntoWater(void);
bool WillObjectBumpIntoWater_Conv(struct Object* bc);
void WillObjectBumpIntoLand(void);
bool WillObjectBumpIntoLand_Conv(struct Object* bc);
void WillObjectBumpIntoTile(void);
bool WillObjectBumpIntoTile_Conv(struct Object* bc);
void CanObjectLeaveTile(void);
bool CanObjectLeaveTile_Conv(struct Object* bc);
void GetSideWallDirectionMask(void);
u8_flag_s GetSideWallDirectionMask_Conv(uint8_t a);
void WillObjectRemainOnWater(void);
bool WillObjectRemainOnWater_Conv(struct Object* bc, uint8_t d, uint8_t e);
void CheckFacingObject(void);
struct Object* CheckFacingObject_Conv(void);
void WillObjectBumpIntoSomeoneElse(void);
bool WillObjectBumpIntoSomeoneElse_Conv(struct Object* bc);
void IsObjectFacingSomeoneElse(void);
void IsNPCAtCoord(void);
struct Object* IsNPCAtCoord_Conv(uint8_t d, uint8_t e);
void HasObjectReachedMovementLimit(void);
bool HasObjectReachedMovementLimit_Conv(struct Object* bc);
void IsObjectMovingOffEdgeOfScreen(void);
bool IsObjectMovingOffEdgeOfScreen_Conv(struct Object* bc);
void IsNPCAtPlayerCoord(void);
bool WillObjectIntersectBigObject_Conv(struct Object* bc, uint8_t d, uint8_t e);
void WillObjectIntersectBigObject(void);
