bool CanObjectMoveInDirection(struct Object* bc);
bool WillObjectBumpIntoWater(struct Object* bc);
// bool WillObjectBumpIntoLand(struct Object* bc);
// bool WillObjectBumpIntoTile(struct Object* bc);
// bool CanObjectLeaveTile(struct Object* bc);
// u8_flag_s GetSideWallDirectionMask(uint8_t a);
// bool WillObjectRemainOnWater(struct Object* bc, uint8_t d, uint8_t e);
struct Object* CheckFacingObject(void);
// bool WillObjectBumpIntoSomeoneElse(struct Object* bc);
void IsObjectFacingSomeoneElse(void);
struct Object* IsNPCAtCoord(uint8_t d, uint8_t e);
// bool HasObjectReachedMovementLimit(struct Object* bc);
// bool IsObjectMovingOffEdgeOfScreen(struct Object* bc);
void IsNPCAtPlayerCoord(void);
// bool WillObjectIntersectBigObject(struct Object* bc, uint8_t d, uint8_t e);
