void GetEmote2bpp(void);
void v_UpdatePlayerSprite(void);
void v_RefreshSprites(void);
void v_ClearSprites(void);
void RefreshSprites(void);
void GetPlayerSprite(void);
void AddMapSprites(void);
void AddIndoorSprites(void);
void AddOutdoorSprites(void);
void LoadUsedSpritesGFX(void);
void LoadMiscTiles(void);
void SafeGetSprite(void);
void GetSprite(void);
void GetMonSprite(void);
void v_DoesSpriteHaveFacings(void);
bool v_DoesSpriteHaveFacings_Conv(uint8_t a);
void v_GetSpritePalette(void);
void LoadAndSortSprites(void);
void AddSpriteGFX(void);
void LoadSpriteGFX(void);
void SortUsedSprites(void);
void ArrangeUsedSprites(void);
void GetSpriteLength(void);
void GetUsedSprites(void);
void GetUsedSprite(void);
void LoadEmote(void);
//#include "data/sprites/player_sprites.h"
//#include "data/sprites/emotes.h"
//#include "data/sprites/sprite_mons.h"
//#include "data/maps/outdoor_sprites.h"
//#include "data/sprites/sprites.h"
