void BlankScreen(void);
void SpawnPlayer(void);
// void PlayerObjectTemplate(void);
extern const struct ObjEvent PlayerObjectTemplate;
void CopyDECoordsToMapObject(uint8_t d, uint8_t e, uint8_t b);
// void PlayerSpawn_ConvertCoords(uint8_t b);
void WriteObjectXY(uint8_t b);
void RefreshPlayerCoords(void);
uint8_t CopyObjectStruct(struct MapObject* bc, uint8_t a);
// void CopyMapObjectToObjectStruct(struct Object* de, struct MapObject* bc, uint8_t mapObjIdx, uint8_t objIdx);
void InitializeVisibleSprites(void);
void CheckObjectEnteringVisibleRange(void);
void CopyTempObjectToObjectStruct(struct Object* de);
void TrainerWalkToPlayer(void);
void SurfStartStep(void);
void FollowNotExact(uint8_t c, uint8_t b);
uint8_t GetRelativeFacing(uint8_t e, uint8_t d);
bool QueueFollowerFirstStep(void);
