void EnableScriptMode(void);
void ScriptEvents(void);
void EndScript(void);
void WaitScript(void);
void WaitScriptMovement(void);
void RunScriptCommand(void);
void ScriptCommandTable(void);
void StartScript(void);
void CheckScript(void);
bool CheckScript_Conv(void);
void StopScript(void);
void StopScript_Conv(void);
void Script_callasm(void);
void Script_special(void);
void Script_memcallasm(void);
void Script_jumptextfaceplayer(void);
void Script_jumptextfaceplayer_Conv(script_s* s, const struct TextCmd* text);
void Script_jumptext(void);
void Script_jumptext_Conv(script_s* s, const struct TextCmd* text);
bool JumpTextFacePlayerScript(script_s* s);
bool JumpTextScript(script_s* s);
void Script_farjumptext(void);
void Script_writetext(void);
void Script_writetext_Conv(script_s* s, const struct TextCmd* text);
void Script_farwritetext(void);
void Script_repeattext(void);
void Script_repeattext_Conv(script_s* s, uint16_t hl);
void Script_waitbutton(void);
void Script_waitbutton_Conv(script_s* s);
void Script_promptbutton(void);
void Script_yesorno(void);
void Script_loadmenu(void);
void Script_closewindow(void);
void Script_pokepic(void);
void Script_closepokepic(void);
void Script_verticalmenu(void);
void Script__2dmenu(void);
void Script_battletowertext(void);
void Script_verbosegiveitem(void);
void GiveItemScript_DummyFunction(void);
void GiveItemScript(void);
void Script_verbosegiveitemvar(void);
void Script_itemnotify(void);
void Script_pocketisfull(void);
void Script_specialsound(void);
void GetPocketName(void);
void CurItemName(void);
void PutItemInPocketText(void);
void PocketIsFullText(void);
void Script_pokemart(void);
void Script_elevator(void);
void Script_trade(void);
void Script_phonecall(void);
void Script_hangup(void);
void Script_askforphonenumber(void);
void Script_describedecoration(void);
void Script_fruittree(void);
void Script_swarm(void);
void Script_trainertext(void);
void Script_scripttalkafter(void);
void Script_trainerflagaction(void);
void Script_winlosstext(void);
void Script_endifjustbattled(void);
void Script_checkjustbattled(void);
void Script_encountermusic(void);
void Script_playmapmusic(void);
void Script_playmusic(void);
void Script_musicfadeout(void);
void Script_playsound(void);
void Script_waitsfx(void);
void Script_warpsound(void);
void Script_cry(void);
void GetScriptObject(void);
uint8_t GetScriptObject_Conv(uint8_t a);
void Script_setlasttalked(void);
void Script_setlasttalked_Conv(script_s* s, uint8_t a);
void Script_applymovement(void);
void Script_applymovement_Conv(script_s* s, uint8_t a, const uint8_t* hl);
void ApplyMovement(void);
void ApplyMovement_Conv(uint8_t c, const uint8_t* hl);
void UnfreezeFollowerObject(void);
void Script_applymovementlasttalked(void);
void Script_applymovementlasttalked_Conv(script_s* s, const uint8_t* hl);
void Script_faceplayer(void);
void Script_faceplayer_Conv(script_s* s);
void Script_faceobject(void);
void Script_turnobject(void);
void ApplyObjectFacing(void);
bool ApplyObjectFacing_Conv(uint8_t d, uint8_t e);
void Script_variablesprite(void);
void Script_appear(void);
void Script_disappear(void);
void ApplyEventActionAppearDisappear(void);
void Script_follow(void);
void Script_stopfollow(void);
void Script_moveobject(void);
void Script_writeobjectxy(void);
void Script_follownotexact(void);
void Script_loademote(void);
void Script_showemote(void);
void ShowEmoteScript(void);
void Script_earthquake(void);
extern const uint8_t EarthquakeMovement[4];
void Script_loadpikachudata(void);
void Script_randomwildmon(void);
void Script_randomwildmon_Conv(script_s* s);
void Script_loadtemptrainer(void);
void Script_loadwildmon(void);
void Script_loadtrainer(void);
void Script_startbattle(void);
void Script_startbattle_Conv(script_s* s);
void Script_catchtutorial(void);
void Script_reloadmapafterbattle(void);
void Script_reloadmap(void);
void Script_scall(void);
void Script_farscall(void);
void Script_memcall(void);
void ScriptCall(void);
void CallCallback(void);
void Script_sjump(void);
void Script_farsjump(void);
void Script_memjump(void);
void Script_iffalse(void);
void Script_iftrue(void);
void Script_ifequal(void);
void Script_ifnotequal(void);
void Script_ifgreater(void);
void Script_ifless(void);
void Script_jumpstd(void);
void Script_callstd(void);
void StdScript(void);
void SkipTwoScriptBytes(void);
void ScriptJump(void);
void Script_sdefer(void);
void Script_checkscene(void);
void Script_checkmapscene(void);
void Script_setscene(void);
void Script_setmapscene(void);
void DoScene(void);
void Script_readmem(void);
void Script_writemem(void);
void Script_loadmem(void);
void Script_setval(void);
void Script_addval(void);
void Script_random(void);
void Script_readvar(void);
void Script_writevar(void);
void Script_loadvar(void);
void GetVarAction(void);
void Script_checkver(void);
void Script_getmonname(void);
void GetStringBuffer(void);
void GetStringBuffer_Conv(uint8_t a, const uint8_t* de);
void CopyConvertedText(void);
void CopyConvertedText_Conv(uint8_t a, const uint8_t* de);
void Script_getitemname(void);
void Script_getcurlandmarkname(void);
void Script_getcurlandmarkname_Conv(script_s* s, uint8_t b);
void ConvertLandmarkToText(void);
void ConvertLandmarkToText_Conv(uint8_t a, uint8_t b);
void Script_getlandmarkname(void);
void Script_gettrainername(void);
void Script_getname(void);
void ContinueToGetName(void);
void Script_gettrainerclassname(void);
void Script_getmoney(void);
void Script_getcoins(void);
void Script_getnum(void);
void ResetStringBuffer1(void);
void ResetStringBuffer1_Conv(void);
void Script_getstring(void);
void Script_givepokemail(void);
void Script_checkpokemail(void);
void Script_giveitem(void);
void Script_takeitem(void);
void Script_checkitem(void);
void Script_givemoney(void);
void Script_takemoney(void);
void Script_checkmoney(void);
void CompareMoneyAction(void);
void GetMoneyAccount(void);
void LoadMoneyAmountToMem(void);
void Script_givecoins(void);
void Script_takecoins(void);
void Script_checkcoins(void);
void LoadCoinAmountToMem(void);
void Script_checktime(void);
void Script_checkpoke(void);
void Script_addcellnum(void);
void Script_delcellnum(void);
void Script_checkcellnum(void);
void Script_specialphonecall(void);
void Script_checkphonecall(void);
void Script_givepoke(void);
void Script_giveegg(void);
void Script_setevent(void);
void Script_clearevent(void);
void Script_checkevent(void);
void Script_setflag(void);
void Script_setflag_Conv(script_s* s, uint16_t flag);
void Script_clearflag(void);
void Script_clearflag_Conv(script_s* s, uint16_t flag);
void Script_checkflag(void);
void Script_checkflag_Conv(script_s* s, uint16_t flag);
void v_EngineFlagAction(void);
bool v_EngineFlagAction_Conv(uint16_t de, uint8_t b);
void Script_wildoff(void);
void Script_wildon(void);
void Script_xycompare(void);
void Script_warpfacing(void);
void Script_warp(void);
void Script_warpmod(void);
void Script_blackoutmod(void);
void Script_dontrestartmapmusic(void);
void Script_writecmdqueue(void);
void Script_delcmdqueue(void);
void Script_changemapblocks(void);
void Script_changeblock(void);
void Script_reloadmappart(void);
void Script_warpcheck(void);
void Script_enableevents(void);
void Script_newloadmap(void);
void Script_reloadend(void);
void Script_opentext(void);
void Script_opentext_Conv(script_s* s);
void Script_refreshscreen(void);
void Script_writeunusedbyte(void);
void UnusedClosetextScript(void);
void Script_closetext(void);
void Script_closetext_Conv(script_s* s);
void Script_autoinput(void);
void Script_pause(void);
void Script_deactivatefacing(void);
void Script_stopandsjump(void);
void Script_end(void);
void Script_endcallback(void);
void ExitScriptSubroutine(void);
void Script_endall(void);
void Script_halloffame(void);
void Script_credits(void);
void ReturnFromCredits(void);
void Script_wait(void);
void Script_checksave(void);
void Script_checkver_duplicate(void);
//#include "data/items/pocket_names.h"
