bool SendScreenToPrinter(void);
void Printer_CleanUpAfterSend(void);
void Printer_PrepareTilemapForPrint(uint8_t margins);
void Printer_ExitPrinter(void);
void PrintDexEntry(void);
void PrintPCBox(void);
void Printer_ResetRegistersAndStartDataSend(void);
void PrintUnownStamp(void);
void PrintMailAndExit(void);
void PrintMail(void);
void PrintPartymon(void);
void v_PrintDiploma(void);
bool CheckCancelPrint(void);
void Printer_CopyTilemapToBuffer(void);
void Printer_CopyBufferToTilemap(void);
void Printer_ResetJoypadRegisters(void);
void Printer_PlayMusic(void);
void Printer_RestartMapMusic(void);
void CheckPrinterStatus(void);
void PlacePrinterStatusString(void);
void PlacePrinterStatusStringBorderless(void);
extern const char String_PressBToCancel[];
extern const char* PrinterStatusStringPointers[];
void PrintPCBox_Page1(void);
void PrintPCBox_Page2(void);
void PrintPCBox_Page3(void);
void PrintPCBox_Page4(void);
void Printer_PrintBoxListSegment(void);
void Printer_GetMonGender(void);
void Printer_GetBoxMonSpecies(void);
void Printer_PlaceTopBorder(void);
void Printer_PlaceSideBorders(void);
void Printer_PlaceBottomBorders(void);
void Printer_PlaceEmptyBoxSlotString(void);
