extern struct Audio gAudio;

void v_InitSound(void);
void MusicFadeRestart(void);
void MusicOn(void);
void MusicOff(void);
void v_UpdateSound(void);
void UpdateChannels(void);
void UpdateChannels_Channel1_LowHealth(void);
void UpdateChannels_Channel1(void);
void UpdateChannels_Channel2(void);
void UpdateChannels_Channel3(void);
void UpdateChannels_load_wave_pattern(uint8_t);
void UpdateChannels_Channel4(void);
int v_CheckSFX(void);
void PlayDanger(void);
void FadeMusic(void);
void LoadNote(void);
void HandleTrackVibrato(void);
void ApplyPitchSlide(void);
void ApplyPitchSlide_finished_pitch_slide(void);
void ApplyPitchSlide_continue_pitch_slide(void);
void HandleNoise(void);
void ReadNoiseSample(void);
void ParseMusic(void);
void RestoreVolume(void);
void ParseSFXOrCry(void);
void GetNoiseSample(void);
void ParseMusicCommand(void);
void MusicCommands(void);
void MusicNone(void);
void Music_Ret(void);
void Music_Call(void);
void Music_Jump(void);
void Music_Loop(void);
void Music_SetCondition(void);
void Music_JumpIf(void);
void MusicEE(void);
void MusicE2(void);
void Music_Vibrato(void);
void Music_PitchSlide(void);
void Music_PitchOffset(void);
void MusicE7(void);
void Music_DutyCyclePattern(void);
void MusicE8(void);
void Music_ToggleSFX(void);
void Music_ToggleNoise(void);
void Music_SFXToggleNoise(void);
void Music_NoteType(void);
void Music_PitchSweep(void);
void Music_DutyCycle(void);
void Music_VolumeEnvelope(void);
void Music_Tempo(void);
void Music_Octave(void);
void Music_Transpose(void);
void Music_StereoPanning(void);
void Music_ForceStereoPanning(void);
void Music_Volume(void);
void Music_TempoRelative(void);
void Music_SFXPriorityOn(void);
void Music_SFXPriorityOff(void);
void Music_RestartChannel(void);
void Music_NewSong(void);
uint8_t GetMusicByte(void);
uint16_t GetFrequency(uint8_t, uint8_t);
void SetNoteDuration(uint8_t);
void SetNoteDuration_Multiply(void);
void SetGlobalTempo(uint16_t);
void Tempo(void);
void StartChannel(void);
void SetLRTracks(void);
void v_PlayMusic(uint16_t);
void v_PlayCry(uint16_t);
void v_PlaySFX(uint16_t);
void PlayStereoSFX(uint16_t);
uint16_t LoadChannel(uint16_t);
void ChannelInit(uint8_t);
uint8_t LoadMusicByte(uint16_t);
const uint8_t* GetLRTracks(void);
// void MonoTracks(void);
// void StereoTracks(void);
// void ChannelPointers(void);
void ClearChannels(void);
void ClearChannel(uint16_t);
void PlayTrainerEncounterMusic(uint8_t e);
//#include "audio/notes.h"
//#include "audio/wave_samples.h"
//#include "audio/drumkits.h"
