// See song sections in audio.asm.
#include "music_1.h"
#include "music_2.h"
#include "music_3.h"
#include "music_4.h"

#define music_pointer(_bank, _name) {_bank, o##_name}

const struct BankAddr Music[] = {
// entries correspond to MUSIC_* constants
	// table_width 3, Music
	music_pointer(AUDIO_BANK_MUSIC_1, Music_Nothing),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_TitleScreen), // bank_addr(Music_TitleScreen),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route1), // bank_addr(Music_Route1),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route3), // bank_addr(Music_Route3),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route12), // bank_addr(Music_Route12),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_MagnetTrain), // bank_addr(Music_MagnetTrain),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_KantoGymBattle), // bank_addr(Music_KantoGymBattle),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_KantoTrainerBattle), // bank_addr(Music_KantoTrainerBattle),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_KantoWildBattle), // bank_addr(Music_KantoWildBattle),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_PokemonCenter), // bank_addr(Music_PokemonCenter),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_LookHiker), // bank_addr(Music_LookHiker),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LookLass), // bank_addr(Music_LookLass),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LookOfficer), // bank_addr(Music_LookOfficer),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_HealPokemon), // bank_addr(Music_HealPokemon),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LavenderTown), // bank_addr(Music_LavenderTown),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route2), // bank_addr(Music_Route2),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_MtMoon), // bank_addr(Music_MtMoon),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_ShowMeAround), // bank_addr(Music_ShowMeAround),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_GameCorner), // bank_addr(Music_GameCorner),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Bicycle), // bank_addr(Music_Bicycle),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_HallOfFame), // bank_addr(Music_HallOfFame),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_ViridianCity), // bank_addr(Music_ViridianCity),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_CeladonCity), // bank_addr(Music_CeladonCity),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_TrainerVictory), // bank_addr(Music_TrainerVictory),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_WildPokemonVictory), // bank_addr(Music_WildPokemonVictory),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_GymLeaderVictory), // bank_addr(Music_GymLeaderVictory),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_MtMoonSquare), // bank_addr(Music_MtMoonSquare),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_Gym), // bank_addr(Music_Gym),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_PalletTown), // bank_addr(Music_PalletTown),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_ProfOaksPokemonTalk), // bank_addr(Music_ProfOaksPokemonTalk),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_ProfOak), // bank_addr(Music_ProfOak),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_LookRival), // bank_addr(Music_LookRival),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_AfterTheRivalFight), // bank_addr(Music_AfterTheRivalFight),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_Surf), // bank_addr(Music_Surf),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_Evolution), // bank_addr(Music_Evolution),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_NationalPark), // bank_addr(Music_NationalPark),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_Credits), // bank_addr(Music_Credits),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_AzaleaTown), // bank_addr(Music_AzaleaTown),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_CherrygroveCity), // bank_addr(Music_CherrygroveCity),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_LookKimonoGirl), // bank_addr(Music_LookKimonoGirl),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_UnionCave), // bank_addr(Music_UnionCave),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_JohtoWildBattle), // bank_addr(Music_JohtoWildBattle),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_JohtoTrainerBattle), // bank_addr(Music_JohtoTrainerBattle),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route30), // bank_addr(Music_Route30),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_EcruteakCity), // bank_addr(Music_EcruteakCity),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_VioletCity), // bank_addr(Music_VioletCity),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_JohtoGymBattle), // bank_addr(Music_JohtoGymBattle),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_ChampionBattle), // bank_addr(Music_ChampionBattle),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_RivalBattle), // bank_addr(Music_RivalBattle),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_RocketBattle), // bank_addr(Music_RocketBattle),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_ElmsLab), // bank_addr(Music_ElmsLab),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_DarkCave), // bank_addr(Music_DarkCave),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_Route29), // bank_addr(Music_Route29),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_Route36), // bank_addr(Music_Route36),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_SSAqua), // bank_addr(Music_SSAqua),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_LookYoungster), // bank_addr(Music_LookYoungster),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LookBeauty), // bank_addr(Music_LookBeauty),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_LookRocket), // bank_addr(Music_LookRocket),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_LookPokemaniac), // bank_addr(Music_LookPokemaniac),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LookSage), // bank_addr(Music_LookSage),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_NewBarkTown), // bank_addr(Music_NewBarkTown),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_GoldenrodCity), // bank_addr(Music_GoldenrodCity),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_VermilionCity), // bank_addr(Music_VermilionCity),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_PokemonChannel), // bank_addr(Music_PokemonChannel),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_PokeFluteChannel), // bank_addr(Music_PokeFluteChannel),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_TinTower), // bank_addr(Music_TinTower),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_SproutTower), // bank_addr(Music_SproutTower),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_BurnedTower), // bank_addr(Music_BurnedTower),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Lighthouse), // bank_addr(Music_Lighthouse),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LakeOfRage), // bank_addr(Music_LakeOfRage),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_IndigoPlateau), // bank_addr(Music_IndigoPlateau),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route37), // bank_addr(Music_Route37),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_RocketHideout), // bank_addr(Music_RocketHideout),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_DragonsDen), // bank_addr(Music_DragonsDen),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_JohtoWildBattleNight), // bank_addr(Music_JohtoWildBattleNight),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_RuinsOfAlphRadio), // bank_addr(Music_RuinsOfAlphRadio),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_SuccessfulCapture), // bank_addr(Music_SuccessfulCapture),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_Route26), // bank_addr(Music_Route26),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_Mom), // bank_addr(Music_Mom),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_VictoryRoad), // bank_addr(Music_VictoryRoad),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_PokemonLullaby), // bank_addr(Music_PokemonLullaby),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_PokemonMarch), // bank_addr(Music_PokemonMarch),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_GoldSilverOpening), // bank_addr(Music_GoldSilverOpening),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_GoldSilverOpening2), // bank_addr(Music_GoldSilverOpening2),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_MainMenu), // bank_addr(Music_MainMenu),
	music_pointer(AUDIO_BANK_MUSIC_1, Music_RuinsOfAlphInterior), // bank_addr(Music_RuinsOfAlphInterior),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_RocketTheme), // bank_addr(Music_RocketTheme),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_DancingHall), // bank_addr(Music_DancingHall),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_ContestResults), // bank_addr(Music_ContestResults),
	music_pointer(AUDIO_BANK_MUSIC_4, Music_BugCatchingContest), // bank_addr(Music_BugCatchingContest),
	music_pointer(AUDIO_BANK_MUSIC_2, Music_LakeOfRageRocketRadio), // bank_addr(Music_LakeOfRageRocketRadio),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_Printer), // bank_addr(Music_Printer),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_PostCredits), // bank_addr(Music_PostCredits),
// new to Crystal
	music_pointer(AUDIO_BANK_MUSIC_3, Music_Clair), // bank_addr(Music_Clair),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_MobileAdapterMenu), // bank_addr(Music_MobileAdapterMenu),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_MobileAdapter), // bank_addr(Music_MobileAdapter),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_BuenasPassword), // bank_addr(Music_BuenasPassword),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_LookMysticalMan), // bank_addr(Music_LookMysticalMan),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_CrystalOpening), // bank_addr(Music_CrystalOpening),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_BattleTowerTheme), // bank_addr(Music_BattleTowerTheme),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_SuicuneBattle), // bank_addr(Music_SuicuneBattle),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_BattleTowerLobby), // bank_addr(Music_BattleTowerLobby),
	music_pointer(AUDIO_BANK_MUSIC_3, Music_MobileCenter), // bank_addr(Music_MobileCenter),
};
static_assert(lengthof(Music) == NUM_MUSIC_SONGS, "");
