void DayCareMan(void);
void DayCareLady(void);
bool DayCareLadyIntroText(uint8_t* hl, uint8_t a);
bool DayCareManIntroText(uint8_t* hl, uint8_t a);
u8_flag_s DayCareAskDepositPokemon(void);
void DayCare_DepositPokemonText(void);
u8_flag_s DayCare_AskWithdrawBreedMon(void);
void DayCare_GetBackMonForMoney(void);
void GetPriceToRetrieveBreedmon(const uint8_t* hl, u8_pair_s lvlGrowth);
void PrintDayCareText(uint8_t a);
void DayCareManOutside(void);
bool DayCare_GiveEgg(void);
void DayCare_GetCurrentPartyMember(void);
void DayCare_InitBreeding(void);
