void BankOfMom(void);
void DSTChecks(void);
void Mom_SetUpWithdrawMenu(void);
void Mom_SetUpDepositMenu(void);
void Mom_ContinueMenuSetup(const char*);
void Mom_Wait10Frames(void);
bool Mom_WithdrawDepositMenuJoypad(void);
extern const txt_cmd_s MomLeavingText1[];
extern const txt_cmd_s MomLeavingText2[];
extern const txt_cmd_s MomLeavingText3[];
extern const txt_cmd_s MomIsThisAboutYourMoneyText[];
extern const txt_cmd_s MomBankWhatDoYouWantToDoText[];
extern const txt_cmd_s MomStoreMoneyText[];
extern const txt_cmd_s MomTakeMoneyText[];
extern const txt_cmd_s MomSaveMoneyText[];
extern const txt_cmd_s MomHaventSavedThatMuchText[];
extern const txt_cmd_s MomNotEnoughRoomInWalletText[];
extern const txt_cmd_s MomInsufficientFundsInWalletText[];
extern const txt_cmd_s MomNotEnoughRoomInBankText[];
extern const txt_cmd_s MomStartSavingMoneyText[];
extern const txt_cmd_s MomStoredMoneyText[];
extern const txt_cmd_s MomTakenMoneyText[];
extern const txt_cmd_s MomJustDoWhatYouCanText[];
extern const char Mom_SavedString[];
extern const char Mon_WithdrawString[];
extern const char Mom_DepositString[];
extern const char Mom_HeldString[];
// void BankOfMom_MenuHeader(void);
