void GiveMoney(void);
bool GiveMoney_Conv(uint8_t* de, const uint8_t* bc);
// void MaxMoney(void);
void TakeMoney(void);
bool TakeMoney_Conv(uint8_t* de, const uint8_t* bc);
void CompareMoney(void);
u8_flag_s CompareMoney_Conv(const uint8_t* bc, const uint8_t* de);
void CompareFunds(void);
u8_flag_s CompareFunds_Conv(const uint8_t* bc, const uint8_t* de, uint8_t a);
void SubtractMoney(void);
bool SubtractMoney_Conv(uint8_t* de, const uint8_t* bc);
void SubtractFunds(void);
bool SubtractFunds_Conv(uint8_t* de, const uint8_t* bc, uint8_t a);
void AddMoney(void);
void AddMoney_Conv(uint8_t* de, const uint8_t* bc);
void AddFunds(void);
void AddFunds_Conv(uint8_t* de, const uint8_t* bc, uint8_t a);
void GiveCoins(void);
bool GiveCoins_Conv(const uint8_t* bc);
void TakeCoins(void);
bool TakeCoins_Conv(const uint8_t* bc);
void CheckCoins(void);
u8_flag_s CheckCoins_Conv(const uint8_t* bc);
