void v_NameRater(void);
// bool CheckIfMonIsYourOT(uint8_t partyMon);
// bool IsNewNameEmpty(void);
// bool CompareNewToOld(uint8_t curPartyMon);
// uint8_t GetNicknamenameLength(const uint8_t* hl);
// void NameRaterHelloText(void);
// void NameRaterWhichMonText(void);
// void NameRaterBetterNameText(void);
// void NameRaterWhatNameText(void);
// void NameRaterFinishedText(void);
// void NameRaterComeAgainText(void);
// void NameRaterPerfectNameText(void);
// void NameRaterEggText(void);
// void NameRaterSameNameText(void);
// void NameRaterNamedText(void);
