void FieldMoveJumptableReset(void);
// void FieldMoveJumptable(void);
void GetPartyNickname(void);
void CheckEngineFlag(void);
bool CheckEngineFlag_Conv(uint16_t de);
void CheckBadge(void);
bool CheckBadge_Conv(uint16_t de);
void CheckPartyMove(void);
bool CheckPartyMove_Conv(move_t d);
void FieldMoveFailed(void);
void CutFunction(void);
extern const struct TextCmd UseCutText[];
extern const struct TextCmd CutNothingText[];
void CheckMapForSomethingToCut(void);
bool CheckMapForSomethingToCut_Conv(void);
bool Script_CutFromMenu(script_s* s);
bool Script_Cut(script_s* s);
void CutDownTreeOrGrass(void);
void CheckOverworldTileArrays(void);
void FlashFunction(void);
void UseFlash(void);
bool Script_UseFlash(script_s* s);
void UseFlashTextScript(struct TextCmdState* state);
void SurfFunction(void);
bool SurfFromMenuScript(script_s* s);
bool UsedSurfScript(script_s* s);
extern const struct TextCmd UsedSurfText[];
extern const struct TextCmd CantSurfText[];
extern const struct TextCmd AlreadySurfingText[];
void GetSurfType(void);
uint8_t GetSurfType_Conv(void);
void CheckDirection(void);
bool CheckDirection_Conv(void);
void TrySurfOW(void);
bool TrySurfOW_Conv(void);
bool AskSurfScript(script_s* s);
extern const struct TextCmd AskSurfText[];
void FlyFunction(void);
void WaterfallFunction(void);
void CheckMapCanWaterfall(void);
bool CheckMapCanWaterfall_Conv(void);
void Script_WaterfallFromMenu(void);
void Script_UsedWaterfall(void);
void TryWaterfallOW(void);
bool TryWaterfallOW_Conv(void);
void Script_CantDoWaterfall(void);
void Script_AskWaterfall(void);
void EscapeRopeFunction(void);
void DigFunction(void);
void EscapeRopeOrDig(void);
void TeleportFunction(void);
void StrengthFunction(void);
void SetStrengthFlag(void);
bool Script_StrengthFromMenu(script_s* s);
bool Script_UsedStrength(script_s* s);
void AskStrengthScript(void);
void AskStrengthText(void);
void BouldersMoveText(void);
void BouldersMayMoveText(void);
void TryStrengthOW(void);
void WhirlpoolFunction(void);
extern const struct TextCmd UseWhirlpoolText[];
void TryWhirlpoolMenu(void);
bool Script_WhirlpoolFromMenu(script_s*);
bool Script_UsedWhirlpool(script_s*);
void DisappearWhirlpool(void);
void TryWhirlpoolOW(void);
bool TryWhirlpoolOW_Conv(void);
bool Script_MightyWhirlpool(script_s*);
bool Script_AskWhirlpoolOW(script_s*);
extern const struct TextCmd AskWhirlpoolText[];
void HeadbuttFunction(void);
void TryHeadbuttFromMenu(void);
uint8_t TryHeadbuttFromMenu_Conv(void);
extern const struct TextCmd UseHeadbuttText[];
extern const struct TextCmd HeadbuttNothingText[];
bool HeadbuttFromMenuScript(script_s* s);
bool HeadbuttScript(script_s* s);
void TryHeadbuttOW(void);
bool TryHeadbuttOW_Conv(void);
bool AskHeadbuttScript(script_s* s);
extern const struct TextCmd AskHeadbuttText[];
void RockSmashFunction(void);
void TryRockSmashFromMenu(void);
uint8_t TryRockSmashFromMenu_Conv(void);
void GetFacingObject(void);
u8_flag_s GetFacingObject_Conv(void);
bool RockSmashFromMenuScript(script_s* s);
bool RockSmashScript(script_s* s);
extern const uint8_t MovementData_RockSmash[];
extern const struct TextCmd UseRockSmashText[];
bool AskRockSmashScript(script_s* s);
extern const struct TextCmd MaySmashText[];
extern const struct TextCmd AskRockSmashText[];
void HasRockSmash(void);
void FishFunction(void);
void Script_NotEvenANibble(void);
void Script_NotEvenANibble2(void);
void Script_NotEvenANibble_FallThrough(void);
void Script_GotABite(void);
void Fishing_CheckFacingUp(void);
void Script_FishCastRod(void);
void MovementData_CastRod(void);
void PutTheRodAway(void);
void RodBiteText(void);
void RodNothingText(void);
void UnusedNothingHereText(void);
void BikeFunction(void);
bool Script_GetOnBike(script_s*);
bool Script_GetOnBike_Register(script_s*);
void Overworld_DummyFunction(void);
bool Script_GetOffBike(script_s*);
bool FinishGettingOffBike(script_s*);
bool Script_GetOffBike_Register(script_s*);
bool Script_CantGetOffBike(script_s*);
extern const struct TextCmd GotOnBikeText[];
extern const struct TextCmd GotOffBikeText[];
void TryCutOW(void);
u8_flag_s TryCutOW_Conv(void);
bool AskCutScript(script_s* s);
extern const struct TextCmd AskCutText[];
bool CantCutScript(script_s* s);
extern const struct TextCmd CanCutText[];
//#include "data/collision/field_move_blocks.h"
