void PokeSeer(void);
void SeerAction(void);
extern void (*const SeerActions[])(void);
void SeerAction0(void);
void SeerAction1(void);
void SeerAction2(void);
void SeerAction3(void);
void SeerAction4(void);
void ReadCaughtData(void);
void GetCaughtName(void);
void GetCaughtLevel(void);
void GetCaughtTime(void);
void UnknownCaughtData(uint8_t* de);
void GetCaughtLocation(void);
void GetCaughtOT(void);
void PrintSeerText(uint8_t a);
extern const txt_cmd_s* SeerTexts[];
extern const txt_cmd_s SeerSeeAllText[];
extern const txt_cmd_s SeerCantTellAThingText[];
extern const txt_cmd_s SeerNameLocationText[];
extern const txt_cmd_s SeerTimeLevelText[];
extern const txt_cmd_s SeerTradeText[];
extern const txt_cmd_s SeerNoLocationText[];
extern const txt_cmd_s SeerEggText[];
extern const txt_cmd_s SeerDoNothingText[];
void SeerAdvice(void);
// extern const struct LevelText SeerAdviceTexts[];
extern const txt_cmd_s SeerMoreCareText[];
extern const txt_cmd_s SeerMoreConfidentText[];
extern const txt_cmd_s SeerMuchStrengthText[];
extern const txt_cmd_s SeerMightyText[];
extern const txt_cmd_s SeerImpressedText[];
uint8_t GetCaughtGender(struct BoxMon* mon);
