void PokemonCenterPC(void);
bool PC_CheckPartyForPokemon(void);
void BillsPC(void);
void PlayersPC(void);
void OaksPC(void);
void HallOfFamePC(void);
void TurnOffPC(void);
void PC_PlayBootSound(void);
void PC_PlayShutdownSound(void);
void PC_PlayChoosePCSound(void);
void PC_PlaySwapItemsSound(void);
void PC_WaitPlaySFX(void);
void PC_WaitPlaySFX_Conv(uint16_t sfx);
bool v_PlayersHousePC(void);
extern const txt_cmd_s PlayersPCTurnOnText[];
u8_flag_s v_PlayersPC(uint8_t b);
extern const struct MenuHeader PlayersPCMenuData;
void PC_DisplayTextWaitMenu(void);
void PC_DisplayTextWaitMenu_Conv(const txt_cmd_s* hl);
extern const txt_cmd_s PlayersPCAskWhatDoText[];
u8_flag_s PlayerWithdrawItemMenu(void);
u8_flag_s PlayerTossItemMenu(void);
u8_flag_s PlayerDecorationMenu(void);
u8_flag_s PlayerLogOffMenu(void);
u8_flag_s PlayerDepositItemMenu(void);
u8_flag_s PlayerMailBoxMenu(void);
bool PCItemsJoypad(void);
void PC_DisplayText(void);
void PC_DisplayText_Conv(const struct TextCmd* hl);
extern const txt_cmd_s PokecenterPCTurnOnText[];
extern const txt_cmd_s PokecenterPCWhoseText[];
extern const txt_cmd_s PokecenterBillsPCText[];
extern const txt_cmd_s PokecenterPlayersPCText[];
extern const txt_cmd_s PokecenterOaksPCText[];
extern const txt_cmd_s PokecenterPCOaksClosedText[];
