void ProfOaksPC(void);
void ProfOaksPCBoot(void);
void ProfOaksPCRating(void);
uint16_t Rate(void);
void FindOakRating(uint8_t caught, uint16_t* sfx, const txt_cmd_s** txt);
extern const txt_cmd_s OakPCText1[];
extern const txt_cmd_s OakPCText2[];
extern const txt_cmd_s OakPCText3[];
extern const txt_cmd_s OakRating01[];
extern const txt_cmd_s OakRating02[];
extern const txt_cmd_s OakRating03[];
extern const txt_cmd_s OakRating04[];
extern const txt_cmd_s OakRating05[];
extern const txt_cmd_s OakRating06[];
extern const txt_cmd_s OakRating07[];
extern const txt_cmd_s OakRating08[];
extern const txt_cmd_s OakRating09[];
extern const txt_cmd_s OakRating10[];
extern const txt_cmd_s OakRating11[];
extern const txt_cmd_s OakRating12[];
extern const txt_cmd_s OakRating13[];
extern const txt_cmd_s OakRating14[];
extern const txt_cmd_s OakRating15[];
extern const txt_cmd_s OakRating16[];
extern const txt_cmd_s OakRating17[];
extern const txt_cmd_s OakRating18[];
extern const txt_cmd_s OakRating19[];
extern const txt_cmd_s OakPCText4[];
//#include "data/events/pokedex_ratings.h"
