void Special(uint16_t de);
void UnusedDummySpecial(void);
void SetPlayerPalette(void);
void GameCornerPrizeMonCheckDex(void);
void UnusedSetSeenMon(void);
void FindPartyMonAboveLevel(void);
void FindPartyMonAtLeastThatHappy(void);
void FindPartyMonThatSpecies(void);
void FindPartyMonThatSpeciesYourTrainerID(void);
void FoundOne(void);
void FoundNone(void);
void NameRival(void);
void NameRater(void);
void OverworldTownMap(void);
void UnownPrinter(void);
void DisplayLinkRecord(void);
void PlayersHousePC(void);
void CheckMysteryGift(void);
void GetMysteryGiftItem(void);
void BugContestJudging(void);
void MapRadio(void);
void UnownPuzzle(void);
void SlotMachine(void);
void CardFlip(void);
void UnusedMemoryGame(void);
void StartGameCornerGame(void (*func)(void));
bool CheckCoinsAndCoinCase(void);
void ClearBGPalettesBufferScreen(void);
void ScriptReturnCarry(void);
void ScriptReturnCarry_Conv(bool carry);
void UnusedCheckUnusedTwoDayTimer(void);
void ActivateFishingSwarm(void);
void StoreSwarmMapIndices(uint8_t flag, uint8_t group, uint8_t number);
void CheckPokerus(void);
void ResetLuckyNumberShowFlag(void);
void CheckLuckyNumberShowFlag(void);
void SnorlaxAwake(void);
void PlayCurMonCry(void);
void GameboyCheck(void);
void FadeOutMusic(void);
void Diploma(void);
void PrintDiploma(void);
void TrainerHouse(void);
//#include "data/events/special_pointers.h"
