#pragma once

#define stdscript_const(_x) StdScript_##_x

extern const Script_fn_t StdScripts[];

enum {
    stdscript_const(PokecenterNurseScript),
    stdscript_const(DifficultBookshelfScript),
    stdscript_const(PictureBookshelfScript),
    stdscript_const(MagazineBookshelfScript),
    stdscript_const(TeamRocketOathScript),
    stdscript_const(IncenseBurnerScript),
    stdscript_const(MerchandiseShelfScript),
    stdscript_const(TownMapScript),
    stdscript_const(WindowScript),
    stdscript_const(TVScript),
    stdscript_const(HomepageScript), // unused
    stdscript_const(Radio1Script),
    stdscript_const(Radio2Script),
    stdscript_const(TrashCanScript),
    stdscript_const(StrengthBoulderScript),
    stdscript_const(SmashRockScript),
    stdscript_const(PokecenterSignScript),
    stdscript_const(MartSignScript),
    stdscript_const(GoldenrodRocketsScript),
    stdscript_const(RadioTowerRocketsScript),
    stdscript_const(ElevatorButtonScript),
    stdscript_const(DayToTextScript),
    stdscript_const(BugContestResultsWarpScript),
    stdscript_const(BugContestResultsScript),
    stdscript_const(InitializeEventsScript),
    stdscript_const(AskNumber1MScript),
    stdscript_const(AskNumber2MScript),
    stdscript_const(RegisteredNumberMScript),
    stdscript_const(NumberAcceptedMScript),
    stdscript_const(NumberDeclinedMScript),
    stdscript_const(PhoneFullMScript),
    stdscript_const(RematchMScript),
    stdscript_const(GiftMScript),
    stdscript_const(PackFullMScript),
    stdscript_const(RematchGiftMScript),
    stdscript_const(AskNumber1FScript),
    stdscript_const(AskNumber2FScript),
    stdscript_const(RegisteredNumberFScript),
    stdscript_const(NumberAcceptedFScript),
    stdscript_const(NumberDeclinedFScript),
    stdscript_const(PhoneFullFScript),
    stdscript_const(RematchFScript),
    stdscript_const(GiftFScript),
    stdscript_const(PackFullFScript),
    stdscript_const(RematchGiftFScript),
    stdscript_const(GymStatue1Script),
    stdscript_const(GymStatue2Script),
    stdscript_const(ReceiveItemScript),
    stdscript_const(ReceiveTogepiEggScript),
    stdscript_const(PCScript),
    stdscript_const(GameCornerCoinVendorScript),
    stdscript_const(HappinessCheckScript),
};
