void HoOhChamber(void);
void OmanyteChamber(void);
void SpecialAerodactylChamber(void);
bool SpecialAerodactylChamber_Conv(void);
void SpecialKabutoChamber(void);
void DisplayUnownWords(void);
void v_DisplayUnownWords_FillAttr(void);
void v_DisplayUnownWords_CopyWord(void);
//#include "data/events/unown_walls.h"
