void DoMysteryGift(void);
uint8_t ExchangeMysteryGiftData(void);
void ReceiverExchangeMysteryGiftDataPayloads(void);
void ReceiverExchangeMysteryGiftDataPayloads_GotPayload(void);
void SenderExchangeMysteryGiftDataPayloads(void);
bool ReceiveMysteryGiftDataPayload(void);
bool ReceiveMysteryGiftDataPayload_GotRegionPrefix(void);
bool SendMysteryGiftDataPayload(void);
uint8_t EndOrContinueMysteryGiftIRCommunication(void);
uint8_t ExchangeNameCardData(void);
bool ReceiveNameCardDataPayload(void);
bool SendNameCardDataPayload(void);
uint8_t EndNameCardIRCommunication(void);
bool WrongMysteryGiftRegion(void);
bool BeginSendingIRCommunication(void);
bool BeginReceivingIRCommunication(void);
bool TrySendingIRDataBlock(const uint8_t* hl, uint8_t b);
bool TryReceivingIRDataBlock(uint8_t* hl, uint8_t b);
void InitializeIRCommunicationInterrupts(void);
void StartFastIRTimer(void);
void StartSlowIRTimer(void);
void BeginIRCommunication(void);
void EndIRCommunication(void);
void ReceiveInfraredLEDOn(void);
void ReceiveInfraredLEDOff(void);
void SendInfraredLEDOn(void);
void SendInfraredLEDOff(void);
void InitializeIRCommunicationRoles(void);
void ReceiveIRHelloMessage(void);
void SendIRHelloMessageAfterDelay(void);
void SendIRHelloMessage(void);
void ToggleIRCommunication(uint8_t a);
void SendIRDataBlock(const uint8_t* hl, uint8_t b);
void SendIRDataMessage(const uint8_t* hl, uint8_t b);
void InfraredLEDReceiveTimedOut(void);
void ReceivedWrongIRChecksum(void);
void ReceivedWrongIRMessagePrefix(void);
void ReceiveIRDataBlock(uint8_t* hl, uint8_t b);
bool ReceiveIRDataMessage(uint8_t* hl, uint8_t b);
void SendEmptyIRDataBlock(void);
void ReceiveEmptyIRDataBlock(void);
void MysteryGift_UpdateJoypad(void);
bool CheckAndSetMysteryGiftDecorationAlreadyReceived(uint8_t c);
void CopyMysteryGiftReceivedDecorationsToPC(void);
void UnlockMysteryGift(void);
void ResetDailyMysteryGiftLimitIfUnlocked(void);
void BackupMysteryGift(void);
void RestoreMysteryGift(void);
void ClearMysteryGiftTrainer(void);
void GetMysteryGiftBank(void);
void StagePartyDataForMysteryGift(void);
void InitMysteryGiftLayout(void);
extern const char MysteryGiftGFX[];
void DoNameCardSwap(void);
void StageDataForNameCard(void);
void InitNameCardLayout(void);
extern const char CardTradeGFX[];
extern const char CardTradeSpriteGFX[];
//#include "gfx/mystery_gift/mystery_gift.2bpp"
//#include "gfx/mystery_gift/card_trade.2bpp"
//#include "gfx/mystery_gift/card_sprite.2bpp"
