#pragma once
//// EVENTS
extern const struct MapScripts ElmsLab_MapScripts;
extern const struct MapEvents ElmsLab_MapEvents;

//// CODE

bool ElmsLab_MapScripts_MeetElm(script_s* s);
bool ElmsLab_MapScripts_DummyScene1(script_s* s);
bool ElmsLab_MapScripts_DummyScene2(script_s* s);
bool ElmsLab_MapScripts_DummyScene3(script_s* s);
bool ElmsLab_MapScripts_DummyScene4(script_s* s);
bool ElmsLab_MapScripts_DummyScene5(script_s* s);
bool ElmsLab_MapScripts_MoveElmCallback(script_s* s);
bool ElmsLab_MapScripts_Skip(script_s* s);
bool ElmsLab_MapScripts_WalkUpToElm(script_s* s);
bool ElmsLab_MapScripts_MustSayYes(script_s* s);
bool ElmsLab_MapScripts_ElmGetsEmail(script_s* s);
bool ProfElmScript(script_s* s);
bool ElmCheckMasterBall(script_s* s);
bool ElmCheckEverstone(script_s* s);
bool ElmEggHatchedScript(script_s* s);
bool ElmCheckTogepiEgg(script_s* s);
bool ElmCheckGotEggAgain(script_s* s);
bool LabTryToLeaveScript(script_s* s);
bool CyndaquilPokeBallScript(script_s* s);
bool TotodilePokeBallScript(script_s* s);
bool ChikoritaPokeBallScript(script_s* s);
bool DidntChooseStarterScript(script_s* s);
bool ElmDirectionsScript(script_s* s);
bool ElmDescribesMrPokemonScript(script_s* s);
bool LookAtElmPokeBallScript(script_s* s);
bool ElmsLabHealingMachine(script_s* s);
bool ElmsLabHealingMachine_HealParty(script_s* s);
bool ElmAfterTheftDoneScript(script_s* s);
bool ElmAfterTheftScript(script_s* s);
bool ElmStudyingEggScript(script_s* s);
bool ElmAideHasEggScript(script_s* s);
bool ElmWaitingEggHatchScript(script_s* s);
bool ShowElmTogepiScript(script_s* s);
bool ElmGiveEverstoneScript(script_s* s);
bool ElmScript_CallYou(script_s* s);
bool ElmScript_NoRoomForEverstone(script_s* s);
bool ElmGiveMasterBallScript(script_s* s);
bool ElmGiveTicketScript(script_s* s);
bool ElmJumpBackScript1(script_s* s);
bool ElmJumpBackScript2(script_s* s);
bool ElmJumpUpScript(script_s* s);
bool ElmJumpDownScript(script_s* s);
bool ElmJumpLeftScript(script_s* s);
bool ElmJumpRightScript(script_s* s);
bool AideScript_WalkPotion1(script_s* s);
bool AideScript_WalkPotion2(script_s* s);
bool AideScript_GivePotion(script_s* s);
bool AideScript_WalkBalls1(script_s* s);
bool AideScript_WalkBalls2(script_s* s);
bool AideScript_GiveYouBalls(script_s* s);
bool AideScript_ReceiveTheBalls(script_s* s);
bool ElmsAideScript(script_s* s);
bool AideScript_TheftTestimony(script_s* s);
bool AideScript_ExplainBalls(script_s* s);
bool AideScript_AfterTheft(script_s* s);
bool MeetCopScript2(script_s* s);
bool MeetCopScript(script_s* s);
bool CopScript(script_s* s);
bool ElmsLabWindow(script_s* s);
bool ElmsLabTravelTip1(script_s* s);
bool ElmsLabTravelTip2(script_s* s);
bool ElmsLabTravelTip3(script_s* s);
bool ElmsLabTravelTip4(script_s* s);
bool ElmsLabTrashcan(script_s* s);
bool ElmsLabPC(script_s* s);
bool ElmsLabTrashcan2(script_s* s);
bool ElmsLabBookshelf(script_s* s);
extern const uint8_t ElmsLab_WalkUpToElmMovement[];
extern const uint8_t ElmsLab_CantLeaveMovement[];
extern const uint8_t MeetCopScript2_StepLeft[];
extern const uint8_t MeetCopScript_WalkUp[];
extern const uint8_t OfficerLeavesMovement[];
extern const uint8_t AideWalksRight1[];
extern const uint8_t AideWalksRight2[];
extern const uint8_t AideWalksLeft1[];
extern const uint8_t AideWalksLeft2[];
extern const uint8_t ElmJumpUpMovement[];
extern const uint8_t ElmJumpDownMovement[];
extern const uint8_t ElmJumpLeftMovement[];
extern const uint8_t ElmJumpRightMovement[];
extern const uint8_t ElmsLab_ElmToDefaultPositionMovement1[];
extern const uint8_t ElmsLab_ElmToDefaultPositionMovement2[];
extern const uint8_t AfterCyndaquilMovement[];
extern const uint8_t AfterTotodileMovement[];
extern const uint8_t AfterChikoritaMovement[];
extern const txt_cmd_s ElmText_Intro[];
extern const txt_cmd_s ElmText_Accepted[];
extern const txt_cmd_s ElmText_Refused[];
extern const txt_cmd_s ElmText_ResearchAmbitions[];
extern const txt_cmd_s ElmText_GotAnEmail[];
extern const txt_cmd_s ElmText_MissionFromMrPokemon[];
extern const txt_cmd_s ElmText_ChooseAPokemon[];
extern const txt_cmd_s ElmText_LetYourMonBattleIt[];
extern const txt_cmd_s LabWhereGoingText[];
extern const txt_cmd_s TakeCyndaquilText[];
extern const txt_cmd_s TakeTotodileText[];
extern const txt_cmd_s TakeChikoritaText[];
extern const txt_cmd_s DidntChooseStarterText[];
extern const txt_cmd_s ChoseStarterText[];
extern const txt_cmd_s ReceivedStarterText[];
extern const txt_cmd_s ElmDirectionsText1[];
extern const txt_cmd_s ElmDirectionsText2[];
extern const txt_cmd_s ElmDirectionsText3[];
extern const txt_cmd_s GotElmsNumberText[];
extern const txt_cmd_s ElmDescribesMrPokemonText[];
extern const txt_cmd_s ElmPokeBallText[];
extern const txt_cmd_s ElmsLabHealingMachineText1[];
extern const txt_cmd_s ElmsLabHealingMachineText2[];
extern const txt_cmd_s ElmAfterTheftText1[];
extern const txt_cmd_s ElmAfterTheftText2[];
extern const txt_cmd_s ElmAfterTheftText3[];
extern const txt_cmd_s ElmAfterTheftText4[];
extern const txt_cmd_s ElmAfterTheftText5[];
extern const txt_cmd_s ElmAfterTheftText6[];
extern const txt_cmd_s ElmStudyingEggText[];
extern const txt_cmd_s ElmAideHasEggText[];
extern const txt_cmd_s ElmWaitingEggHatchText[];
extern const txt_cmd_s ElmThoughtEggHatchedText[];
extern const txt_cmd_s ShowElmTogepiText1[];
extern const txt_cmd_s ShowElmTogepiText2[];
extern const txt_cmd_s ShowElmTogepiText3[];
extern const txt_cmd_s ElmGiveEverstoneText1[];
extern const txt_cmd_s ElmGiveEverstoneText2[];
extern const txt_cmd_s ElmText_CallYou[];
extern const txt_cmd_s AideText_AfterTheft[];
extern const txt_cmd_s ElmGiveMasterBallText1[];
extern const txt_cmd_s ElmGiveMasterBallText2[];
extern const txt_cmd_s ElmGiveTicketText1[];
extern const txt_cmd_s ElmGiveTicketText2[];
extern const txt_cmd_s ElmsLabMonEggText[];
extern const txt_cmd_s AideText_GiveYouPotion[];
extern const txt_cmd_s AideText_AlwaysBusy[];
extern const txt_cmd_s AideText_TheftTestimony[];
extern const txt_cmd_s AideText_GiveYouBalls[];
extern const txt_cmd_s AideText_ExplainBalls[];
extern const txt_cmd_s ElmsLabOfficerText1[];
extern const txt_cmd_s ElmsLabOfficerText2[];
extern const txt_cmd_s ElmsLabWindowText1[];
extern const txt_cmd_s ElmsLabWindowText2[];
extern const txt_cmd_s ElmsLabTravelTip1Text[];
extern const txt_cmd_s ElmsLabTravelTip2Text[];
extern const txt_cmd_s ElmsLabTravelTip3Text[];
extern const txt_cmd_s ElmsLabTravelTip4Text[];
extern const txt_cmd_s ElmsLabTrashcanText[];
extern const txt_cmd_s ElmsLabPCText[];
