#pragma once
//// EVENTS
extern const struct MapScripts FastShipB1F_MapScripts;
extern const struct MapEvents FastShipB1F_MapEvents;

//// CODE

bool FastShipB1F_MapScripts_DummyScene0(script_s* s);
bool FastShipB1F_MapScripts_DummyScene1(script_s* s);
bool FastShipB1FSailorBlocksLeft(script_s* s);
bool FastShipB1FSailorBlocksRight(script_s* s);
bool FastShipB1FAlreadyBlocked(script_s* s);
bool FastShipB1FSailorScript(script_s* s);
extern const struct TrainerObj TrainerSailorJeff;
bool TrainerSailorJeff_Script(script_s* s);
extern const struct TrainerObj TrainerPicnickerDebra;
bool TrainerPicnickerDebra_Script(script_s* s);
extern const struct TrainerObj TrainerJugglerFritz;
bool TrainerJugglerFritz_Script(script_s* s);
extern const struct TrainerObj TrainerSailorGarrett;
bool TrainerSailorGarrett_Script(script_s* s);
extern const struct TrainerObj TrainerFisherJonah;
bool TrainerFisherJonah_Script(script_s* s);
extern const struct TrainerObj TrainerBlackbeltWai;
bool TrainerBlackbeltWai_Script(script_s* s);
extern const struct TrainerObj TrainerSailorKenneth;
bool TrainerSailorKenneth_Script(script_s* s);
extern const struct TrainerObj TrainerTeacherShirley;
bool TrainerTeacherShirley_Script(script_s* s);
extern const struct TrainerObj TrainerSchoolboyNate;
bool TrainerSchoolboyNate_Script(script_s* s);
extern const struct TrainerObj TrainerSchoolboyRicky;
bool TrainerSchoolboyRicky_Script(script_s* s);
bool FastShipB1FTrashcan(script_s* s);
extern const uint8_t FastShipB1FSailorBlocksRightMovement[];
extern const uint8_t FastShipB1FSailorBlocksLeftMovement[];
extern const txt_cmd_s FastShipB1FOnDutySailorText[];
extern const txt_cmd_s FastShipB1FOnDutySailorRefusedText[];
extern const txt_cmd_s FastShipB1FOnDutySailorThanksText[];
extern const txt_cmd_s FastShipB1FOnDutySailorSawLittleGirlText[];
extern const txt_cmd_s FastShipB1FOnDutySailorDirectionsText[];
extern const txt_cmd_s SailorJeffSeenText[];
extern const txt_cmd_s SailorJeffBeatenText[];
extern const txt_cmd_s SailorJeffAfterBattleText[];
extern const txt_cmd_s PicnickerDebraSeenText[];
extern const txt_cmd_s PicnickerDebraBeatenText[];
extern const txt_cmd_s PicnickerDebraAfterBattleText[];
extern const txt_cmd_s JugglerFritzSeenText[];
extern const txt_cmd_s JugglerFritzBeatenText[];
extern const txt_cmd_s JugglerFritzAfterBattleText[];
extern const txt_cmd_s SailorGarrettSeenText[];
extern const txt_cmd_s SailorGarrettBeatenText[];
extern const txt_cmd_s SailorGarrettAfterBattleText[];
extern const txt_cmd_s FisherJonahSeenText[];
extern const txt_cmd_s FisherJonahBeatenText[];
extern const txt_cmd_s FisherJonahAfterBattleText[];
extern const txt_cmd_s BlackbeltWaiSeenText[];
extern const txt_cmd_s BlackbeltWaiBeatenText[];
extern const txt_cmd_s BlackbeltWaiAfterBattleText[];
extern const txt_cmd_s SailorKennethSeenText[];
extern const txt_cmd_s SailorKennethBeatenText[];
extern const txt_cmd_s SailorKennethAfterBattleText[];
extern const txt_cmd_s TeacherShirleySeenText[];
extern const txt_cmd_s TeacherShirleyBeatenText[];
extern const txt_cmd_s TeacherShirleyAfterBattleText[];
extern const txt_cmd_s SchoolboyNateSeenText[];
extern const txt_cmd_s SchoolboyNateBeatenText[];
extern const txt_cmd_s SchoolboyNateAfterBattleText[];
extern const txt_cmd_s SchoolboyRickySeenText[];
extern const txt_cmd_s SchoolboyRickyBeatenText[];
extern const txt_cmd_s SchoolboyRickyAfterBattleText[];
