#pragma once
//// EVENTS
extern const struct MapScripts GoldenrodUndergroundSwitchRoomEntrances_MapScripts;
extern const struct MapEvents GoldenrodUndergroundSwitchRoomEntrances_MapEvents;

//// CODE

bool GoldenrodUndergroundSwitchRoomEntrances_MapScripts_DummyScene0(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrances_MapScripts_DummyScene1(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrances_MapScripts_UpdateDoorPositions(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrancesSuperNerdScript(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrancesTeacherScript(script_s* s);
bool UndergroundSilverScene1(script_s* s);
bool UndergroundSilverScene2(script_s* s);
bool UndergroundSilverBattleScript(script_s* s);
extern const struct TrainerObj TrainerGruntM11;
bool TrainerGruntM11_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM25;
bool TrainerGruntM25_Script(script_s* s);
extern const struct TrainerObj TrainerBurglarDuncan;
bool TrainerBurglarDuncan_Script(script_s* s);
extern const struct TrainerObj TrainerBurglarEddie;
bool TrainerBurglarEddie_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM13;
bool TrainerGruntM13_Script(script_s* s);
extern const struct TrainerObj TrainerGruntF3;
bool TrainerGruntF3_Script(script_s* s);
bool Switch1Script(script_s* s);
bool Switch2Script(script_s* s);
bool Switch3Script(script_s* s);
bool EmergencySwitchScript(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrances_DontToggle(script_s* s);
bool GoldenrodUndergroundSwitchRoomEntrances_UpdateDoors(script_s* s);
extern const struct ItemBall GoldenrodUndergroundSwitchRoomEntrancesSmokeBall;
extern const struct ItemBall GoldenrodUndergroundSwitchRoomEntrancesFullHeal;
extern const struct HiddenItem GoldenrodUndergroundSwitchRoomEntrancesHiddenMaxPotion;
extern const struct HiddenItem GoldenrodUndergroundSwitchRoomEntrancesHiddenRevive;
extern const uint8_t UndergroundSilverApproachMovement1[];
extern const uint8_t UndergroundSilverApproachMovement2[];
extern const uint8_t UndergroundSilverRetreatMovement1[];
extern const uint8_t UndergroundSilverRetreatMovement2[];
extern const txt_cmd_s UndergroundSilverBeforeText[];
extern const txt_cmd_s UndergroundSilverWinText[];
extern const txt_cmd_s UndergroundSilverAfterText[];
extern const txt_cmd_s UndergroundSilverLossText[];
extern const txt_cmd_s GoldenrodUndergroundSwitchRoomEntrances_SuperNerdText[];
extern const txt_cmd_s GoldenrodUndergroundSwitchRoomEntrances_TeacherText[];
extern const txt_cmd_s GruntM11SeenText[];
extern const txt_cmd_s GruntM11BeatenText[];
extern const txt_cmd_s GruntM11AfterBattleText[];
extern const txt_cmd_s GruntM25SeenText[];
extern const txt_cmd_s GruntM25BeatenText[];
extern const txt_cmd_s GruntM25AfterBattleText[];
extern const txt_cmd_s BurglarDuncanSeenText[];
extern const txt_cmd_s BurglarDuncanBeatenText[];
extern const txt_cmd_s BurglarDuncanAfterBattleText[];
extern const txt_cmd_s BurglarEddieSeenText[];
extern const txt_cmd_s BurglarEddieBeatenText[];
extern const txt_cmd_s BurglarEddieAfterBattleText[];
extern const txt_cmd_s GruntM13SeenText[];
extern const txt_cmd_s GruntM13BeatenText[];
extern const txt_cmd_s GruntM13AfterBattleText[];
extern const txt_cmd_s SwitchRoomText_Switch1[];
extern const txt_cmd_s GruntF3SeenText[];
extern const txt_cmd_s GruntF3BeatenText[];
extern const txt_cmd_s GruntF3AfterBattleText[];
extern const txt_cmd_s SwitchRoomText_OffTurnOn[];
extern const txt_cmd_s SwitchRoomText_OnTurnOff[];
extern const txt_cmd_s SwitchRoomText_Switch2[];
extern const txt_cmd_s SwitchRoomText_Switch3[];
extern const txt_cmd_s SwitchRoomText_Emergency[];
