#pragma once
//// EVENTS
extern const struct MapScripts GoldenrodCity_MapScripts;
extern const struct MapEvents GoldenrodCity_MapEvents;

//// CODE

bool GoldenrodCity_MapScripts_FlyPointAndFloria(script_s* s);
bool GoldenrodCity_MapScripts_FloriaDone(script_s* s);
bool GoldenrodCity_MapScripts_MoveTutor(script_s* s);
bool GoldenrodCity_MapScripts_MoveTutorDisappear(script_s* s);
bool GoldenrodCity_MapScripts_MoveTutorAppear(script_s* s);
bool GoldenrodCity_MapScripts_MoveTutorDone(script_s* s);
bool MoveTutorScript(script_s* s);
bool GoldenrodCityPokefanMScript(script_s* s);
bool GoldenrodCityYoungster1Script(script_s* s);
bool GoldenrodCityCooltrainerF1Script(script_s* s);
bool GoldenrodCityCooltrainerF2Script(script_s* s);
bool GoldenrodCityYoungster2Script(script_s* s);
bool GoldenrodCityLassScript(script_s* s);
bool GoldenrodCityGrampsScript(script_s* s);
bool GoldenrodCityRocketScoutScript(script_s* s);
bool GoldenrodCityRocket1Script(script_s* s);
bool GoldenrodCityRocket2Script(script_s* s);
bool GoldenrodCityRocket3Script(script_s* s);
bool GoldenrodCityRocket4Script(script_s* s);
bool GoldenrodCityRocket5Script(script_s* s);
bool GoldenrodCityRocket6Script(script_s* s);
bool GoldenrodCityStationSign(script_s* s);
bool GoldenrodCityRadioTowerSign(script_s* s);
bool GoldenrodDeptStoreSign(script_s* s);
bool GoldenrodGymSign(script_s* s);
bool GoldenrodCitySign(script_s* s);
bool GoldenrodCityBikeShopSign(script_s* s);
bool GoldenrodCityGameCornerSign(script_s* s);
bool GoldenrodCityNameRaterSign(script_s* s);
bool GoldenrodCityUndergroundSignNorth(script_s* s);
bool GoldenrodCityUndergroundSignSouth(script_s* s);
bool GoldenrodCityPokecenterSign(script_s* s);
bool GoldenrodCityFlowerShopSign(script_s* s);
extern const uint8_t GoldenrodCityMoveTutorEnterGameCornerMovement[];
extern const uint8_t GoldenrodCityMoveTutorWalkAroundPlayerThenEnterGameCornerMovement[];
extern const txt_cmd_s GoldenrodCityPokefanMText[];
extern const txt_cmd_s GoldenrodCityYoungster1Text[];
extern const txt_cmd_s GoldenrodCityCooltrainerF1Text[];
extern const txt_cmd_s GoldenrodCityCooltrainerF1Text_ClearedRadioTower[];
extern const txt_cmd_s GoldenrodCityCooltrainerF2Text[];
extern const txt_cmd_s GoldenrodCityCooltrainerF2Text_GotRadioCard[];
extern const txt_cmd_s GoldenrodCityYoungster2Text[];
extern const txt_cmd_s GoldenrodCityLassText[];
extern const txt_cmd_s GoldenrodCityGrampsText[];
extern const txt_cmd_s GoldenrodCityRocketScoutText1[];
extern const txt_cmd_s GoldenrodCityRocketScoutText2[];
extern const txt_cmd_s GoldenrodCityRocket1Text[];
extern const txt_cmd_s GoldenrodCityRocket2Text[];
extern const txt_cmd_s GoldenrodCityRocket3Text[];
extern const txt_cmd_s GoldenrodCityRocket4Text[];
extern const txt_cmd_s GoldenrodCityRocket5Text[];
extern const txt_cmd_s GoldenrodCityRocket6Text[];
extern const txt_cmd_s GoldenrodCityStationSignText[];
extern const txt_cmd_s GoldenrodCityRadioTowerSignText[];
extern const txt_cmd_s GoldenrodDeptStoreSignText[];
extern const txt_cmd_s GoldenrodGymSignText[];
extern const txt_cmd_s GoldenrodCitySignText[];
extern const txt_cmd_s GoldenrodCityBikeShopSignText[];
extern const txt_cmd_s GoldenrodCityGameCornerSignText[];
extern const txt_cmd_s GoldenrodCityNameRaterSignText[];
extern const txt_cmd_s GoldenrodCityUndergroundSignNorthText[];
extern const txt_cmd_s GoldenrodCityUndergroundSignSouthText[];
extern const txt_cmd_s GoldenrodCityPokeComCenterSignText[];
extern const txt_cmd_s GoldenrodCityFlowerShopSignText[];
extern const txt_cmd_s GoldenrodCityMoveTutorAskTeachAMoveText[];
extern const txt_cmd_s GoldenrodCityMoveTutorAsk4000CoinsOkayText[];
extern const txt_cmd_s GoldenrodCityMoveTutorAwwButTheyreAmazingText[];
extern const txt_cmd_s GoldenrodCityMoveTutorWhichMoveShouldITeachText[];
extern const txt_cmd_s GoldenrodCityMoveTutorHmTooBadText[];
extern const txt_cmd_s GoldenrodCityMoveTutorIfYouUnderstandYouveMadeItText[];
extern const txt_cmd_s GoldenrodCityMoveTutorFarewellKidText[];
extern const txt_cmd_s GoldenrodCityMoveTutorBButText[];
extern const txt_cmd_s GoldenrodCityMoveTutorYouDontHaveEnoughCoinsText[];
extern const txt_cmd_s GoldenrodCityMoveTutorMoveText[];
