#pragma once
//// EVENTS
extern const struct MapScripts IlexForest_MapScripts;
extern const struct MapEvents IlexForest_MapEvents;

//// CODE

bool IlexForest_MapScripts_FarfetchdCallback(script_s* s);
bool IlexForest_MapScripts_Static(script_s* s);
bool IlexForest_MapScripts_PositionOne(script_s* s);
bool IlexForest_MapScripts_PositionTwo(script_s* s);
bool IlexForest_MapScripts_PositionThree(script_s* s);
bool IlexForest_MapScripts_PositionFour(script_s* s);
bool IlexForest_MapScripts_PositionFive(script_s* s);
bool IlexForest_MapScripts_PositionSix(script_s* s);
bool IlexForest_MapScripts_PositionSeven(script_s* s);
bool IlexForest_MapScripts_PositionEight(script_s* s);
bool IlexForest_MapScripts_PositionNine(script_s* s);
bool IlexForest_MapScripts_PositionTen(script_s* s);
bool IlexForestCharcoalApprenticeScript(script_s* s);
bool IlexForestFarfetchdScript(script_s* s);
bool IlexForestCharcoalMasterScript(script_s* s);
bool IlexForestHeadbuttGuyScript(script_s* s);
extern const struct TrainerObj TrainerBugCatcherWayne;
bool TrainerBugCatcherWayne_Script(script_s* s);
bool IlexForestLassScript(script_s* s);
extern const struct ItemBall IlexForestRevive;
extern const struct ItemBall IlexForestXAttack;
extern const struct ItemBall IlexForestAntidote;
extern const struct ItemBall IlexForestEther;
extern const struct HiddenItem IlexForestHiddenEther;
extern const struct HiddenItem IlexForestHiddenSuperPotion;
extern const struct HiddenItem IlexForestHiddenFullHeal;
bool IlexForestBoulder(script_s* s);
bool IlexForestSignpost(script_s* s);
bool IlexForestShrineScript(script_s* s);
extern const uint8_t MovementData_Farfetchd_Pos1_Pos2[];
extern const uint8_t MovementData_Farfetchd_Pos2_Pos3[];
extern const uint8_t MovementData_Farfetchd_Pos2_Pos8[];
extern const uint8_t MovementData_Farfetchd_Pos3_Pos4[];
extern const uint8_t MovementData_Farfetchd_Pos3_Pos2[];
extern const uint8_t MovementData_Farfetchd_Pos4_Pos5[];
extern const uint8_t MovementData_Farfetchd_Pos4_Pos3[];
extern const uint8_t MovementData_Farfetchd_Pos5_Pos6[];
extern const uint8_t MovementData_Farfetchd_Pos5_Pos7[];
extern const uint8_t MovementData_Farfetched_Pos5_Pos4_Up[];
extern const uint8_t MovementData_Farfetched_Pos5_Pos4_Right[];
extern const uint8_t MovementData_Farfetched_Pos6_Pos7[];
extern const uint8_t MovementData_Farfetched_Pos6_Pos5[];
extern const uint8_t MovementData_Farfetched_Pos7_Pos8[];
extern const uint8_t MovementData_Farfetched_Pos7_Pos6[];
extern const uint8_t MovementData_Farfetched_Pos7_Pos5[];
extern const uint8_t MovementData_Farfetched_Pos8_Pos9[];
extern const uint8_t MovementData_Farfetched_Pos8_Pos7[];
extern const uint8_t MovementData_Farfetched_Pos8_Pos2[];
extern const uint8_t MovementData_Farfetched_Pos9_Pos10[];
extern const uint8_t MovementData_Farfetched_Pos9_Pos8_Right[];
extern const uint8_t MovementData_Farfetched_Pos9_Pos8_Down[];
extern const uint8_t IlexForestKurtStepsUpMovement[];
extern const uint8_t IlexFOrestKurtStepsDownMovement[];
extern const uint8_t IlexForestPlayerStepsDownMovement[];
extern const txt_cmd_s IlexForestApprenticeIntroText[];
extern const txt_cmd_s IlexForestApprenticeAfterText[];
extern const txt_cmd_s Text_ItsTheMissingPokemon[];
extern const txt_cmd_s Text_Kwaaaa[];
extern const txt_cmd_s Text_CharcoalMasterIntro[];
extern const txt_cmd_s Text_CharcoalMasterOutro[];
extern const txt_cmd_s Text_CharcoalMasterTalkAfter[];
extern const txt_cmd_s Text_HeadbuttIntro[];
extern const txt_cmd_s Text_HeadbuttOutro[];
extern const txt_cmd_s Text_IlexForestLass[];
extern const txt_cmd_s IlexForestSignpostText[];
extern const txt_cmd_s Text_IlexForestShrine[];
extern const txt_cmd_s Text_ShrineCelebiEvent[];
extern const txt_cmd_s Text_InsertGSBall[];
extern const txt_cmd_s Text_KurtCaughtCelebi[];
extern const txt_cmd_s BugCatcherWayneSeenText[];
extern const txt_cmd_s BugCatcherWayneBeatenText[];
extern const txt_cmd_s BugCatcherWayneAfterBattleText[];
