#pragma once
//// EVENTS
extern const struct MapScripts LakeOfRage_MapScripts;
extern const struct MapEvents LakeOfRage_MapEvents;

//// CODE

bool LakeOfRage_MapScripts_DummyScene0(script_s* s);
bool LakeOfRage_MapScripts_DummyScene1(script_s* s);
bool LakeOfRage_MapScripts_FlyPoint(script_s* s);
bool LakeOfRage_MapScripts_Wesley(script_s* s);
bool LakeOfRageLanceScript(script_s* s);
bool RedGyarados(script_s* s);
bool LakeOfRageGrampsScript(script_s* s);
bool LakeOfRageSuperNerdScript(script_s* s);
bool LakeOfRageCooltrainerFScript(script_s* s);
bool LakeOfRageSign(script_s* s);
bool MagikarpHouseSignScript(script_s* s);
extern const struct TrainerObj TrainerFisherAndre;
bool TrainerFisherAndre_Script(script_s* s);
extern const struct TrainerObj TrainerFisherRaymond;
bool TrainerFisherRaymond_Script(script_s* s);
extern const struct TrainerObj TrainerCooltrainermAaron;
bool TrainerCooltrainermAaron_Script(script_s* s);
extern const struct TrainerObj TrainerCooltrainerfLois;
bool TrainerCooltrainerfLois_Script(script_s* s);
bool WesleyScript(script_s* s);
bool WesleyWednesdayScript(script_s* s);
bool WesleyDoneScript(script_s* s);
bool WesleyNotWednesdayScript(script_s* s);
extern const struct ItemBall LakeOfRageElixer;
extern const struct ItemBall LakeOfRageTMDetect;
extern const struct HiddenItem LakeOfRageHiddenFullRestore;
extern const struct HiddenItem LakeOfRageHiddenRareCandy;
extern const struct HiddenItem LakeOfRageHiddenMaxPotion;
extern const uint8_t LakeOfRageLanceTeleportIntoSkyMovement[];
extern const txt_cmd_s LakeOfRageLanceForcedToEvolveText[];
extern const txt_cmd_s LakeOfRageLanceIntroText[];
extern const txt_cmd_s LakeOfRageLanceRadioSignalText[];
extern const txt_cmd_s LakeOfRageLanceRefusedText[];
extern const txt_cmd_s LakeOfRageLanceAskHelpText[];
extern const txt_cmd_s LakeOfRageGyaradosCryText[];
extern const txt_cmd_s LakeOfRageGotRedScaleText[];
extern const txt_cmd_s LakeOfRageGrampsText[];
extern const txt_cmd_s LakeOfRageGrampsText_ClearedRocketHideout[];
extern const txt_cmd_s LakeOfRageSuperNerdText[];
extern const txt_cmd_s LakeOfRageCooltrainerFText[];
extern const txt_cmd_s FisherAndreSeenText[];
extern const txt_cmd_s FisherAndreBeatenText[];
extern const txt_cmd_s FisherAndreAfterBattleText[];
extern const txt_cmd_s FisherRaymondSeenText[];
extern const txt_cmd_s FisherRaymondBeatenText[];
extern const txt_cmd_s FisherRaymondAfterBattleText[];
extern const txt_cmd_s CooltrainermAaronSeenText[];
extern const txt_cmd_s CooltrainermAaronBeatenText[];
extern const txt_cmd_s CooltrainermAaronAfterBattleText[];
extern const txt_cmd_s CooltrainerfLoisSeenText[];
extern const txt_cmd_s CooltrainerfLoisBeatenText[];
extern const txt_cmd_s CooltrainerfLoisAfterBattleText[];
extern const txt_cmd_s MeetWesleyText[];
extern const txt_cmd_s WesleyGivesGiftText[];
extern const txt_cmd_s WesleyGaveGiftText[];
extern const txt_cmd_s WesleyWednesdayText[];
extern const txt_cmd_s WesleyNotWednesdayText[];
extern const txt_cmd_s LakeOfRageSignText[];
extern const txt_cmd_s FishingGurusHouseSignText[];
