#pragma once
//// EVENTS
extern const struct MapScripts PokecomCenter_MapScripts;
extern const struct MapEvents PokecomCenter_MapEvents;

//// CODE

bool PokecomCenter_MapScripts_Scene0(script_s* s);
bool GoldenrodPokecenter1F_scenejmp01(script_s* s);
bool GoldenrodPokecenter1F_noTrade(script_s* s);
bool GoldenrodPokecenter1F_scenejmp02(script_s* s);
bool GoldenrodPokecenter1F_prepareMap(script_s* s);
bool GoldenrodPokecenter1FNurseScript(script_s* s);
bool GoldenrodPokecenter1FTradeCornerAttendantScript(script_s* s);
bool GoldenrodPokecenter1FTradeCornerAttendantScript_receivedOddEgg(script_s* s);
bool GoldenrodPokecenter1F_NewsMachineScript(script_s* s);
bool GoldenrodPokecenter1F_GSBallSceneLeft(script_s* s);
bool GoldenrodPokecenter1F_GSBallSceneRight(script_s* s);
bool GoldenrodPokecenter1FGameboyKidScript(script_s* s);
bool GoldenrodPokecenter1FLassScript(script_s* s);
bool GoldenrodPokecenter1FPokefanF(script_s* s);
bool GoldenrodPokecenter1FSuperNerdScript(script_s* s);
bool GoldenrodPokecenter1FLass2Script(script_s* s);
bool GoldenrodPokecenter1FYoungsterScript(script_s* s);
bool GoldenrodPokecenter1FTeacherScript(script_s* s);
bool GoldenrodPokecenter1FRockerScript(script_s* s);
bool GoldenrodPokecenter1FGrampsScript(script_s* s);
bool PokeComCenterInfoSign(script_s* s);
extern const uint8_t GoldenrodPokeCenter1FLinkReceptionistApproachPlayerAtLeftDoorwayTileMovement[];
extern const uint8_t GoldenrodPokeCenter1FLinkReceptionistWalkToStairsFromLeftDoorwayTileMovement[];
extern const uint8_t GoldenrodPokeCenter1FLinkReceptionistApproachPlayerAtRightDoorwayTileMovement[];
extern const uint8_t GoldenrodPokeCenter1FLinkReceptionistWalkToStairsFromRightDoorwayTileMovement[];
extern const uint8_t GoldenrodPokeCenter1FLass2WalkRightMovement[];
extern const uint8_t GoldenrodPokeCenter1FLassWalkRightAroundPlayerMovement[];
extern const txt_cmd_s GoldenrodPokecomCenterWelcomeToTradeCornerText[];
extern const txt_cmd_s GoldenrodPokecomCenterWeMustHoldYourMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterWhatMonDoYouWantText[];
extern const txt_cmd_s GoldenrodPokecomCenterWeWillTradeYourMonForMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterWeWillTradeYourMonForNewText[];
extern const txt_cmd_s GoldenrodPokecomCenterYourMonHasBeenReceivedText[];
extern const txt_cmd_s GoldenrodPokecomCenterYouHaveOnlyOneMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterWeHopeToSeeYouAgainText[];
extern const txt_cmd_s GoldenrodPokecomCenterCommunicationErrorText[];
extern const txt_cmd_s GoldenrodPokecomCenterCantAcceptLastMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterCantAcceptEggText[];
extern const txt_cmd_s GoldenrodPokecomCenterCantAcceptAbnormalMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterAlreadyHoldingMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterCheckingTheRoomsText[];
extern const txt_cmd_s GoldenrodPokecomCenterTradePartnerHasBeenFoundText[];
extern const txt_cmd_s GoldenrodPokecomCenterItsYourNewPartnerText[];
extern const txt_cmd_s GoldenrodPokecomCenterYourPartyIsFullText[];
extern const txt_cmd_s GoldenrodPokecomCenterNoTradePartnerFoundText[];
extern const txt_cmd_s GoldenrodPokecomCenterReturnedYourMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterYourMonIsLonelyText[];
extern const txt_cmd_s GoldenrodPokecenter1FWeHopeToSeeYouAgainText_2[];
extern const txt_cmd_s GoldenrodPokecomCenterContinueToHoldYourMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterRecentlyLeftYourMonText[];
extern const txt_cmd_s GoldenrodPokecomCenterSaveBeforeTradeCornerText[];
extern const txt_cmd_s GoldenrodPokecomCenterWhichMonToTradeText[];
extern const txt_cmd_s GoldenrodPokecomCenterTradeCanceledText[];
extern const txt_cmd_s GoldenrodPokecomCenterEggTicketText[];
extern const txt_cmd_s GoldenrodPokecomCenterOddEggBriefingText[];
extern const txt_cmd_s GoldenrodPokecomCenterPleaseWaitAMomentText[];
extern const txt_cmd_s GoldenrodPokecomCenterHereIsYourOddEggText[];
extern const txt_cmd_s GoldenrodPokecomCenterNoEggTicketServiceText[];
extern const txt_cmd_s GoldenrodPokecomCenterNewsMachineText[];
extern const txt_cmd_s GoldenrodPokecomCenterWhatToDoText[];
extern const txt_cmd_s GoldenrodPokecomCenterNewsMachineExplanationText[];
extern const txt_cmd_s GoldenrodPokecomCenterWouldYouLikeTheNewsText[];
extern const txt_cmd_s GoldenrodPokecomCenterReadingTheLatestNewsText[];
extern const txt_cmd_s GoldenrodPokecomCenterNoOldNewsText[];
extern const txt_cmd_s GoldenrodPokecomCenterCorruptedNewsDataText[];
extern const txt_cmd_s GoldenrodPokecomCenterMakingPreparationsText[];
extern const txt_cmd_s GoldenrodPokecomCenterSaveBeforeNewsMachineText[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson1Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson2Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson3Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson4Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson5Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson6Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson7Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson8Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson9Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson10Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson11Text[];
extern const txt_cmd_s GoldenrodPokecenter1FGameboyKidText[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson12Text[];
extern const txt_cmd_s GoldenrodPokecomCenterPerson13Text[];
extern const txt_cmd_s GoldenrodPokecenter1FLassText[];
extern const txt_cmd_s GoldenrodPokeCenter1FLinkReceptionistPleaseAcceptGSBallText[];
extern const txt_cmd_s GoldenrodPokeCenter1FLinkReceptionistPleaseDoComeAgainText[];
extern const txt_cmd_s GoldenrodPokecomCenterSignText[];
extern const txt_cmd_s GoldenrodPokecomCenterNewsMachineNotYetText[];
extern const txt_cmd_s GoldenrodPokecenter1FPokefanFDoYouHaveEonMailText[];
extern const txt_cmd_s GoldenrodPokecenter1FAskGiveAwayAnEonMailText[];
extern const txt_cmd_s GoldenrodPokecenter1FPokefanFThisIsForYouText[];
extern const txt_cmd_s GoldenrodPokecenter1FPokefanFDaughterWillBeDelightedText[];
extern const txt_cmd_s GoldenrodPokecenter1FPokefanFTooBadText[];
extern const txt_cmd_s GoldenrodPokecenter1FPokefanFAnotherTimeThenText[];
extern const txt_cmd_s GoldenrodPokecenter1FPlayerGaveAwayTheEonMailText[];
bool GoldenrodPokecenter1F_MapEvents(script_s* s);
