#pragma once
//// EVENTS
extern const struct MapScripts RadioTower2F_MapScripts;
extern const struct MapEvents RadioTower2F_MapEvents;

//// CODE

bool RadioTower2FUnusedDummyScene(script_s* s);
bool RadioTower2FSuperNerdScript(script_s* s);
bool RadioTower2FTeacherScript(script_s* s);
bool RadioTowerJigglypuff(script_s* s);
bool RadioTower2FBlackBelt1Script(script_s* s);
bool RadioTower2FBlackBelt2Script(script_s* s);
extern const struct TrainerObj TrainerGruntM4;
bool TrainerGruntM4_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM5;
bool TrainerGruntM5_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM6;
bool TrainerGruntM6_Script(script_s* s);
extern const struct TrainerObj TrainerGruntF2;
bool TrainerGruntF2_Script(script_s* s);
bool Buena(script_s* s);
bool RadioTowerBuenaPrizeReceptionist(script_s* s);
bool RadioTower2FSalesSign(script_s* s);
bool RadioTower2FOaksPKMNTalkSign(script_s* s);
bool RadioTower2FPokemonRadioSign(script_s* s);
bool RadioTower2FBookshelf(script_s* s);
extern const uint8_t RadioTower2FPlayerWalksToMicrophoneMovement[];
extern const txt_cmd_s RadioTower2FSuperNerdText[];
extern const txt_cmd_s RadioTower2FTeacherText[];
extern const txt_cmd_s RadioTower2FTeacherText_Rockets[];
extern const txt_cmd_s RadioTowerJigglypuffText[];
extern const txt_cmd_s RadioTower2FBlackBelt1Text[];
extern const txt_cmd_s RadioTower2FBlackBelt2Text[];
extern const txt_cmd_s GruntM4SeenText[];
extern const txt_cmd_s GruntM4BeatenText[];
extern const txt_cmd_s GruntM4AfterBattleText[];
extern const txt_cmd_s GruntM5SeenText[];
extern const txt_cmd_s GruntM5BeatenText[];
extern const txt_cmd_s GruntM5AfterBattleText[];
extern const txt_cmd_s GruntM6SeenText[];
extern const txt_cmd_s GruntM6BeatenText[];
extern const txt_cmd_s GruntM6AfterBattleText[];
extern const txt_cmd_s GruntF2SeenText[];
extern const txt_cmd_s GruntF2BeatenText[];
extern const txt_cmd_s GruntF2AfterBattleText[];
extern const txt_cmd_s RadioTower2FBuenaShowIntroductionText[];
extern const txt_cmd_s RadioTower2FBuenaTuneInToMyShowText[];
extern const txt_cmd_s RadioTower2FBuenaDoYouKnowPasswordText[];
extern const txt_cmd_s RadioTower2FBuenaJoinTheShowText[];
extern const txt_cmd_s RadioTower2FBuenaEveryoneSayPasswordText[];
extern const txt_cmd_s RadioTower2FBuenaComeBackAfterListeningText[];
extern const txt_cmd_s RadioTower2FBuenaAlreadyPlayedText[];
extern const txt_cmd_s RadioTower2FBuenaCorrectAnswerText[];
extern const txt_cmd_s RadioTower2FBuenaDidYouForgetText[];
extern const txt_cmd_s RadioTower2FBuenaThanksForComingText[];
extern const txt_cmd_s RadioTower2FBuenaPasswordIsHelpText[];
extern const txt_cmd_s RadioTower2FBuenaCardIsFullText[];
extern const txt_cmd_s RadioTower2FBuenaTuneInAfterSixText[];
extern const txt_cmd_s RadioTower2FBuenaNoBlueCardText[];
extern const txt_cmd_s RadioTower2FBuenaOfferPhoneNumberText[];
extern const txt_cmd_s RadioTower2FBuenaOfferNumberAgainText[];
extern const txt_cmd_s RadioTower2FRegisteredBuenasNumberText[];
extern const txt_cmd_s RadioTower2FBuenaCallMeText[];
extern const txt_cmd_s RadioTower2FBuenaSadRejectedText[];
extern const txt_cmd_s RadioTower2FBuenaYourPhoneIsFullText[];
extern const txt_cmd_s RadioTower2FBuenaReceptionistPointsForPrizesText[];
extern const txt_cmd_s RadioTower2FBuenaReceptionistNoCardText[];
extern const txt_cmd_s RadioTower2FSalesSignText[];
extern const txt_cmd_s RadioTower2FOaksPKMNTalkSignText[];
extern const txt_cmd_s RadioTower2FPokemonRadioSignText[];
