#pragma once
//// EVENTS
extern const struct MapScripts Route32_MapScripts;
extern const struct MapEvents Route32_MapEvents;

//// CODE

bool Route32_MapScripts_DummyScene0(script_s* s);
bool Route32_MapScripts_DummyScene1(script_s* s);
bool Route32_MapScripts_DummyScene2(script_s* s);
bool Route32_MapScripts_Frieda(script_s* s);
bool Route32_MapScripts_FriedaAppears(script_s* s);
bool Route32CooltrainerMScript(script_s* s);
bool Route32CooltrainerMContinueScene(script_s* s);
bool Route32CooltrainerMStopsYouScene(script_s* s);
bool Route32RoarTMGuyScript(script_s* s);
bool Route32WannaBuyASlowpokeTailScript(script_s* s);
bool SlowpokeTailSalesmanScript(script_s* s);
bool _OfferToSellSlowpokeTail(script_s* s);
extern const struct TrainerObj TrainerCamperRoland;
bool TrainerCamperRoland_Script(script_s* s);
extern const struct TrainerObj TrainerFisherJustin;
bool TrainerFisherJustin_Script(script_s* s);
extern const struct TrainerObj TrainerFisherRalph1;
bool TrainerFisherRalph1_Script(script_s* s);
extern const struct TrainerObj TrainerFisherHenry;
bool TrainerFisherHenry_Script(script_s* s);
extern const struct TrainerObj TrainerPicnickerLiz1;
bool TrainerPicnickerLiz1_Script(script_s* s);
extern const struct TrainerObj TrainerYoungsterAlbert;
bool TrainerYoungsterAlbert_Script(script_s* s);
extern const struct TrainerObj TrainerYoungsterGordon;
bool TrainerYoungsterGordon_Script(script_s* s);
extern const struct TrainerObj TrainerBirdKeeperPeter;
bool TrainerBirdKeeperPeter_Script(script_s* s);
bool FriedaScript(script_s* s);
extern const struct ItemBall Route32GreatBall;
extern const struct ItemBall Route32Repel;
bool Route32Sign(script_s* s);
bool Route32RuinsSign(script_s* s);
bool Route32UnionCaveSign(script_s* s);
bool Route32PokecenterSign(script_s* s);
extern const struct HiddenItem Route32HiddenGreatBall;
extern const struct HiddenItem Route32HiddenSuperPotion;
extern const uint8_t Movement_Route32CooltrainerMPushesYouBackToViolet[];
extern const uint8_t Movement_Route32CooltrainerMReset1[];
extern const uint8_t Movement_Route32CooltrainerMReset2[];
extern const txt_cmd_s Route32CooltrainerMText_WhatsTheHurry[];
extern const txt_cmd_s Route32CooltrainerMText_AideIsWaiting[];
extern const txt_cmd_s Route32CooltrainerMText_UnusedSproutTower[];
extern const txt_cmd_s Route32CooltrainerMText_VioletGym[];
extern const txt_cmd_s Route32CooltrainerMText_HaveThisSeed[];
extern const txt_cmd_s Route32CooltrainerMText_ExperiencesShouldBeUseful[];
extern const txt_cmd_s Text_MillionDollarSlowpokeTail[];
extern const txt_cmd_s Text_ThoughtKidsWereLoaded[];
extern const txt_cmd_s Text_RefusedToBuySlowpokeTail[];
extern const txt_cmd_s FisherJustinSeenText[];
extern const txt_cmd_s FisherJustinBeatenText[];
extern const txt_cmd_s FisherJustinAfterText[];
extern const txt_cmd_s FisherRalph1SeenText[];
extern const txt_cmd_s FisherRalph1BeatenText[];
extern const txt_cmd_s FisherRalphAfterText[];
extern const txt_cmd_s FisherRalphSwarmText[];
extern const txt_cmd_s Route32UnusedFisher1SeenText[];
extern const txt_cmd_s Route32UnusedFisher1BeatenText[];
extern const txt_cmd_s Route32UnusedFisher1AfterText[];
extern const txt_cmd_s Route32UnusedFisher2SeenText[];
extern const txt_cmd_s Route32UnusedFisher2BeatenText[];
extern const txt_cmd_s Route32UnusedFisher2AfterText[];
extern const txt_cmd_s FisherHenrySeenText[];
extern const txt_cmd_s FisherHenryBeatenText[];
extern const txt_cmd_s FisherHenryAfterText[];
extern const txt_cmd_s YoungsterAlbertSeenText[];
extern const txt_cmd_s YoungsterAlbertBeatenText[];
extern const txt_cmd_s YoungsterAlbertAfterText[];
extern const txt_cmd_s YoungsterGordonSeenText[];
extern const txt_cmd_s YoungsterGordonBeatenText[];
extern const txt_cmd_s YoungsterGordonAfterText[];
extern const txt_cmd_s CamperRolandSeenText[];
extern const txt_cmd_s CamperRolandBeatenText[];
extern const txt_cmd_s CamperRolandAfterText[];
extern const txt_cmd_s PicnickerLiz1SeenText[];
extern const txt_cmd_s PicnickerLiz1BeatenText[];
extern const txt_cmd_s PicnickerLiz1AfterText[];
extern const txt_cmd_s BirdKeeperPeterSeenText[];
extern const txt_cmd_s BirdKeeperPeterBeatenText[];
extern const txt_cmd_s BirdKeeperPeterAfterText[];
extern const txt_cmd_s Route32UnusedText[];
extern const txt_cmd_s Text_RoarIntro[];
extern const txt_cmd_s Text_RoarOutro[];
extern const txt_cmd_s MeetFriedaText[];
extern const txt_cmd_s FriedaGivesGiftText[];
extern const txt_cmd_s FriedaGaveGiftText[];
extern const txt_cmd_s FriedaFridayText[];
extern const txt_cmd_s FriedaNotFridayText[];
extern const txt_cmd_s Route32SignText[];
extern const txt_cmd_s Route32RuinsSignText[];
extern const txt_cmd_s Route32UnionCaveSignText[];
