#pragma once
//// EVENTS
extern const struct MapScripts Route36NationalParkGate_MapScripts;
extern const struct MapEvents Route36NationalParkGate_MapEvents;

//// CODE

bool Route36NationalParkGate_MapScripts_DummyScene0(script_s* s);
bool Route36NationalParkGate_MapScripts_DummyScene1(script_s* s);
bool Route36NationalParkGate_MapScripts_LeaveContestEarly(script_s* s);
bool Route36NationalParkGate_MapScripts_CheckIfContestRunning(script_s* s);
bool Route36NationalParkGate_MapScripts_CheckIfContestAvailable(script_s* s);
bool Route36NationalParkGate_MapScripts_LeavingContestEarly(script_s* s);
bool Route36NationalParkGate_MapScripts_GoBackToContest(script_s* s);
bool Route36NationalParkGate_MapScripts_CopyContestants(script_s* s);
bool Route36OfficerScriptContest(script_s* s);
bool Route36Officer_ContestHasConcluded(script_s* s);
bool _ContestNotOn(script_s* s);
bool Route36NationalParkGateOfficerScript(script_s* s);
bool Route36ParkGate_DayToText(script_s* s);
bool BugCatchingContestant1BScript(script_s* s);
bool BugCatchingContestant2BScript(script_s* s);
bool BugCatchingContestant3BScript(script_s* s);
bool BugCatchingContestant4BScript(script_s* s);
bool BugCatchingContestant5BScript(script_s* s);
bool BugCatchingContestant6BScript(script_s* s);
bool BugCatchingContestant7BScript(script_s* s);
bool BugCatchingContestant8BScript(script_s* s);
bool BugCatchingContestant9BScript(script_s* s);
bool BugCatchingContestant10BScript(script_s* s);
bool UnusedBugCatchingContestExplanationSign(script_s* s);
extern const uint8_t Route36NationalParkGatePlayerWaitWithContestantsMovement[];
extern const txt_cmd_s Route36NationalParkGateOfficer1AskToParticipateText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1GiveParkBallsText[];
extern const txt_cmd_s Route36NationalParkGatePlayerReceivedParkBallsText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1ExplainsRulesText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1AskToUseFirstMonText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1WellHoldYourMonText[];
extern const txt_cmd_s Route36NationalParkGatePlayersMonLeftWithHelperText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1ChooseMonAndComeBackText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1TakePartInFutureText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1FirstMonCantBattleText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1MakeRoomText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1EggAsFirstMonText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1WantToFinishText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1WaitHereForAnnouncementText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1OkGoFinishText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1ContestIsOverText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1SomeMonOnlySeenInParkText[];
extern const txt_cmd_s BugCatchingContestant1BText[];
extern const txt_cmd_s BugCatchingContestant1BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant2BText[];
extern const txt_cmd_s BugCatchingContestant2BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant3BText[];
extern const txt_cmd_s BugCatchingContestant3BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant4BText[];
extern const txt_cmd_s BugCatchingContestant4BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant5BText[];
extern const txt_cmd_s BugCatchingContestant5BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant6BText[];
extern const txt_cmd_s BugCatchingContestant6BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant7BText[];
extern const txt_cmd_s BugCatchingContestant7BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant8BText[];
extern const txt_cmd_s BugCatchingContestant8BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant9BText[];
extern const txt_cmd_s BugCatchingContestant9BStillCompetingText[];
extern const txt_cmd_s BugCatchingContestant10BText[];
extern const txt_cmd_s BugCatchingContestant10BStillCompetingText[];
extern const txt_cmd_s UnusedSilphScope2Text[];
extern const txt_cmd_s UnusedBugCatchingContestExplanationText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1WellHoldPrizeText[];
extern const txt_cmd_s Route36NationalParkGateOfficer1HeresThePrizeText[];
