#pragma once
//// EVENTS
extern const struct MapScripts Route45_MapScripts;
extern const struct MapEvents Route45_MapEvents;

//// CODE

extern const struct TrainerObj TrainerBlackbeltKenji;
bool TrainerBlackbeltKenji_Script(script_s* s);
bool Route45AskNumber1M(script_s* s);
bool Route45AskNumber2M(script_s* s);
bool Route45RegisteredNumberM(script_s* s);
bool Route45NumberAcceptedM(script_s* s);
bool Route45NumberDeclinedM(script_s* s);
bool Route45PhoneFullM(script_s* s);
bool Route45RematchM(script_s* s);
bool Route45GiftM(script_s* s);
bool Route45PackFullM(script_s* s);
bool HikerParryHasIron(script_s* s);
bool Route45RematchGiftM(script_s* s);
extern const struct TrainerObj TrainerHikerErik;
bool TrainerHikerErik_Script(script_s* s);
extern const struct TrainerObj TrainerHikerMichael;
bool TrainerHikerMichael_Script(script_s* s);
extern const struct TrainerObj TrainerHikerParry;
bool TrainerHikerParry_Script(script_s* s);
extern const struct TrainerObj TrainerHikerTimothy;
bool TrainerHikerTimothy_Script(script_s* s);
extern const struct TrainerObj TrainerCooltrainermRyan;
bool TrainerCooltrainermRyan_Script(script_s* s);
extern const struct TrainerObj TrainerCooltrainerfKelly;
bool TrainerCooltrainerfKelly_Script(script_s* s);
bool TrainerCamperQuentin(script_s* s);
bool Route45DummyScript(script_s* s);
bool Route45Sign(script_s* s);
bool Route45FruitTree(script_s* s);
extern const struct ItemBall Route45Nugget;
extern const struct ItemBall Route45Revive;
extern const struct ItemBall Route45Elixer;
extern const struct ItemBall Route45MaxPotion;
extern const struct HiddenItem Route45HiddenPpUp;
extern const txt_cmd_s HikerErikSeenText[];
extern const txt_cmd_s HikerErikBeatenText[];
extern const txt_cmd_s HikerErikAfterBattleText[];
extern const txt_cmd_s HikerMichaelSeenText[];
extern const txt_cmd_s HikerMichaelBeatenText[];
extern const txt_cmd_s HikerMichaelAfterBattleText[];
extern const txt_cmd_s HikerParry3SeenText[];
extern const txt_cmd_s HikerParry3BeatenText[];
extern const txt_cmd_s HikerParryAfterBattleText[];
extern const txt_cmd_s HikerTimothySeenText[];
extern const txt_cmd_s HikerTimothyBeatenText[];
extern const txt_cmd_s HikerTimothyAfterBattleText[];
extern const txt_cmd_s HikerParryGivesIronText[];
extern const txt_cmd_s BlackbeltKenji3SeenText[];
extern const txt_cmd_s BlackbeltKenji3BeatenText[];
extern const txt_cmd_s BlackbeltKenjiAfterBattleText[];
extern const txt_cmd_s BlackbeltKenjiMorningText[];
extern const txt_cmd_s BlackbeltKenjiNightText[];
extern const txt_cmd_s CooltrainermRyanSeenText[];
extern const txt_cmd_s CooltrainermRyanBeatenText[];
extern const txt_cmd_s CooltrainermRyanAfterBattleText[];
extern const txt_cmd_s CooltrainerfKellySeenText[];
extern const txt_cmd_s CooltrainerfKellyBeatenText[];
extern const txt_cmd_s CooltrainerfKellyAfterBattleText[];
extern const txt_cmd_s Route45DummyText[];
extern const txt_cmd_s CamperQuentinSeenText[];
extern const txt_cmd_s CamperQuentinBeatenText[];
extern const txt_cmd_s CamperQuentinAfterBattleText[];
extern const txt_cmd_s Route45SignText[];
