#pragma once
//// EVENTS
extern const struct MapScripts TeamRocketBaseB2F_MapScripts;
extern const struct MapEvents TeamRocketBaseB2F_MapEvents;

//// CODE

bool TeamRocketBaseB2F_MapScripts_DummyScene0(script_s* s);
bool TeamRocketBaseB2F_MapScripts_DummyScene1(script_s* s);
bool TeamRocketBaseB2F_MapScripts_DummyScene2(script_s* s);
bool TeamRocketBaseB2F_MapScripts_DummyScene3(script_s* s);
bool TeamRocketBaseB2F_MapScripts_TransmitterDoorCallback(script_s* s);
bool RocketBaseBossFLeft(script_s* s);
bool RocketBaseBossFRight(script_s* s);
bool RocketBaseBossFScript(script_s* s);
bool RocketBaseCantLeaveScript(script_s* s);
bool RocketBaseLancesSideScript(script_s* s);
bool LanceHealsScript1(script_s* s);
bool LanceHealsScript2(script_s* s);
bool LanceHealsCommon(script_s* s);
extern const struct TrainerObj TrainerGruntM17;
bool TrainerGruntM17_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM18;
bool TrainerGruntM18_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM19;
bool TrainerGruntM19_Script(script_s* s);
bool RocketElectrode1(script_s* s);
bool RocketElectrode2(script_s* s);
bool RocketElectrode3(script_s* s);
bool TeamRocketBaseB2FReloadMap(script_s* s);
bool RocketBaseElectrodeScript(script_s* s);
extern const struct ConditionalEvent TeamRocketBaseB2FLockedDoor;
bool TeamRocketBaseB2FLockedDoor_Script(script_s* s);
bool TeamRocketBaseB2FTransmitterScript(script_s* s);
extern const struct ItemBall TeamRocketBaseB2FTMThief;
extern const struct HiddenItem TeamRocketBaseB2FHiddenFullHeal;
extern const uint8_t RocketBaseLanceLeavesAfterHealMovement[];
extern const uint8_t RocketBaseLanceLeavesAfterHealRightMovement[];
extern const uint8_t RocketBasePlayerApproachesBossFMovement[];
extern const uint8_t RocketBaseBossFApproachesPlayerMovement[];
extern const uint8_t RocketBaseGruntApproachesPlayerMovement[];
extern const uint8_t RocketBaseDragoniteAttacksMovement[];
extern const uint8_t RocketBaseBossFHitMovement[];
extern const uint8_t RocketBaseBossFFacesPlayerMovement[];
extern const uint8_t RocketBaseLanceApproachesBossFMovement[];
extern const uint8_t RocketBaseBossFBattlesPlayerMovement[];
extern const uint8_t RocketBaseGruntBattlesLanceMovement[];
extern const uint8_t RocketBaseGruntProtectsBossFMovement[];
extern const uint8_t RocketBaseLanceChecksPlayerMovement[];
extern const uint8_t RocketBaseLanceApproachesMachineMovement[];
extern const uint8_t RocketBaseLancePacesMovement[];
extern const uint8_t RocketBaseLanceApproachesElectrodesMovement[];
extern const uint8_t RocketBasePlayerCantLeaveElectrodesMovement[];
extern const uint8_t RocketBasePlayerCantGoRightMovement[];
extern const uint8_t RocketBaseLanceLeavesElectrodesMovement[];
extern const uint8_t RocketBaseLanceLeavesBaseMovement[];
extern const uint8_t RocketBasePlayerLeavesElectrodesMovement1[];
extern const uint8_t RocketBasePlayerLeavesElectrodesMovement2[];
extern const uint8_t RocketBasePlayerLeavesElectrodesMovement3[];
extern const txt_cmd_s RocketBaseExecutiveFHoldItText[];
extern const txt_cmd_s RocketBaseBossFThrashText[];
extern const txt_cmd_s RocketBaseLanceShareFunText[];
extern const txt_cmd_s RocketBaseBossDontMeddleText[];
extern const txt_cmd_s RocketBaseBossWinText[];
extern const txt_cmd_s RocketBaseBossRetreatText[];
extern const txt_cmd_s RocketBaseLancePostBattleText[];
extern const txt_cmd_s RocketBaseLancePowerOffText[];
extern const txt_cmd_s RockerBaseLanceElectrodeFaintText[];
extern const txt_cmd_s RocketBaseLancesSideText[];
extern const txt_cmd_s RocketBaseLanceElectrodeDoneText[];
extern const txt_cmd_s RocketBaseReceivedHM06Text[];
extern const txt_cmd_s RocketBaseLanceWhirlpoolText[];
extern const txt_cmd_s RocketBaseLanceMonMasterText[];
extern const txt_cmd_s LanceHealsText1[];
extern const txt_cmd_s LanceHealsText2[];
extern const txt_cmd_s GruntM17SeenText[];
extern const txt_cmd_s GruntM17BeatenText[];
extern const txt_cmd_s GruntM17AfterBattleText[];
extern const txt_cmd_s GruntM18SeenText[];
extern const txt_cmd_s GruntM18BeatenText[];
extern const txt_cmd_s GruntM18AfterBattleText[];
extern const txt_cmd_s GruntM19SeenText[];
extern const txt_cmd_s GruntM19BeatenText[];
extern const txt_cmd_s GruntM19AfterBattleText[];
extern const txt_cmd_s RocketBaseDoorNoPasswordText[];
extern const txt_cmd_s RocketBaseDoorKnowPasswordText[];
extern const txt_cmd_s RocketBaseB2FTransmitterText[];
extern const txt_cmd_s RocketBaseB2FDeactivateTransmitterText[];
