#pragma once
//// EVENTS
extern const struct MapScripts TeamRocketBaseB1F_MapScripts;
extern const struct MapEvents TeamRocketBaseB1F_MapEvents;

//// CODE

bool TeamRocketBaseB1F_MapScripts_DummyScene(script_s* s);
bool TeamRocketBaseB1F_MapScripts_HideSecurityGrunt(script_s* s);
bool SecurityCamera1a(script_s* s);
bool SecurityCamera1b(script_s* s);
bool SecurityCamera2a(script_s* s);
bool SecurityCamera2b(script_s* s);
bool SecurityCamera3a(script_s* s);
bool SecurityCamera3b(script_s* s);
bool SecurityCamera4(script_s* s);
bool SecurityCamera5(script_s* s);
bool NoSecurityCamera(script_s* s);
bool TrainerCameraGrunt1(script_s* s);
bool TrainerCameraGrunt2(script_s* s);
bool PlaySecurityCameraSounds(script_s* s);
bool ExplodingTrap1(script_s* s);
bool ExplodingTrap2(script_s* s);
bool ExplodingTrap3(script_s* s);
bool ExplodingTrap4(script_s* s);
bool ExplodingTrap5(script_s* s);
bool ExplodingTrap6(script_s* s);
bool ExplodingTrap7(script_s* s);
bool ExplodingTrap8(script_s* s);
bool ExplodingTrap9(script_s* s);
bool ExplodingTrap10(script_s* s);
bool ExplodingTrap11(script_s* s);
bool ExplodingTrap12(script_s* s);
bool ExplodingTrap13(script_s* s);
bool ExplodingTrap14(script_s* s);
bool ExplodingTrap15(script_s* s);
bool ExplodingTrap16(script_s* s);
bool ExplodingTrap17(script_s* s);
bool ExplodingTrap18(script_s* s);
bool ExplodingTrap19(script_s* s);
bool ExplodingTrap20(script_s* s);
bool ExplodingTrap21(script_s* s);
bool ExplodingTrap22(script_s* s);
bool VoltorbExplodingTrap(script_s* s);
bool GeodudeExplodingTrap(script_s* s);
bool KoffingExplodingTrap(script_s* s);
bool NoExplodingTrap(script_s* s);
extern const struct TrainerObj TrainerScientistJed;
bool TrainerScientistJed_Script(script_s* s);
extern const struct TrainerObj TrainerGruntM16;
bool TrainerGruntM16_Script(script_s* s);
bool TeamRocketBaseB1FSecurityCamera(script_s* s);
bool TeamRocketBaseB1FBookshelf(script_s* s);
bool TeamRocketBaseB1FSecretSwitch(script_s* s);
extern const struct ItemBall TeamRocketBaseB1FHyperPotion;
extern const struct ItemBall TeamRocketBaseB1FNugget;
extern const struct ItemBall TeamRocketBaseB1FGuardSpec;
extern const struct HiddenItem TeamRocketBaseB1FHiddenRevive;
extern const uint8_t SecurityCameraMovement1[];
extern const uint8_t SecurityCameraMovement2[];
extern const uint8_t SecurityCameraMovement3[];
extern const uint8_t SecurityCameraMovement4[];
extern const uint8_t SecurityCameraMovement5[];
extern const uint8_t SecurityCameraMovement6[];
extern const uint8_t SecurityCameraMovement7[];
extern const uint8_t SecurityCameraMovement8[];
extern const uint8_t SecurityCameraMovement9[];
extern const txt_cmd_s CameraGrunt1SeenText[];
extern const txt_cmd_s CameraGrunt1BeatenText[];
extern const txt_cmd_s CameraGrunt2SeenText[];
extern const txt_cmd_s CameraGrunt2BeatenText[];
extern const txt_cmd_s ScientistJedSeenText[];
extern const txt_cmd_s ScientistJedBeatenText[];
extern const txt_cmd_s ScientistJedAfterBattleText[];
extern const txt_cmd_s GruntM16SeenText[];
extern const txt_cmd_s GruntM16BeatenText[];
extern const txt_cmd_s GruntM16AfterBattleText[];
extern const txt_cmd_s TeamRocketBaseB1FSecurityCameraText[];
extern const txt_cmd_s TeamRocketBaseB1FSecretSwitchText[];
extern const txt_cmd_s TeamRocketBaseB1FSwitchOffText[];
