void ExecuteBGEffects(void);
void ExecuteBGEffects_Conv(void);
void QueueBGEffect(void);
bool QueueBGEffect_Conv(void);
void EndBattleBGEffect(void);
void EndBattleBGEffect_Conv(struct BattleBGEffect* bc);
void DoBattleBGEffectFunction(void);
void DoBattleBGEffectFunction_Conv(struct BattleBGEffect* bc);
// void BattleBGEffects(void);
extern void(*const BattleBGEffects[54])(struct BattleBGEffect*);
void BattleBGEffect_End(void);
void BattleBGEffect_End_Conv(struct BattleBGEffect* bc);
void BatttleBGEffects_GetNamedJumptablePointer(void);
void BattleBGEffects_AnonJumptable(void);
void BattleBGEffects_IncAnonJumptableIndex(void);
void BattleBGEffect_FlashInverted(void);
void BattleBGEffect_FlashInverted_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FlashWhite(void);
void BattleBGEffect_FlashWhite_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FlashContinue(void);
void BattleBGEffect_FlashContinue_Conv(struct BattleBGEffect* bc, const uint8_t* de);
void BattleBGEffect_WhiteHues(void);
void BattleBGEffect_WhiteHues_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BlackHues(void);
void BattleBGEffect_BlackHues_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_AlternateHues(void);
void BattleBGEffect_AlternateHues_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_CycleOBPalsGrayAndYellow(void);
void BattleBGEffect_CycleOBPalsGrayAndYellow_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_CycleMidOBPalsGrayAndYellow(void);
void BattleBGEffect_CycleMidOBPalsGrayAndYellow_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_CycleBGPals_Inverted(void);
void BattleBGEffect_CycleBGPals_Inverted_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_HideMon(void);
void BattleBGEffect_HideMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_ShowMon(void);
void BattleBGEffect_ShowMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BattlerObj_1Row(void);
void BattleBGEffect_BattlerObj_1Row_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BattlerObj_2Row(void);
void BattleBGEffect_BattlerObj_2Row_Conv(struct BattleBGEffect* bc);
void v_QueueBattleAnimation(void);
void v_QueueBattleAnimation_Conv(void);
void BattleBGEffect_RemoveMon(void);
void BattleBGEffect_RemoveMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_EnterMon(void);
void BattleBGEffect_EnterMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_ReturnMon(void);
void BattleBGEffect_ReturnMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_RunPicResizeScript(void);
void BattleBGEffect_RunPicResizeScript_Conv(struct BattleBGEffect* bc, const uint8_t* de);
void BattleBGEffect_Surf(void);
void BattleBGEffect_Surf_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Whirlpool(void);
void BattleBGEffect_Whirlpool_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_StartWater(void);
void BattleBGEffect_StartWater_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Water(void);
void BattleBGEffect_Water_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_EndWater(void);
void BattleBGEffect_EndWater_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Psychic(void);
void BattleBGEffect_Psychic_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Teleport(void);
void BattleBGEffect_Teleport_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_NightShade(void);
void BattleBGEffect_NightShade_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_DoubleTeam(void);
void BattleBGEffect_DoubleTeam_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_AcidArmor(void);
void BattleBGEffect_AcidArmor_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Withdraw(void);
void BattleBGEffect_Withdraw_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Dig(void);
void BattleBGEffect_Dig_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Tackle(void);
void BattleBGEffect_Tackle_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BodySlam(void);
void BattleBGEffect_BodySlam_Conv(struct BattleBGEffect* bc);
void Tackle_MoveForward(void);
void Tackle_MoveForward_Conv(struct BattleBGEffect* bc);
void Tackle_ReturnMove(void);
void Tackle_ReturnMove_Conv(struct BattleBGEffect* bc);
void Rollout_FillLYOverridesBackup(void);
void Rollout_FillLYOverridesBackup_Conv(uint8_t a);
void BattleBGEffect_BetaPursuit(void);
void BattleBGEffect_BetaPursuit_Conv(struct BattleBGEffect* bc);
void VitalThrow_MoveBackwards(void);
void VitalThrow_MoveBackwards_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_VitalThrow(void);
void BattleBGEffect_VitalThrow_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_WobbleMon(void);
void BattleBGEffect_WobbleMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Flail(void);
void BattleBGEffect_Flail_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_WaveDeformMon(void);
void BattleBGEffect_WaveDeformMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BounceDown(void);
void BattleBGEffect_BounceDown_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_BetaSendOutMon1(void);
void BattleBGEffect_BetaSendOutMon2(void);
void BattleBGEffect_FadeMonsToBlackRepeating(void);
void BattleBGEffect_RapidFlash(void);
void BattleBGEffect_RapidFlash_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonToLight(void);
void BattleBGEffect_FadeMonToLight_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonToBlack(void);
void BattleBGEffect_FadeMonToBlack_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonToLightRepeating(void);
void BattleBGEffect_FadeMonToLightRepeating_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonToBlackRepeating(void);
void BattleBGEffect_FadeMonToBlackRepeating_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_CycleMonLightDarkRepeating(void);
void BattleBGEffect_CycleMonLightDarkRepeating_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FlashMonRepeating(void);
void BattleBGEffect_FlashMonRepeating_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonToWhiteWaitFadeBack(void);
void BattleBGEffect_FadeMonToWhiteWaitFadeBack_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_FadeMonFromWhite(void);
void BattleBGEffect_FadeMonFromWhite_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_VibrateMon(void);
void BattleBGEffect_VibrateMon_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_WobblePlayer(void);
void BattleBGEffect_WobblePlayer_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_Rollout(void);
void BattleBGEffect_Rollout_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_ShakeScreenX(void);
void BattleBGEffect_ShakeScreenX_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_ShakeScreenY(void);
void BattleBGEffect_ShakeScreenY_Conv(struct BattleBGEffect* bc);
void BattleBGEffects_GetShakeAmount(void);
u8_flag_s BattleBGEffects_GetShakeAmount_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_WobbleScreen(void);
void BattleBGEffect_WobbleScreen_Conv(struct BattleBGEffect* bc);
void BattleBGEffect_GetNthDMGPal(void);
u8_flag_s BattleBGEffect_GetNthDMGPal_Conv(struct BattleBGEffect* bc, const uint8_t* de);
void BGEffect_RapidCyclePals(void);
void BGEffect_RapidCyclePals_Conv(struct BattleBGEffect* bc, const uint8_t* de);
void BGEffects_LoadBGPal0_OBPal1(void);
void BGEffects_LoadBGPal0_OBPal1_Conv(uint8_t a);
void BGEffects_LoadBGPal1_OBPal0(void);
void BGEffects_LoadBGPal1_OBPal0_Conv(uint8_t a);
void BattleBGEffect_GetFirstDMGPal(void);
u8_flag_s BattleBGEffect_GetFirstDMGPal_Conv(struct BattleBGEffect* bc, const uint8_t* de);
void BattleBGEffect_GetNextDMGPal(void);
u8_flag_s BattleBGEffect_GetNextDMGPal_Conv(struct BattleBGEffect* bc, const uint8_t* de, uint8_t a);
void BattleBGEffects_ClearLYOverrides(void);
void BattleBGEffects_ClearLYOverrides_Conv(void);
void BattleBGEffects_SetLYOverrides(void);
void BattleBGEffects_SetLYOverrides_Conv(uint8_t a);
void BattleBGEffect_SetLCDStatCustoms1(void);
void BattleBGEffect_SetLCDStatCustoms1_Conv(struct BattleBGEffect* bc, uint8_t a);
void BattleBGEffect_SetLCDStatCustoms2(void);
void BattleBGEffect_SetLCDStatCustoms2_Conv(struct BattleBGEffect* bc, uint8_t a);
void BattleAnim_ResetLCDStatCustom(void);
void BattleAnim_ResetLCDStatCustom_Conv(struct BattleBGEffect* bc);
void BattleBGEffects_ResetVideoHRAM(void);
void BattleBGEffects_ResetVideoHRAM_Conv(void);
void DeformScreen(void);
void DeformScreen_Conv(uint8_t d, uint8_t e);
void InitSurfWaves(void);
void InitSurfWaves_Conv(uint8_t d, uint8_t e);
void DeformWater(void);
void DeformWater_Conv(uint8_t d, uint8_t e, uint8_t a);
void BattleBGEffect_WavyScreenFX(void);
void BattleBGEffect_WavyScreenFX_Conv(void);
void BGEffect_FillLYOverridesBackup(void);
void BGEffect_FillLYOverridesBackup_Conv(uint8_t a);
void BGEffect_DisplaceLYOverridesBackup(void);
void BGEffect_DisplaceLYOverridesBackup_Conv(uint8_t a);
void BGEffect_CheckBattleTurn(void);
uint8_t BGEffect_CheckBattleTurn_Conv(struct BattleBGEffect* bc);
void BGEffect_CheckFlyDigStatus(void);
bool BGEffect_CheckFlyDigStatus_Conv(struct BattleBGEffect* bc);
void BattleBGEffects_CheckSGB(void);
bool BattleBGEffects_CheckSGB_Conv(void);
void BattleBGEffects_Sine(void);
uint8_t BattleBGEffects_Sine_Conv(uint8_t e, uint8_t d);
void BattleBGEffects_Cosine(void);
uint8_t BattleBGEffects_Cosine_Conv(uint8_t e, uint8_t d);
