#include "../constants.h"
// Footprints are 2x2 tiles each, but were stored as a 16x64-tile image
// (32 rows of 8 footprints per row).
// That means there was a row of the top two tiles for eight footprints,
// then a row of the bottom two tiles for those eight footprints.

// These macros used to help extract the first and the last two tiles, respectively.
//footprint_top    EQUS "0,                 2 * LEN_1BPP_TILE"
//footprint_bottom EQUS "2 * LEN_1BPP_TILE, 2 * LEN_1BPP_TILE"

// This has been fixed in suiCune. Now all footprints are simply loaded and
// stored contiguously.

const char* Footprints[] = {
// Entries correspond to Pokémon species

// 001-008
    "gfx/footprints/bulbasaur.png",
    "gfx/footprints/ivysaur.png",
    "gfx/footprints/venusaur.png",
    "gfx/footprints/charmander.png",
    "gfx/footprints/charmeleon.png",
    "gfx/footprints/charizard.png",
    "gfx/footprints/squirtle.png",
    "gfx/footprints/wartortle.png",
// 009-016
    "gfx/footprints/blastoise.png",
    "gfx/footprints/caterpie.png",
    "gfx/footprints/metapod.png",
    "gfx/footprints/butterfree.png",
    "gfx/footprints/weedle.png",
    "gfx/footprints/kakuna.png",
    "gfx/footprints/beedrill.png",
    "gfx/footprints/pidgey.png",
// 017-024
    "gfx/footprints/pidgeotto.png",
    "gfx/footprints/pidgeot.png",
    "gfx/footprints/rattata.png",
    "gfx/footprints/raticate.png",
    "gfx/footprints/spearow.png",
    "gfx/footprints/fearow.png",
    "gfx/footprints/ekans.png",
    "gfx/footprints/arbok.png",
// 025-032
    "gfx/footprints/pikachu.png",
    "gfx/footprints/raichu.png",
    "gfx/footprints/sandshrew.png",
    "gfx/footprints/sandslash.png",
    "gfx/footprints/nidoran_f.png",
    "gfx/footprints/nidorina.png",
    "gfx/footprints/nidoqueen.png",
    "gfx/footprints/nidoran_m.png",
// 033-040
    "gfx/footprints/nidorino.png",
    "gfx/footprints/nidoking.png",
    "gfx/footprints/clefairy.png",
    "gfx/footprints/clefable.png",
    "gfx/footprints/vulpix.png",
    "gfx/footprints/ninetales.png",
    "gfx/footprints/jigglypuff.png",
    "gfx/footprints/wigglytuff.png",
// 041-048
    "gfx/footprints/zubat.png",
    "gfx/footprints/golbat.png",
    "gfx/footprints/oddish.png",
    "gfx/footprints/gloom.png",
    "gfx/footprints/vileplume.png",
    "gfx/footprints/paras.png",
    "gfx/footprints/parasect.png",
    "gfx/footprints/venonat.png",
// 049-056 top halves
    "gfx/footprints/venomoth.png",
    "gfx/footprints/diglett.png",
    "gfx/footprints/dugtrio.png",
    "gfx/footprints/meowth.png",
    "gfx/footprints/persian.png",
    "gfx/footprints/psyduck.png",
    "gfx/footprints/golduck.png",
    "gfx/footprints/mankey.png",
// 057-064 top halves
    "gfx/footprints/primeape.png",
    "gfx/footprints/growlithe.png",
    "gfx/footprints/arcanine.png",
    "gfx/footprints/poliwag.png",
    "gfx/footprints/poliwhirl.png",
    "gfx/footprints/poliwrath.png",
    "gfx/footprints/abra.png",
    "gfx/footprints/kadabra.png",
// 065-072 top halves
    "gfx/footprints/alakazam.png",
    "gfx/footprints/machop.png",
    "gfx/footprints/machoke.png",
    "gfx/footprints/machamp.png",
    "gfx/footprints/bellsprout.png",
    "gfx/footprints/weepinbell.png",
    "gfx/footprints/victreebel.png",
    "gfx/footprints/tentacool.png",
// 073-080 top halves
    "gfx/footprints/tentacruel.png",
    "gfx/footprints/geodude.png",
    "gfx/footprints/graveler.png",
    "gfx/footprints/golem.png",
    "gfx/footprints/ponyta.png",
    "gfx/footprints/rapidash.png",
    "gfx/footprints/slowpoke.png",
    "gfx/footprints/slowbro.png",
// 081-088 top halves
    "gfx/footprints/magnemite.png",
    "gfx/footprints/magneton.png",
    "gfx/footprints/farfetch_d.png",
    "gfx/footprints/doduo.png",
    "gfx/footprints/dodrio.png",
    "gfx/footprints/seel.png",
    "gfx/footprints/dewgong.png",
    "gfx/footprints/grimer.png",
// 089-096 top halves
    "gfx/footprints/muk.png",
    "gfx/footprints/shellder.png",
    "gfx/footprints/cloyster.png",
    "gfx/footprints/gastly.png",
    "gfx/footprints/haunter.png",
    "gfx/footprints/gengar.png",
    "gfx/footprints/onix.png",
    "gfx/footprints/drowzee.png",
// 097-104 top halves
    "gfx/footprints/hypno.png",
    "gfx/footprints/krabby.png",
    "gfx/footprints/kingler.png",
    "gfx/footprints/voltorb.png",
    "gfx/footprints/electrode.png",
    "gfx/footprints/exeggcute.png",
    "gfx/footprints/exeggutor.png",
    "gfx/footprints/cubone.png",
// 105-112 top halves
    "gfx/footprints/marowak.png",
    "gfx/footprints/hitmonlee.png",
    "gfx/footprints/hitmonchan.png",
    "gfx/footprints/lickitung.png",
    "gfx/footprints/koffing.png",
    "gfx/footprints/weezing.png",
    "gfx/footprints/rhyhorn.png",
    "gfx/footprints/rhydon.png",
// 113-120 top halves
    "gfx/footprints/chansey.png",
    "gfx/footprints/tangela.png",
    "gfx/footprints/kangaskhan.png",
    "gfx/footprints/horsea.png",
    "gfx/footprints/seadra.png",
    "gfx/footprints/goldeen.png",
    "gfx/footprints/seaking.png",
    "gfx/footprints/staryu.png",
// 121-128 top halves
    "gfx/footprints/starmie.png",
    "gfx/footprints/mr__mime.png",
    "gfx/footprints/scyther.png",
    "gfx/footprints/jynx.png",
    "gfx/footprints/electabuzz.png",
    "gfx/footprints/magmar.png",
    "gfx/footprints/pinsir.png",
    "gfx/footprints/tauros.png",
// 129-136 top halves
    "gfx/footprints/magikarp.png",
    "gfx/footprints/gyarados.png",
    "gfx/footprints/lapras.png",
    "gfx/footprints/ditto.png",
    "gfx/footprints/eevee.png",
    "gfx/footprints/vaporeon.png",
    "gfx/footprints/jolteon.png",
    "gfx/footprints/flareon.png",
// 137-144 top halves
    "gfx/footprints/porygon.png",
    "gfx/footprints/omanyte.png",
    "gfx/footprints/omastar.png",
    "gfx/footprints/kabuto.png",
    "gfx/footprints/kabutops.png",
    "gfx/footprints/aerodactyl.png",
    "gfx/footprints/snorlax.png",
    "gfx/footprints/articuno.png",
// 145-152 top halves
    "gfx/footprints/zapdos.png",
    "gfx/footprints/moltres.png",
    "gfx/footprints/dratini.png",
    "gfx/footprints/dragonair.png",
    "gfx/footprints/dragonite.png",
    "gfx/footprints/mewtwo.png",
    "gfx/footprints/mew.png",
    "gfx/footprints/chikorita.png",
// 153-160 top halves
    "gfx/footprints/bayleef.png",
    "gfx/footprints/meganium.png",
    "gfx/footprints/cyndaquil.png",
    "gfx/footprints/quilava.png",
    "gfx/footprints/typhlosion.png",
    "gfx/footprints/totodile.png",
    "gfx/footprints/croconaw.png",
    "gfx/footprints/feraligatr.png",
// 161-168 top halves
    "gfx/footprints/sentret.png",
    "gfx/footprints/furret.png",
    "gfx/footprints/hoothoot.png",
    "gfx/footprints/noctowl.png",
    "gfx/footprints/ledyba.png",
    "gfx/footprints/ledian.png",
    "gfx/footprints/spinarak.png",
    "gfx/footprints/ariados.png",
// 169-176 top halves
    "gfx/footprints/crobat.png",
    "gfx/footprints/chinchou.png",
    "gfx/footprints/lanturn.png",
    "gfx/footprints/pichu.png",
    "gfx/footprints/cleffa.png",
    "gfx/footprints/igglybuff.png",
    "gfx/footprints/togepi.png",
    "gfx/footprints/togetic.png",
// 177-184 top halves
    "gfx/footprints/natu.png",
    "gfx/footprints/xatu.png",
    "gfx/footprints/mareep.png",
    "gfx/footprints/flaaffy.png",
    "gfx/footprints/ampharos.png",
    "gfx/footprints/bellossom.png",
    "gfx/footprints/marill.png",
    "gfx/footprints/azumarill.png",
// 185-192 top halves
    "gfx/footprints/sudowoodo.png",
    "gfx/footprints/politoed.png",
    "gfx/footprints/hoppip.png",
    "gfx/footprints/skiploom.png",
    "gfx/footprints/jumpluff.png",
    "gfx/footprints/aipom.png",
    "gfx/footprints/sunkern.png",
    "gfx/footprints/sunflora.png",
// 193-200 top halves
    "gfx/footprints/yanma.png",
    "gfx/footprints/wooper.png",
    "gfx/footprints/quagsire.png",
    "gfx/footprints/espeon.png",
    "gfx/footprints/umbreon.png",
    "gfx/footprints/murkrow.png",
    "gfx/footprints/slowking.png",
    "gfx/footprints/misdreavus.png",
// 201-208 top halves
    "gfx/footprints/unown.png",
    "gfx/footprints/wobbuffet.png",
    "gfx/footprints/girafarig.png",
    "gfx/footprints/pineco.png",
    "gfx/footprints/forretress.png",
    "gfx/footprints/dunsparce.png",
    "gfx/footprints/gligar.png",
    "gfx/footprints/steelix.png",
// 209-216 top halves
    "gfx/footprints/snubbull.png",
    "gfx/footprints/granbull.png",
    "gfx/footprints/qwilfish.png",
    "gfx/footprints/scizor.png",
    "gfx/footprints/shuckle.png",
    "gfx/footprints/heracross.png",
    "gfx/footprints/sneasel.png",
    "gfx/footprints/teddiursa.png",
// 217-224 top halves
    "gfx/footprints/ursaring.png",
    "gfx/footprints/slugma.png",
    "gfx/footprints/magcargo.png",
    "gfx/footprints/swinub.png",
    "gfx/footprints/piloswine.png",
    "gfx/footprints/corsola.png",
    "gfx/footprints/remoraid.png",
    "gfx/footprints/octillery.png",
// 225-232 top halves
    "gfx/footprints/delibird.png",
    "gfx/footprints/mantine.png",
    "gfx/footprints/skarmory.png",
    "gfx/footprints/houndour.png",
    "gfx/footprints/houndoom.png",
    "gfx/footprints/kingdra.png",
    "gfx/footprints/phanpy.png",
    "gfx/footprints/donphan.png",
// 233-240 top halves
    "gfx/footprints/porygon2.png",
    "gfx/footprints/stantler.png",
    "gfx/footprints/smeargle.png",
    "gfx/footprints/tyrogue.png",
    "gfx/footprints/hitmontop.png",
    "gfx/footprints/smoochum.png",
    "gfx/footprints/elekid.png",
    "gfx/footprints/magby.png",
// 241-248 top halves
    "gfx/footprints/miltank.png",
    "gfx/footprints/blissey.png",
    "gfx/footprints/raikou.png",
    "gfx/footprints/entei.png",
    "gfx/footprints/suicune.png",
    "gfx/footprints/larvitar.png",
    "gfx/footprints/pupitar.png",
    "gfx/footprints/tyranitar.png",
// 249-256 top halves
    "gfx/footprints/lugia.png",
    "gfx/footprints/ho_oh.png",
    "gfx/footprints/celebi.png",
    "gfx/footprints/252.png",
    "gfx/footprints/253.png",
    "gfx/footprints/254.png",
    "gfx/footprints/255.png",
    "gfx/footprints/256.png",
};
static_assert(lengthof(Footprints) == 0x100, "");
