void PokeGear(void);
// void PokeGear_InitTilemap(void);
// void Pokegear_LoadGFX(void);
//void FastShipGFX(void);
// void InitPokegearModeIndicatorArrow(void);
void AnimatePokegearModeIndicatorArrow(struct SpriteAnim* bc);
// uint8_t TownMap_GetCurrentLandmark(void);
// void TownMap_InitCursorAndPlayerIconPositions(void);
// void Pokegear_InitJumptableIndices(void);
// void InitPokegearTilemap(void);
// void InitPokegearTilemap_UpdateBGMap(void);
// void InitPokegearTilemap_PlacePhoneBars(void);
// void Pokegear_FinishTilemap(void);
void PokegearJumptable(void);
// void PokegearClock_Init(void);
// void PokegearClock_Joypad(void);
// void Pokegear_UpdateClock(void);
// void PokegearMap_CheckRegion(void);
// void PokegearMap_Init(void);
// void PokegearMap_KantoMap(void);
// void PokegearMap_JohtoMap(void);
// void PokegearMap_ContinueMap(u8_pair_s de);
// void PokegearMap_InitPlayerIcon(uint8_t landmark);
// struct SpriteAnim* PokegearMap_InitCursor(uint8_t landmark);
// void PokegearMap_UpdateLandmarkName(uint8_t landmark);
// void PokegearMap_UpdateCursorPosition(struct SpriteAnim* bc, uint8_t landmark);
// u8_pair_s TownMap_GetKantoLandmarkLimits(void);
// void PokegearRadio_Init(void);
// void PokegearRadio_Joypad(void);
// void PokegearPhone_Init(void);
// void PokegearPhone_Joypad(void);
// void PokegearPhone_MakePhoneCall(void);
// void PokegearPhone_FinishPhoneCall(void);
// void PokegearPhone_GetDPad(void);
// void PokegearPhone_UpdateCursor(void);
// void PokegearPhone_UpdateDisplayList(void);
// void PokegearPhone_DeletePhoneNumber(void);
bool PokegearPhoneContactSubmenu(void);
void GetAMPMHours(void);
// void Pokegear_SwitchPage(uint8_t c, uint8_t b);
void ExitPokegearRadio_HandleMusic(void);
void DeleteSpriteAnimStruct2ToEnd(void);
// void Pokegear_LoadTilemapRLE(const char* path);
extern const txt_cmd_s PokegearAskWhoCallText[];
extern const txt_cmd_s PokegearPressButtonText[];
extern const txt_cmd_s PokegearAskDeleteText[];
// void PokegearSpritesGFX(void);
// void RadioTilemapRLE(void);
// void PhoneTilemapRLE(void);
// void ClockTilemapRLE(void);
// void v_UpdateRadioStation(void);
void AnimateTuningKnob(struct SpriteAnim* bc);
// void UpdateRadioStation(void);
void LoadPokegearRadioChannelPointer(void);
// void RadioChannels(void);
// const char* LoadStation_OaksPokemonTalk(void);
// const char* LoadStation_PokedexShow(void);
// const char* LoadStation_PokemonMusic(void);
// const char* LoadStation_LuckyChannel(void);
// const char* LoadStation_BuenasPassword(void);
// extern const char BuenasPasswordName[];
// extern const char NotBuenasPasswordName[];
// const char* LoadStation_UnownRadio(void);
// const char* LoadStation_PlacesAndPeople(void);
// const char* LoadStation_LetsAllSing(void);
// const char* LoadStation_RocketRadio(void);
// const char* LoadStation_PokeFluteRadio(void);
// const char* LoadStation_EvolutionRadio(void);
void DummyLoadStation(void);
void RadioMusicRestartDE(uint16_t de);
void RadioMusicRestartPokemonChannel(void);
// void Radio_BackUpFarCallParams(void (*hl)(void));
void NoRadioStation(void);
void NoRadioMusic(void);
void NoRadioName(void);
// extern const char OaksPKMNTalkName[];
// extern const char PokedexShowName[];
// extern const char PokemonMusicName[];
// extern const char LuckyChannelName[];
// extern const char UnownStationName[];
// extern const char PlacesAndPeopleName[];
// extern const char LetsAllSingName[];
// extern const char PokeFluteStationName[];
void v_TownMap(void);
void PlayRadio(uint8_t e);
// extern const char* (*const PlayRadioStationPointers[])(void);
// const char* LoadStation_PokemonChannel(void);
void PokegearMap(uint8_t e);
uint8_t v_FlyMap(void);
void TownMapBubble(void);
void GetMapCursorCoordinates(void);
bool CheckIfVisitedFlypoint(uint8_t fp);
uint8_t HasVisitedSpawn(uint8_t c);
void Pokegear_DummyFunction(void);
void FlyMap(void);
void Pokedex_GetArea(uint8_t e, species_t species);
// void TownMapBGUpdate(uint16_t hl);
// void FillJohtoMap(void);
// void FillKantoMap(void);
// void FillTownMap(const uint8_t* map);
// void TownMapPals(void);
// struct SpriteAnim* TownMapMon(void);
// struct SpriteAnim* TownMapPlayerIcon(uint8_t location);
void LoadTownMapGFX(void);
// extern const char JohtoMap[];
// extern const char KantoMap[];
// extern const char PokedexNestIconGFX[];
// extern const char FlyMapLabelBorderGFX[];
uint8_t EntireFlyMap(void);
//#include "gfx/pokegear/fast_ship.2bpp"
//#include "gfx/pokegear/pokegear_sprites.2bpp.lz"
//#include "gfx/pokegear/radio.tilemap.rle"
//#include "gfx/pokegear/phone.tilemap.rle"
//#include "gfx/pokegear/clock.tilemap.rle"
//#include "data/maps/flypoints.h"
//#include "gfx/pokegear/town_map_palette_map.h"
//#include "gfx/pokegear/johto.bin"
//#include "gfx/pokegear/kanto.bin"
//#include "gfx/pokegear/dexmap_nest_icon.2bpp"
//#include "gfx/pokegear/flymap_label_border.1bpp"
