void PlayRadioShow(void);
void PlayRadioShow_Conv(void);
void RadioJumptable(void);
void PrintRadioLine(void);
void PrintRadioLine_Conv(uint8_t a);
void ReplacePeriodsWithSpaces(void);
void RadioScroll(void);
void RadioScroll_Conv(void);
void OaksPKMNTalk1(void);
void OaksPKMNTalk2(void);
void OaksPKMNTalk3(void);
void OaksPKMNTalk4(void);
void OaksPKMNTalk5(void);
void OaksPKMNTalk6(void);
extern const txt_cmd_s OPT_IntroText1[];
extern const txt_cmd_s OPT_IntroText2[];
extern const txt_cmd_s OPT_IntroText3[];
extern const txt_cmd_s OPT_OakText1[];
extern const txt_cmd_s OPT_OakText2[];
extern const txt_cmd_s OPT_OakText3[];
void OaksPKMNTalk7(void);
extern const txt_cmd_s OPT_MaryText1[];
void OaksPKMNTalk8(void);
void OaksPKMNTalk9(void);
void OaksPKMNTalk10(void);
extern const txt_cmd_s OPT_PokemonChannelText[];
extern const txt_cmd_s OPT_RestartText[];
void OaksPKMNTalk11(void);
void OaksPKMNTalk12(void);
void OaksPKMNTalk13(void);
void OaksPKMNTalk14(void);
void PlaceRadioString(void);
void PlaceRadioString_Conv(tile_t* hl, uint8_t* de, uint8_t line);
void CopyBottomLineToTopLine(void);
void ClearBottomLine(void);
void PokedexShow_GetDexEntryBank(void);
void PokedexShow1(void);
void PokedexShow2(void);
void PokedexShow3(void);
void PokedexShow4(void);
void PokedexShow5(void);
void PokedexShow6(void);
void PokedexShow7(void);
void PokedexShow8(void);
void CopyDexEntry(void);
void CopyDexEntry_Conv(void);
void CopyDexEntryPart1(void);
uint8_t* CopyDexEntryPart1_Conv(void);
void CopyDexEntryPart2(void);
uint8_t* CopyDexEntryPart2_Conv(void);
extern const txt_cmd_s PokedexShowText[];
void BenMonMusic1(void);
void BenMonMusic2(void);
void BenMonMusic3(void);
void FernMonMusic1(void);
void FernMonMusic2(void);
void BenFernMusic4(void);
void BenFernMusic5(void);
void BenFernMusic6(void);
void BenFernMusic7(void);
void StartPokemonMusicChannel(void);
extern const txt_cmd_s BenIntroText1[];
extern const txt_cmd_s BenIntroText2[];
extern const txt_cmd_s BenIntroText3[];
extern const txt_cmd_s FernIntroText1[];
extern const txt_cmd_s FernIntroText2[];
extern const txt_cmd_s BenFernText1[];
extern const txt_cmd_s BenFernText2A[];
extern const txt_cmd_s BenFernText2B[];
extern const txt_cmd_s BenFernText3A[];
extern const txt_cmd_s BenFernText3B[];
void LuckyNumberShow1(void);
void LuckyNumberShow2(void);
void LuckyNumberShow3(void);
void LuckyNumberShow4(void);
void LuckyNumberShow5(void);
void LuckyNumberShow6(void);
void LuckyNumberShow7(void);
void LuckyNumberShow8(void);
void LuckyNumberShow9(void);
void LuckyNumberShow10(void);
void LuckyNumberShow11(void);
void LuckyNumberShow12(void);
void LuckyNumberShow13(void);
void LuckyNumberShow14(void);
void LuckyNumberShow15(void);
extern const txt_cmd_s LC_Text1[];
extern const txt_cmd_s LC_Text2[];
extern const txt_cmd_s LC_Text3[];
extern const txt_cmd_s LC_Text4[];
extern const txt_cmd_s LC_Text5[];
extern const txt_cmd_s LC_Text6[];
extern const txt_cmd_s LC_Text7[];
extern const txt_cmd_s LC_Text8[];
extern const txt_cmd_s LC_Text9[];
extern const txt_cmd_s LC_Text10[];
extern const txt_cmd_s LC_Text11[];
extern const txt_cmd_s LC_DragText1[];
extern const txt_cmd_s LC_DragText2[];
void PeoplePlaces1(void);
void PeoplePlaces2(void);
void PeoplePlaces3(void);
extern const txt_cmd_s PnP_Text1[];
extern const txt_cmd_s PnP_Text2[];
extern const txt_cmd_s PnP_Text3[];
void PeoplePlaces4(void);
extern const txt_cmd_s PnP_Text4[];
void PeoplePlaces5(void);
extern const txt_cmd_s PnP_CuteText[];
extern const txt_cmd_s PnP_LazyText[];
extern const txt_cmd_s PnP_HappyText[];
extern const txt_cmd_s PnP_NoisyText[];
extern const txt_cmd_s PnP_PrecociousText[];
extern const txt_cmd_s PnP_BoldText[];
extern const txt_cmd_s PnP_PickyText[];
extern const txt_cmd_s PnP_SortOfOKText[];
extern const txt_cmd_s PnP_SoSoText[];
extern const txt_cmd_s PnP_GreatText[];
extern const txt_cmd_s PnP_MyTypeText[];
extern const txt_cmd_s PnP_CoolText[];
extern const txt_cmd_s PnP_InspiringText[];
extern const txt_cmd_s PnP_WeirdText[];
extern const txt_cmd_s PnP_RightForMeText[];
extern const txt_cmd_s PnP_OddText[];
void PeoplePlaces6(void);
extern const txt_cmd_s PnP_Text5[];
void PeoplePlaces7(void);
void RocketRadio1(void);
void RocketRadio2(void);
void RocketRadio3(void);
void RocketRadio4(void);
void RocketRadio5(void);
void RocketRadio6(void);
void RocketRadio7(void);
void RocketRadio8(void);
void RocketRadio9(void);
void RocketRadio10(void);
extern const txt_cmd_s RocketRadioText1[];
extern const txt_cmd_s RocketRadioText2[];
extern const txt_cmd_s RocketRadioText3[];
extern const txt_cmd_s RocketRadioText4[];
extern const txt_cmd_s RocketRadioText5[];
extern const txt_cmd_s RocketRadioText6[];
extern const txt_cmd_s RocketRadioText7[];
extern const txt_cmd_s RocketRadioText8[];
extern const txt_cmd_s RocketRadioText9[];
extern const txt_cmd_s RocketRadioText10[];
void PokeFluteRadio(void);
void UnownRadio(void);
void EvolutionRadio(void);
void BuenasPassword1(void);
void BuenasPassword2(void);
void BuenasPassword3(void);
void BuenasPassword4(void);
void GetBuenasPassword(void);
uint8_t* GetBuenasPassword_Conv(uint8_t c);
void BuenasPassword5(void);
void BuenasPassword6(void);
void BuenasPassword7(void);
void BuenasPasswordAfterMidnight(const txt_cmd_s* hl);
void BuenasPassword8(void);
void BuenasPassword9(void);
void BuenasPassword10(void);
void BuenasPassword11(void);
void BuenasPassword12(void);
void BuenasPassword13(void);
void BuenasPassword14(void);
void BuenasPassword15(void);
void BuenasPassword16(void);
void BuenasPassword17(void);
void BuenasPassword18(void);
void BuenasPassword19(void);
void BuenasPassword20(void);
void BuenasPassword21(void);
bool BuenasPasswordCheckTime(void);
extern const char BuenasPasswordChannelName[];
extern const txt_cmd_s BuenaRadioText1[];
extern const txt_cmd_s BuenaRadioText2[];
extern const txt_cmd_s BuenaRadioText3[];
extern const txt_cmd_s BuenaRadioText4[];
extern const txt_cmd_s BuenaRadioText5[];
extern const txt_cmd_s BuenaRadioText6[];
extern const txt_cmd_s BuenaRadioText7[];
extern const txt_cmd_s BuenaRadioMidnightText1[];
extern const txt_cmd_s BuenaRadioMidnightText2[];
extern const txt_cmd_s BuenaRadioMidnightText3[];
extern const txt_cmd_s BuenaRadioMidnightText4[];
extern const txt_cmd_s BuenaRadioMidnightText5[];
extern const txt_cmd_s BuenaRadioMidnightText6[];
extern const txt_cmd_s BuenaRadioMidnightText7[];
extern const txt_cmd_s BuenaRadioMidnightText8[];
extern const txt_cmd_s BuenaRadioMidnightText9[];
extern const txt_cmd_s BuenaRadioMidnightText10[];
extern const txt_cmd_s BuenaOffTheAirText[];
void CopyRadioTextToRAM(void);
void CopyRadioTextToRAM_Conv(const struct TextCmd* hl);
void StartRadioStation(void);
void StartRadioStation_Conv(void);
void NextRadioLine(void);
void NextRadioLine_Conv(const struct TextCmd* hl, uint8_t station);
//#include "data/radio/oaks_pkmn_talk_routes.h"
//#include "data/radio/pnp_hidden_people.h"
//#include "data/radio/pnp_places.h"
//#include "data/radio/buenas_passwords.h"
//#include "data/radio/channel_music.h"
