bool v_ReceiveItem(item_pocket_u* pocket, item_t a, uint8_t count);
bool v_TossItem(item_pocket_u* pocket, item_t item, uint8_t count);
bool v_CheckItem(item_pocket_u* hl, item_t item);
void DoesHLEqualNumItems(void);
uint8_t GetPocketCapacity(item_quantity_pocket_s* pocket);
bool PutItemInPocket(item_quantity_pocket_s* pocket, item_t item, uint8_t count);
bool RemoveItemFromPocket(item_quantity_pocket_s* hl, item_t item, item_t count);
bool CheckTheItem(item_quantity_pocket_s* pocket, item_t item);
bool ReceiveKeyItem(item_t item);
bool TossKeyItem(item_t item, uint8_t index);
bool CheckKeyItems(item_t c);
bool ReceiveTMHM(uint8_t id, uint8_t count);
bool TossTMHM(uint8_t tmhm, uint8_t count);
bool CheckTMHM(uint8_t c);
uint8_t GetTMHMNumber(item_t c);
item_t GetNumberedTMHM(uint8_t tmhm);
bool v_CheckTossableItem(item_t item);
bool CheckSelectableItem(item_t item);
uint8_t CheckItemPocket(item_t item);
uint8_t CheckItemContext(item_t item);
uint8_t CheckItemMenu(item_t item);
void GetItemAttr(void);
void ItemAttr_ReturnCarry(void);
uint16_t GetItemPrice(item_t item);
