void v_ReceiveItem(void);
bool v_ReceiveItem_Conv(item_t* hl, item_t a, uint8_t count);
void v_TossItem(void);
void v_CheckItem(void);
bool v_CheckItem_Conv(item_t item, item_t* hl);
void DoesHLEqualNumItems(void);
bool DoesHLEqualNumItems_Conv(uint16_t hl);
void GetPocketCapacity(void);
uint8_t GetPocketCapacity_Conv(item_t* pocket);
void PutItemInPocket(void);
bool PutItemInPocket_Conv(item_t* pocket, uint8_t* pocketQuantity, item_t item, uint8_t count);
void RemoveItemFromPocket(void);
void CheckTheItem(void);
bool CheckTheItem_Conv(item_t item, item_t* hl);
void ReceiveKeyItem(void);
bool ReceiveKeyItem_Conv(item_t item);
void TossKeyItem(void);
void CheckKeyItems(void);
bool CheckKeyItems_Conv(uint8_t c);
void ReceiveTMHM(void);
bool ReceiveTMHM_Conv(uint8_t id, uint8_t count);
void TossTMHM(void);
void CheckTMHM(void);
bool CheckTMHM_Conv(uint8_t c);
void GetTMHMNumber(void);
uint8_t GetTMHMNumber_Conv(item_t c);
void GetNumberedTMHM(void);
void v_CheckTossableItem(void);
bool v_CheckTossableItem_Conv(item_t item);
void CheckSelectableItem(void);
void CheckItemPocket(void);
uint8_t CheckItemPocket_Conv(item_t item);
void CheckItemContext(void);
uint8_t CheckItemContext_Conv(item_t item);
void CheckItemMenu(void);
uint8_t CheckItemMenu_Conv(item_t item);
void GetItemAttr(void);
void ItemAttr_ReturnCarry(void);
void GetItemPrice(void);
