void Pack(void);
void Pack_RunJumptable(void);
void MenuHeader_UsableKeyItem(void);
void Jumptable_UseGiveTossRegisterQuit(void);
void MenuHeader_UsableItem(void);
void Jumptable_UseGiveTossQuit(void);
void MenuHeader_UnusableItem(void);
void Jumptable_UseQuit(void);
void MenuHeader_UnusableKeyItem(void);
void Jumptable_UseRegisterQuit(void);
void MenuHeader_HoldableKeyItem(void);
void Jumptable_GiveTossRegisterQuit(void);
void MenuHeader_HoldableItem(void);
void Jumptable_GiveTossQuit(void);
void UseItem(void);
void TossMenu(void);
void ResetPocketCursorPositions(void);
void RegisterItem(void);
void GiveItem(void);
void QuitItemSubmenu(void);
void BattlePack(void);
void ItemSubmenu(void);
void TMHMSubmenu(void);
void InitPackBuffers(void);
void DepositSellInitPackBuffers(void);
void DepositSellPack(void);
void InitPocket(void);
void DepositSellTutorial_InterpretJoypad(void);
void TutorialPack(void);
void Pack_JumptableNext(void);
void Pack_GetJumptablePointer(void);
void Pack_QuitNoScript(void);
void Pack_QuitRunScript(void);
void Pack_PrintTextNoScroll(const txt_cmd_s* hl);
void WaitBGMap_DrawPackGFX(void);
void DrawPackGFX(uint8_t pocket);
extern const uint16_t PackGFXPointers[];
void Pack_InterpretJoypad(void);
bool Pack_InterpretJoypad_Conv(uint8_t b, uint8_t c);
void Pack_InitGFX(void);
void PlacePackGFX(void);
void DrawPocketName(uint8_t pocket);
void Pack_GetItemName(void);
void Pack_ClearTilemap(void);
void ClearPocketList(void);
void Pack_InitColors(void);
extern const struct MenuHeader ItemsPocketMenuHeader;
void PC_Mart_ItemsPocketMenuHeader(void);
extern const struct MenuHeader KeyItemsPocketMenuHeader;
void PC_Mart_KeyItemsPocketMenuHeader(void);
extern const struct MenuHeader BallsPocketMenuHeader;
void PC_Mart_BallsPocketMenuHeader(void);
extern const txt_cmd_s PackNoItemText[];
extern const txt_cmd_s AskThrowAwayText[];
extern const txt_cmd_s AskQuantityThrowAwayText[];
extern const txt_cmd_s ThrewAwayText[];
extern const txt_cmd_s OakThisIsntTheTimeText[];
extern const txt_cmd_s YouDontHaveAMonText[];
extern const txt_cmd_s RegisteredItemText[];
extern const txt_cmd_s CantRegisterText[];
extern const txt_cmd_s AskItemMoveText[];
extern const txt_cmd_s PackEmptyText[];
extern const txt_cmd_s YouCantUseItInABattleText[];
extern const char PackMenuGFX[];
extern const char PackGFX[];
//#include "gfx/pack/pack_menu.tilemap"
//#include "gfx/pack/pack_menu.2bpp"
//#include "gfx/pack/pack.2bpp"
