void v_SlotMachine(void);
void Slots_GetPals(void);
bool SlotsLoop(void);
void DebugPrintSlotBias(void);
void AnimateSlotReelIcons(void);
void SlotsJumptable(void);
void SlotsAction_Next(void);
void SlotsAction_Init(void);
void SlotsAction_BetAndStart(void);
void SlotsAction_WaitStart(void);
void SlotsAction_WaitReel1(void);
void SlotsAction_WaitStopReel1(void);
void SlotsAction_WaitReel2(void);
void SlotsAction_WaitStopReel2(void);
void SlotsAction_WaitReel3(void);
void SlotsAction_WaitStopReel3(void);
void SlotsAction_FlashIfWin(void);
void SlotsAction_FlashScreen(void);
void SlotsAction_GiveEarnedCoins(void);
void SlotsAction_PayoutTextAndAnim(void);
void SlotsAction_PayoutAnim(void);
void SlotsAction_RestartOrQuit(void);
void SlotsAction_Quit(void);
void Slots_LoadReelState(uint8_t* de, struct SlotReelData* bc);
bool Slots_CheckCoinCaseFull(uint16_t de);
const uint8_t* Slots_GetCurrentReelState(struct SlotReelData* bc);
uint8_t Slots_StopReel1(void);
uint8_t Slots_StopReel2(void);
uint8_t Slots_StopReel3(void);
void Slots_InitReelTiles(void);
void Slots_SpinReels(void);
void Slots_UpdateReelPositionAndOAM(struct SlotReelData* bc);
void GetUnknownSlotReelData(void);
void ReelActionJumptable(struct SlotReelData* bc);
void ReelAction_DoNothing(void);
void ReelAction_QuadrupleRate(struct SlotReelData* bc);
void ReelAction_DoubleRate(struct SlotReelData* bc);
void ReelAction_NormalRate(struct SlotReelData* bc);
void ReelAction_HalfRate(struct SlotReelData* bc);
void ReelAction_QuarterRate(struct SlotReelData* bc);
void Slots_StopReel(struct SlotReelData* bc);
void ReelAction_StopReelIgnoreJoypad(struct SlotReelData* bc);
void ReelAction_StopReel1(struct SlotReelData* bc);
void ReelAction_StopReel2(struct SlotReelData* bc);
void ReelAction_StopReel3(struct SlotReelData* bc);
void ReelAction_SetUpReel2SkipTo7(struct SlotReelData* bc);
void ReelAction_WaitReel2SkipTo7(struct SlotReelData* bc);
void ReelAction_FastSpinReel2UntilLinedUp7s(struct SlotReelData* bc);
void ReelAction_InitGolem(struct SlotReelData* bc);
void ReelAction_WaitGolem(struct SlotReelData* bc);
void ReelAction_EndGolem(struct SlotReelData* bc);
void ReelAction_InitChansey(struct SlotReelData* bc);
void ReelAction_WaitChansey(struct SlotReelData* bc);
void ReelAction_WaitEgg(struct SlotReelData* bc);
void ReelAction_DropReel(struct SlotReelData* bc);
void ReelAction_Unused(struct SlotReelData* bc);
void ReelAction_CheckDropReel(struct SlotReelData* bc);
void ReelAction_WaitDropReel(struct SlotReelData* bc);
void ReelAction_StartSlowAdvanceReel3(struct SlotReelData* bc);
void ReelAction_WaitSlowAdvanceReel3(struct SlotReelData* bc);
bool Slots_CheckMatchedFirstTwoReels(struct SlotReelData* bc);
bool Slots_CheckMatchedAllThreeReels(struct SlotReelData* bc);
void Slots_CopyReelState(const uint8_t* state);
uint8_t Slots_GetNumberOfGolems(struct SlotReelData* bc);
void Slots_InitBias(void);
void Slots_IlluminateBetLights(void);
void Slots_DeilluminateBetLights(void);
void Slots_Lights3OnOff(uint8_t b);
void Slots_Lights2OnOff(uint8_t b);
void Slots_Lights1OnOff(uint8_t b);
void Slots_TurnLightsOnOrOff(uint8_t* hl, uint8_t b);
bool Slots_AskBet(void);
bool Slots_AskPlayAgain(void);
uint16_t Slots_GetPayout(void);
void Slots_PayoutText(void);
void Slots_AnimateGolem(struct SpriteAnim* bc);
void Slots_AnimateChansey(struct SpriteAnim* bc);
void Slots_WaitSFX(void);
void Slots_PlaySFX(uint16_t sfx);
extern const uint8_t Reel1Tilemap[];
extern const uint8_t Reel2Tilemap[];
extern const uint8_t Reel3Tilemap[];
extern const char SlotsTilemap[];
extern const char Slots1LZ[];
extern const char Slots2LZ[];
extern const char Slots3LZ[];
//#include "gfx/slots/slots.tilemap"
//#include "gfx/slots/slots_1.2bpp.lz"
//#include "gfx/slots/slots_2.2bpp.lz"
//#include "gfx/slots/slots_3.2bpp.lz"
