void v_DepositPKMN(void);
void BillsPCDepositJumptable(void);
void BillsPCDepositFuncDeposit(void);
void BillsPCDepositFuncStats(void);
void BillsPCDepositFuncRelease(void);
void BillsPCDepositFuncCancel(void);
extern const struct MenuHeader BillsPCDepositMenuHeader;
void BillsPCClearThreeBoxes(void);
void v_WithdrawPKMN(void);
void BillsPC_Withdraw(void);
void v_MovePKMNWithoutMail(void);
void BillsPC_InitRAM(void);
void BillsPC_IncrementJumptableIndex(void);
void BillsPC_EndJumptableLoop(void);
void v_StatsScreenDPad(void);
u8_flag_s v_StatsScreenDPad_Conv(uint8_t* hl);
void Withdraw_UpDown(void);
u8_flag_s Withdraw_UpDown_Conv(void);
void MoveMonWithoutMail_DPad(void);
void MoveMonWithoutMail_DPad_2(void);
void BillsPC_PressUp(void);
u8_flag_s BillsPC_PressUp_Conv(void);
void BillsPC_PressDown(void);
u8_flag_s BillsPC_PressDown_Conv(uint8_t d, uint8_t e);
void BillsPC_PressLeft(void);
void BillsPC_PressRight(void);
void BillsPC_JoypadDidNothing(void);
u8_flag_s BillsPC_JoypadDidNothing_Conv(void);
void BillsPC_UpDownDidSomething(void);
u8_flag_s BillsPC_UpDownDidSomething_Conv(void);
void BillsPC_LeftRightDidSomething(void);
u8_flag_s BillsPC_LeftRightDidSomething_Conv(void);
void BillsPC_PlaceString(void);
void BillsPC_PlaceString_Conv(uint8_t* de);
void BillsPC_MoveMonWOMail_BoxNameAndArrows(void);
void BillsPC_BoxName(void);
void PCMonInfo(void);
void BillsPC_LoadMonStats(void);
void BillsPC_LoadMonStats_Conv(void);
void BillsPC_RefreshTextboxes(void);
void CopyBoxmonSpecies(void);
void BillsPC_GetSelectedPokemonSpecies(void);
species_t BillsPC_GetSelectedPokemonSpecies_Conv(void);
void BillsPC_UpdateSelectionCursor(void);
void BillsPC_UpdateInsertCursor(void);
void BillsPC_FillBox(void);
void BillsPC_CheckSpaceInDestination(void);
void BillsPC_CheckMail_PreventBlackout(void);
bool BillsPC_CheckMail_PreventBlackout_Conv(void);
void BillsPC_IsMonAnEgg(void);
bool BillsPC_IsMonAnEgg_Conv(void);
void BillsPC_StatsScreen(void);
void BillsPC_StatsScreen_Conv(void);
void StatsScreenDPad(void);
void StatsScreenDPad_Conv(void);
void BillsPC_CopyMon(void);
void BillsPC_CopyMon_Conv(void);
void DepositPokemon(void);
bool DepositPokemon_Conv(void);
void TryWithdrawPokemon(void);
void ReleasePKMN_ByePKMN(void);
void MovePKMNWitoutMail_InsertMon(void);
void CopySpeciesToTemp(void);
void CopySpeciesToTemp_Conv(const uint8_t* hl);
void CopyNicknameToTemp(void);
void CopyNicknameToTemp_Conv(const uint8_t (*hl)[MON_NAME_LENGTH]);
void CopyOTNameToTemp(void);
void CopyOTNameToTemp_Conv(const uint8_t (*hl)[NAME_LENGTH]);
void CopyMonToTemp(void);
void CopyMonToTemp_Conv(struct PartyMon* hl);
void GetBoxPointer(void);
uint32_t GetBoxPointer_Conv(uint8_t b);
void BillsPC_ApplyPalettes(uint8_t a);
void BillsPC_Jumptable(void);
void BillsPC_InitGFX(void);
extern const char PCSelectLZ[];
extern const char PCMailGFX[];
extern const char PCString_ChooseaPKMN[];
extern const char PCString_WhatsUp[];
extern const char PCString_ReleasePKMN[];
void PCString_MoveToWhere(void);
extern const char PCString_ItsYourLastPKMN[];
void PCString_TheresNoRoom(void);
extern const char PCString_NoMoreUsablePKMN[];
extern const char PCString_RemoveMail[];
extern const char PCString_ReleasedPKMN[];
extern const char PCString_Bye[];
extern const char PCString_Stored[];
void PCString_Got(void);
void PCString_Non(void);
extern const char PCString_BoxFull[];
void PCString_PartyFull(void);
extern const char PCString_NoReleasingEGGS[];
void v_ChangeBox(void);
void BillsPC_ClearTilemap(void);
void v_ChangeBox_MenuHeader(void);
void GetBoxName(void);
void BillsPC_PrintBoxCountAndCapacity(void);
void GetBoxCount(void);
void BillsPC_PrintBoxName(void);
void BillsPC_ChangeBoxSubmenu(void);
void BillsPC_PlaceChooseABoxString(void);
void BillsPC_PlaceWhatsUpString(void);
void BillsPC_PlaceEmptyBoxString_SFX(void);
void BillsPC_PlaceChangeBoxString(void);
