void v_DepositPKMN(void);
void BillsPCDepositJumptable(void);
void BillsPCDepositFuncDeposit(void);
void BillsPCDepositFuncStats(void);
void BillsPCDepositFuncRelease(void);
void BillsPCDepositFuncCancel(void);
void BillsPCDepositMenuHeader(void);
void BillsPCClearThreeBoxes(void);
void v_WithdrawPKMN(void);
void BillsPC_Withdraw(void);
void v_MovePKMNWithoutMail(void);
void BillsPC_InitRAM(void);
void BillsPC_IncrementJumptableIndex(void);
void BillsPC_EndJumptableLoop(void);
void v_StatsScreenDPad(void);
struct FlagA v_StatsScreenDPad_Conv(uint8_t* hl);
void Withdraw_UpDown(void);
void MoveMonWithoutMail_DPad(void);
void MoveMonWithoutMail_DPad_2(void);
void BillsPC_PressUp(void);
struct FlagA BillsPC_PressUp_Conv(void);
void BillsPC_PressDown(void);
struct FlagA BillsPC_PressDown_Conv(uint16_t de);
void BillsPC_PressLeft(void);
void BillsPC_PressRight(void);
void BillsPC_JoypadDidNothing(void);
struct FlagA BillsPC_JoypadDidNothing_Conv(void);
void BillsPC_UpDownDidSomething(void);
struct FlagA BillsPC_UpDownDidSomething_Conv(void);
void BillsPC_LeftRightDidSomething(void);
struct FlagA BillsPC_LeftRightDidSomething_Conv(void);
void BillsPC_PlaceString(void);
void BillsPC_MoveMonWOMail_BoxNameAndArrows(void);
void BillsPC_BoxName(void);
void PCMonInfo(void);
void BillsPC_LoadMonStats(void);
void BillsPC_LoadMonStats_Conv(void);
void BillsPC_RefreshTextboxes(void);
void CopyBoxmonSpecies(void);
void BillsPC_GetSelectedPokemonSpecies(void);
species_t BillsPC_GetSelectedPokemonSpecies_Conv(void);
void BillsPC_UpdateSelectionCursor(void);
void BillsPC_UpdateInsertCursor(void);
void BillsPC_FillBox(void);
void BillsPC_CheckSpaceInDestination(void);
void BillsPC_CheckMail_PreventBlackout(void);
void BillsPC_IsMonAnEgg(void);
void BillsPC_StatsScreen(void);
void StatsScreenDPad(void);
void StatsScreenDPad_Conv(void);
void BillsPC_CopyMon(void);
void BillsPC_CopyMon_Conv(void);
void DepositPokemon(void);
void TryWithdrawPokemon(void);
void ReleasePKMN_ByePKMN(void);
void MovePKMNWitoutMail_InsertMon(void);
void CopySpeciesToTemp(void);
void CopySpeciesToTemp_Conv(const uint8_t* hl);
void CopyNicknameToTemp(void);
void CopyNicknameToTemp_Conv(const uint8_t (*hl)[MON_NAME_LENGTH]);
void CopyOTNameToTemp(void);
void CopyOTNameToTemp_Conv(const uint8_t (*hl)[NAME_LENGTH]);
void CopyMonToTemp(void);
void CopyMonToTemp_Conv(struct PartyMon* hl);
void GetBoxPointer(void);
void BillsPC_ApplyPalettes(void);
void BillsPC_Jumptable(void);
void BillsPC_InitGFX(void);
void PCSelectLZ(void);
void PCMailGFX(void);
void PCString_ChooseaPKMN(void);
void PCString_WhatsUp(void);
void PCString_ReleasePKMN(void);
void PCString_MoveToWhere(void);
void PCString_ItsYourLastPKMN(void);
void PCString_TheresNoRoom(void);
void PCString_NoMoreUsablePKMN(void);
void PCString_RemoveMail(void);
void PCString_ReleasedPKMN(void);
void PCString_Bye(void);
void PCString_Stored(void);
void PCString_Got(void);
void PCString_Non(void);
void PCString_BoxFull(void);
void PCString_PartyFull(void);
void PCString_NoReleasingEGGS(void);
void v_ChangeBox(void);
void BillsPC_ClearTilemap(void);
void v_ChangeBox_MenuHeader(void);
void GetBoxName(void);
void BillsPC_PrintBoxCountAndCapacity(void);
void GetBoxCount(void);
void BillsPC_PrintBoxName(void);
void BillsPC_ChangeBoxSubmenu(void);
void BillsPC_PlaceChooseABoxString(void);
void BillsPC_PlaceWhatsUpString(void);
void BillsPC_PlaceEmptyBoxString_SFX(void);
void BillsPC_PlaceChangeBoxString(void);
