void CheckBreedmonCompatibility(void);
uint8_t CheckBreedmonCompatibility_Conv(void);
void DoEggStep(void);
void OverworldHatchEgg(void);
void HatchEggs(void);
void InitEggMoves(void);
void InitEggMoves_Conv(void);
void GetEggMove(void);
bool GetEggMove_Conv(const move_t* de);
void LoadEggMove(void);
void LoadEggMove_Conv(const move_t* de2);
void GetHeritableMoves(void);
const move_t* GetHeritableMoves_Conv(void);
void GetBreedmonMovePointer(void);
move_t* GetBreedmonMovePointer_Conv(void);
void GetEggFrontpic(void);
void GetHatchlingFrontpic(void);
void Hatch_UpdateFrontpicBGMapCenter(void);
void EggHatch_DoAnimFrame(void);
void EggHatch_AnimationSequence(void);
void Hatch_LoadFrontpicPal(void);
void EggHatch_CrackShell(void);
void EggHatchGFX(void);
void Hatch_InitShellFragments(void);
void Hatch_ShellFragmentLoop(void);
void DayCareMon1(void);
void DayCareMon2(void);
void DayCareMonCursor(void);
void LeftWithDayCareLadyText(void);
void LeftWithDayCareManText(void);
void DayCareMonCompatibilityText(void);
void DayCareMonPrintEmptyString(void);
//#include "gfx/evo/egg_hatch.2bpp"
