void CheckPartyFullAfterContest(void);
bool GiveANickname_YesNo(void);
extern const txt_cmd_s CaughtAskNicknameText[];
void SetCaughtData(void);
void SetCaughtData_Conv(void);
void SetBoxmonOrEggmonCaughtData(void);
void SetBoxmonOrEggmonCaughtData_Conv(struct BoxMon* boxmon);
void SetBoxMonCaughtData(void);
void SetGiftBoxMonCaughtData(uint8_t b);
void SetGiftPartyMonCaughtData(uint8_t b);
void SetGiftMonCaughtData(void);
void SetGiftMonCaughtData_Conv(struct BoxMon* hl, uint8_t b);
void SetEggMonCaughtData(void);
