void EvolvePokemon(void);
void EvolveAfterBattle(void);
void EvolveAfterBattle_MasterLoop(species_t* species);
void UpdateSpeciesNameIfNotNicknamed(void);
void CancelEvolution(void);
bool IsMonHoldingEverstone(void);
extern const txt_cmd_s CongratulationsYourPokemonText[];
extern const txt_cmd_s EvolvedIntoText[];
extern const txt_cmd_s StoppedEvolvingText[];
extern const txt_cmd_s EvolvingText[];
void LearnLevelMoves(void);
void LearnLevelMoves_Conv(struct PartyMon* mon, uint8_t level, species_t species);
void FillMoves(void);
void FillMoves_Conv(move_t* de, uint8_t* pp, species_t species, uint8_t level);
void ShiftMoves(void);
void ShiftMoves_Conv(move_t* hl);
uint8_t EvoFlagAction(uint8_t* hl, uint8_t c, uint8_t b);
void GetPreEvolution(void);
species_t GetPreEvolution_Conv(species_t species);
