void ReadPartyMonMail(void);
void ReadAnyMail(const struct MailMsg* de);
// void MailGFXPointers(void);
void LoadSurfMailGFX(const struct MailMsg* bc);
void LoadLiteBlueMailGFX(const struct MailMsg* bc);
void FinishLoadingSurfLiteBlueMailGFX(const struct MailMsg* bc, uint8_t* hl);
void LoadEonMailGFX(const struct MailMsg* bc);
void LoadLovelyMailGFX(const struct MailMsg* bc);
void LovelyEonMail_PlaceIcons(void);
void LoadMorphMailGFX(const struct MailMsg* bc);
void LoadBlueSkyMailGFX(const struct MailMsg* bc);
tile_t Mail_Place6TileRow(tile_t* hl, tile_t a);
void LoadFlowerMailGFX(const struct MailMsg* bc);
void LoadPortraitMailGFX(const struct MailMsg* bc);
void LoadMusicMailGFX(const struct MailMsg* bc);
void LoadMirageMailGFX(const struct MailMsg* bc);
uint8_t* MailGFX_GenerateMonochromeTilesColor2(uint8_t* hl, uint16_t bc);
void MailGFX_PlaceMessage(const struct MailMsg* hl);
void InvertBytes(void);
void DrawMailBorder(void);
void DrawMailBorder2(void);
void Mail_Place14TileAlternatingRow(tile_t* hl, tile_t a);
void Mail_Place16TileAlternatingRow(void);
void Mail_Place18TileAlternatingRow(tile_t* hl, tile_t a);
void Mail_PlaceAlternatingRow(tile_t* hl, tile_t a, uint8_t b);
void Mail_Place14TileAlternatingColumn(tile_t* hl, tile_t a);
void Mail_Place16TileAlternatingColumn(tile_t* hl, tile_t a);
void Mail_PlaceAlternatingColumn(tile_t* hl, tile_t a, uint8_t b);
void Mail_Draw7TileRow(void);
tile_t* Mail_Draw13TileRow(tile_t* hl, tile_t a);
tile_t* Mail_Draw16TileRow(tile_t* hl, tile_t a);
tile_t* Mail_DrawTopBottomBorder(tile_t* hl, tile_t a);
tile_t* Mail_DrawFullWidthBorder(tile_t* hl, tile_t a);
tile_t* Mail_DrawRowLoop(tile_t* hl, tile_t a, uint8_t b);
tile_t* Mail_DrawLeftRightBorder(tile_t* hl, tile_t a);
void Mail_Draw2x2Graphic(tile_t* hl, tile_t a);
tile_t Mail_Draw3x2Graphic(tile_t* hl, tile_t a);
uint8_t* LoadMailGFX_Color1(uint8_t* hl, const char* de, uint8_t start, uint8_t c);
uint8_t* LoadMailGFX_Color2(uint8_t* hl, const char* de, uint8_t start, uint8_t c);
uint8_t* LoadMailGFX_Color3(uint8_t* hl, const char* de, uint8_t start, uint8_t c);
bool ItemIsMail(item_t d);
//#include "gfx/mail.h"
//#include "data/items/mail_items.h"
