struct MailMsg LoadMailMsg(uint8_t* ptr);
bool SendMailToPC(uint8_t b);
void DeleteMailFromPC(uint8_t b);
void ReadMailMessage(uint8_t b);
void MoveMailFromPCToParty(uint8_t b);
uint8_t GetMailboxCount(void);
void CheckPokeMail(const char* message);
void GivePokeMail(const struct Pokemail* mail);
void BackupPartyMonMail(void);
void RestorePartyMonMail(void);
void DeletePartyMonMail(void);
bool IsAnyMonHoldingMail(void);
void v_PlayerMailBoxMenu(void);
uint8_t* MailboxPC_GetMailAuthor(uint8_t a);
void MailboxPC_PrintMailAuthor(const struct MenuData* data, tile_t* tile);
void MailboxPC(void);
