bool SendMailToPC(uint8_t b);
void DeleteMailFromPC(void);
void ReadMailMessage(void);
void MoveMailFromPCToParty(void);
uint8_t GetMailboxCount(void);
void CheckPokeMail(void);
void GivePokeMail(void);
void GivePokeMail_Conv(const struct Pokemail* mail);
void BackupPartyMonMail(void);
void RestorePartyMonMail(void);
void DeletePartyMonMail(void);
void IsAnyMonHoldingMail(void);
bool IsAnyMonHoldingMail_Conv(void);
void v_PlayerMailBoxMenu(void);
void InitMail(void);
bool InitMail_Conv(void);
void MailboxPC_GetMailAuthor(void);
void MailboxPC_PrintMailAuthor(void);
void MailboxPC(void);
