void HasNoItems(void);
bool HasNoItems_Conv(void);
void TossItemFromPC(void);
bool TossItemFromPC_Conv(item_pocket_s* de);
void CantUseItem(void);
extern const txt_cmd_s ItemsOakWarningText[];
void PartyMonItemName(void);
void PartyMonItemName_Conv(item_t item);
void CancelPokemonAction(void);
void PokemonActionSubmenu(void);
void SwitchPartyMons(void);
void GiveTakePartyMonItem(void);
void TryGiveItemToPartymon(void);
void GivePartyItem(void);
void TakePartyItem(void);
void GiveTakeItemMenuData(void);
void PokemonSwapItemText(void);
void PokemonHoldItemText(void);
void PokemonRemoveMailText(void);
void PokemonNotHoldingText(void);
void ItemStorageFullText(void);
void PokemonTookItemText(void);
void PokemonAskSwapItemText(void);
void ItemCantHeldText(void);
void GetPartyItemLocation(void);
void ReceiveItemFromPokemon(void);
void GiveItemToPokemon(void);
void StartMenuYesNo(void);
bool StartMenuYesNo_Conv(const struct TextCmd* hl);
void ComposeMailMessage(void);
void MonMailAction(void);
void OpenPartyStats(void);
void MonMenu_Cut(void);
void MonMenu_Fly(void);
void MonMenu_Flash(void);
void MonMenu_Strength(void);
void MonMenu_Whirlpool(void);
void MonMenu_Waterfall(void);
void MonMenu_Teleport(void);
void MonMenu_Surf(void);
void MonMenu_Dig(void);
void MonMenu_Softboiled_MilkDrink(void);
void MonMenu_Headbutt(void);
void MonMenu_RockSmash(void);
void MonMenu_SweetScent(void);
void ChooseMoveToDelete(void);
u8_flag_s ChooseMoveToDelete_Conv(void);
extern const uint8_t DeleteMoveScreen2DMenuData[];
void ManagePokemonMoves(void);
void MoveScreenLoop(void);
void MoveScreen2DMenuData(void);
void String_MoveWhere(void);
void SetUpMoveScreenBG(void);
void SetUpMoveList(void);
void PrepareToPlaceMoveData(void);
void PlaceMoveData(void);
extern const char String_MoveType_Top[];
extern const char String_MoveType_Bottom[];
extern const char String_MoveAtk[];
extern const char String_MoveNoPower[];
void PlaceMoveScreenArrows(void);
void PlaceMoveScreenLeftArrow(void);
void PlaceMoveScreenRightArrow(void);
