void DrawPlayerHP(void);
void DrawEnemyHP(void);
void DrawHP(void);
void PrintTempMonStats(void);
void GetGender(void);
struct FlagA GetGender_Conv(void);
void ListMovePP(void);
void BrokenPlacePPUnits(void);
void Unused_PlaceEnemyHPLevel(void);
void PlaceStatusString(void);
bool PlaceStatusString_Conv(uint8_t* hl, struct PartyMon* de);
// void FntString(void);
extern const char FntString[];
void CopyStatusString(void);
void CopyStatusString_Conv(uint8_t* hl, uint8_t* de);
void PlaceNonFaintStatus(void);
bool PlaceNonFaintStatus_Conv(uint8_t* hl, struct PartyMon* de);
extern const char SlpString[];
extern const char PsnString[];
extern const char BrnString[];
extern const char FrzString[];
extern const char ParString[];
void ListMoves(void);
void ListMoves_Conv(uint8_t* hl);
