void TryAddMonToParty(void);
bool TryAddMonToParty_Conv(species_t species, uint8_t level);
void GeneratePartyMonStats(void);
bool GeneratePartyMonStats_Conv(struct PartyMon* hl, species_t species, uint8_t level, uint8_t monType, uint8_t battleMode);
void FillPP(void);
void FillPP_Conv(uint8_t* de, const move_t* hl);
void AddTempmonToParty(void);
void SendGetMonIntoFromBox(void);
bool SendGetMonIntoFromBox_Conv(uint8_t param);
bool CloseSRAM_And_SetCarryFlag(void);
void RestorePPOfDepositedPokemon(uint8_t b);
void RetrieveMonFromDayCareMan(void);
bool RetrieveMonFromDayCareMan_Conv(void);
void RetrieveMonFromDayCareLady(void);
bool RetrieveMonFromDayCareLady_Conv(void);
void RetrieveBreedmon(void);
bool RetrieveBreedmon_Conv(void);
void GetLastPartyMon(void);
void DepositMonWithDayCareMan(void);
void DepositMonWithDayCareMan_Conv(uint8_t a);
void DepositMonWithDayCareLady(void);
void DepositMonWithDayCareLady_Conv(uint8_t a);
void DepositBreedmon(void);
void DepositBreedmon_Conv(uint8_t* nickname, uint8_t* ot, struct BoxMon* de, uint8_t a);
void SendMonIntoBox(void);
bool SendMonIntoBox_Conv(void);
void ShiftBoxMon(void);
void ShiftBoxMon_Conv(void);
void GiveEgg(void);
bool GiveEgg_Conv(void);
extern const char String_Egg[];
void RemoveMonFromPartyOrBox(void);
void RemoveMonFromPartyOrBox_Conv(uint8_t param);
void ComputeNPCTrademonStats(void);
void ComputeNPCTrademonStats_Conv(uint8_t curPartyMon);
void CalcMonStats(void);
void CalcMonStats_Conv(uint16_t* stats, const uint16_t* statExp, uint16_t dvs, uint8_t b);
void CalcMonStatC(void);
uint16_t CalcMonStatC_Conv(const uint16_t* statExp, uint16_t dvs, uint8_t b, uint8_t c);
void GivePoke(void);
uint8_t GivePoke_Conv(uint8_t b, const char* nickname, const char* otName);
extern const txt_cmd_s WasSentToBillsPCText[];
void InitNickname(void);
void InitNickname_Conv(uint8_t* hl);
