void TryAddMonToParty(void);
void GeneratePartyMonStats(void);
void FillPP(void);
void FillPP_Conv(uint8_t* de, const move_t* hl);
void AddTempmonToParty(void);
void SendGetMonIntoFromBox(void);
void CloseSRAM_And_SetCarryFlag(void);
void RestorePPOfDepositedPokemon(void);
void RetrieveMonFromDayCareMan(void);
void RetrieveMonFromDayCareLady(void);
void RetrieveBreedmon(void);
void GetLastPartyMon(void);
void DepositMonWithDayCareMan(void);
void DepositMonWithDayCareLady(void);
void DepositBreedmon(void);
void SendMonIntoBox(void);
void ShiftBoxMon(void);
void GiveEgg(void);
void String_Egg(void);
void RemoveMonFromPartyOrBox(void);
void RemoveMonFromPartyOrBox_Conv(uint8_t param);
void ComputeNPCTrademonStats(void);
void ComputeNPCTrademonStats_Conv(uint8_t curPartyMon);
void CalcMonStats(void);
void CalcMonStats_Conv(uint16_t* stats, const uint16_t* statExp, uint16_t dvs, uint8_t b);
void CalcMonStatC(void);
uint16_t CalcMonStatC_Conv(const uint16_t* statExp, uint16_t dvs, uint8_t b, uint8_t c);
void GivePoke(void);
void WasSentToBillsPCText(void);
void InitNickname(void);
