void BattleStatsScreenInit(void);
void StatsScreenInit(void);
void v_MobileStatsScreenInit(void);
void StatsScreenInit_gotaddress(void);
void StatsScreenInit_Common(void (*hl)(void));
void StatsScreenMain(void);
void StatsScreenMobile(void);
// void StatsScreenPointerTable(void);
// void StatsScreen_WaitAnim(void);
// void StatsScreen_SetJumptableIndex(uint8_t h);
// void StatsScreen_Exit(void);
// void MonStatsInit(void);
// void EggStatsInit(void);
// void EggStatsJoypad(void);
// void StatsScreen_LoadPage(void);
// void MonStatsJoypad(void);
// void StatsScreenWaitCry(void);
// void StatsScreen_CopyToTempMon(void);
// bool StatsScreen_GetJoypad(uint8_t* a);
// void StatsScreen_JoypadAction(uint8_t a);
// void StatsScreen_InitUpperHalf(void);
// void StatsScreen_PlaceVerticalDivider(void);
// void StatsScreen_PlaceHorizontalDivider(void);
// void StatsScreen_PlacePageSwitchArrows(void);
// void StatsScreen_PlaceShinyIcon(void);
// void StatsScreen_LoadGFX(void);
// void LoadPinkPage(void);
// void LoadGreenPage(void);
// void LoadBluePage(void);
// void IDNoString(void);
// void OTString(void);
// void StatsScreen_PlaceFrontpic(void);
// u8_flag_s StatsScreen_GetAnimationParam(void);
void StatsScreen_LoadTextboxSpaceGFX(void);
void StatsScreenSpaceGFX(void);
void EggStatsScreen(void);
// extern const char EggString[];
// extern const char FiveQMarkString[];
// void StatsScreen_AnimateEgg(void);
// void StatsScreen_LoadPageIndicators(uint8_t c);
// uint8_t* CopyNickname(uint8_t* hl);
// uint8_t* GetNicknamenamePointer(void);
// uint8_t* GetNicknamenamePointer2(void);
bool CheckFaintedFrzSlp(struct PartyMon* bc);
//#include "gfx/font/space.2bpp"
