void CopyMonToTempMon(void);
void CopyMonToTempMon_Conv(void);
void CalcBufferMonStats(void);
void CalcBufferMonStats_Conv(void);
void CalcTempmonStats(void);
void CalcTempmonStats_Conv(void);
void v_TempMonStatsCalculation(void);
void v_TempMonStatsCalculation_Conv(struct PartyMon* bc);
void GetMonSpecies(void);
species_t GetMonSpecies_Conv(uint8_t e);
