void AI_SwitchOrTryItem(void);
void DontSwitch(void);
void SwitchOften(void);
void SwitchRarely(void);
void SwitchSometimes(void);
void CheckSubstatusCantRun(void);
void AI_TryItem(void);
void AI_Items(void);
void AIUpdateHUD(void);
void AIUsedItemSound(void);
void EnemyUsedFullHeal(void);
void EnemyUsedMaxPotion(void);
void EnemyUsedFullRestore(void);
void FullRestoreContinue(void);
void EnemyUsedPotion(void);
void EnemyUsedSuperPotion(void);
void EnemyUsedHyperPotion(void);
void EnemyPotionContinue(void);
void EnemyPotionFinish(void);
void AI_TrySwitch(void);
void AI_Switch(void);
// void EnemyWithdrewText(void);
extern const txt_cmd_s EnemyWithdrewText[];
void EnemyUsedFullHealRed(void);
void AI_HealStatus(void);
void EnemyUsedXAccuracy(void);
void EnemyUsedGuardSpec(void);
void EnemyUsedDireHit(void);
void AICheckEnemyFractionMaxHP(void);
void EnemyUsedXAttack(void);
void EnemyUsedXDefend(void);
void EnemyUsedXSpeed(void);
void EnemyUsedXSpecial(void);
void EnemyUsedXItem(void);
void PrintText_UsedItemOn_AND_AIUpdateHUD(void);
void PrintText_UsedItemOn(void);
// void EnemyUsedOnText(void);
extern const txt_cmd_s EnemyUsedOnText[];
