bool AI_SwitchOrTryItem(void);
bool DontSwitch(void);
bool SwitchOften(void);
bool SwitchRarely(void);
bool SwitchSometimes(void);
void CheckSubstatusCantRun(void);
bool AI_TryItem(void);
// void AI_Items(void);
void AIUpdateHUD(void);
void AIUsedItemSound(void);
void EnemyUsedFullHeal(void);
void EnemyUsedMaxPotion(void);
void EnemyUsedFullRestore(void);
void FullRestoreContinue(void);
void EnemyUsedPotion(void);
void EnemyUsedSuperPotion(void);
void EnemyUsedHyperPotion(void);
void EnemyPotionContinue(item_t a, uint16_t hp);
void EnemyPotionFinish(void);
bool AI_TrySwitch(void);
bool AI_Switch(void);
// void EnemyWithdrewText(void);
extern const txt_cmd_s EnemyWithdrewText[];
void EnemyUsedFullHealRed(void);
void AI_HealStatus(void);
void EnemyUsedXAccuracy(void);
void EnemyUsedGuardSpec(void);
void EnemyUsedDireHit(void);
void AICheckEnemyFractionMaxHP(void);
void EnemyUsedXAttack(void);
void EnemyUsedXDefend(void);
void EnemyUsedXSpeed(void);
void EnemyUsedXSpecial(void);
void EnemyUsedXItem(item_t item, uint8_t b);
void PrintText_UsedItemOn_AND_AIUpdateHUD(item_t item);
void PrintText_UsedItemOn(void);
// void EnemyUsedOnText(void);
extern const txt_cmd_s EnemyUsedOnText[];
