void AIScoring(void);
void AI_Basic(void);
void AI_Setup(void);
void AI_Types(void);
void AI_Offensive(void);
void AI_Smart(void);
void AI_Smart_EffectHandlers(void);
void AI_Smart_Sleep(void);
void AI_Smart_Sleep_Conv(uint8_t* hl);
void AI_Smart_LeechHit(void);
void AI_Smart_LeechHit_Conv(uint8_t* hl);
void AI_Smart_LockOn(void);
void AI_Smart_LockOn_Conv(uint8_t* hl);
void AI_Smart_Selfdestruct(void);
void AI_Smart_Selfdestruct_Conv(uint8_t* hl);
void AI_Smart_DreamEater(void);
void AI_Smart_DreamEater_Conv(uint8_t* hl);
void AI_Smart_EvasionUp(void);
void AI_Smart_EvasionUp_Conv(uint8_t* hl);
void AI_Smart_AlwaysHit(void);
void AI_Smart_AlwaysHit_Conv(uint8_t* hl);
void AI_Smart_MirrorMove(void);
void AI_Smart_MirrorMove_Conv(uint8_t* hl);
void AI_Smart_AccuracyDown(void);
void AI_Smart_AccuracyDown_Conv(uint8_t* hl);
void AI_Smart_ResetStats(void);
void AI_Smart_ResetStats_Conv(uint8_t* hl);
void AI_Smart_Bide(void);
void AI_Smart_Bide_Conv(uint8_t* hl);
void AI_Smart_ForceSwitch(void);
void AI_Smart_ForceSwitch_Conv(uint8_t* hl);
void AI_Smart_Heal(void);
void AI_Smart_MorningSun(void);
void AI_Smart_Synthesis(void);
void AI_Smart_Moonlight(void);
void AI_Smart_Moonlight_Conv(uint8_t* hl);
void AI_Smart_Toxic(void);
void AI_Smart_LeechSeed(void);
void AI_Smart_LeechSeed_Conv(uint8_t* hl);
void AI_Smart_LightScreen(void);
void AI_Smart_Reflect(void);
void AI_Smart_Reflect_Conv(uint8_t* hl);
void AI_Smart_Ohko(void);
void AI_Smart_Ohko_Conv(uint8_t* hl);
void AI_Smart_TrapTarget(void);
void AI_Smart_TrapTarget_Conv(uint8_t* hl);
void AI_Smart_RazorWind(void);
void AI_Smart_RazorWind_Conv(uint8_t* hl);
void AI_Smart_Unused2B(void);
void AI_Smart_Confuse(void);
void AI_Smart_Confuse_Conv(uint8_t* hl);
void AI_Smart_SpDefenseUp2(void);
void AI_Smart_SpDefenseUp2_Conv(uint8_t* hl);
void AI_Smart_Fly(void);
void AI_Smart_Fly_Conv(uint8_t* hl);
void AI_Smart_SuperFang(void);
void AI_Smart_SuperFang_Conv(uint8_t* hl);
void AI_Smart_Paralyze(void);
void AI_Smart_Paralyze_Conv(uint8_t* hl);
void AI_Smart_SpeedDownHit(void);
void AI_Smart_SpeedDownHit_Conv(uint8_t* hl);
void AI_Smart_Substitute(void);
void AI_Smart_Substitute_Conv(uint8_t* hl);
void AI_Smart_HyperBeam(void);
void AI_Smart_HyperBeam_Conv(uint8_t* hl);
void AI_Smart_Rage(void);
void AI_Smart_Rage_Conv(uint8_t* hl);
void AI_Smart_Mimic(void);
void AI_Smart_Mimic_Conv(uint8_t* hl);
void AI_Smart_Counter(void);
void AI_Smart_Counter_Conv(uint8_t* hl);
void AI_Smart_Encore(void);
void AI_Smart_Encore_Conv(uint8_t* hl);
void AI_Smart_PainSplit(void);
void AI_Smart_PainSplit_Conv(uint8_t* hl);
void AI_Smart_Snore(void);
void AI_Smart_SleepTalk(void);
void AI_Smart_SleepTalk_Conv(uint8_t* hl);
void AI_Smart_DefrostOpponent(void);
void AI_Smart_Spite(void);
void AI_Smart_Spite_Conv(uint8_t* hl);
void AI_Smart_DestinyBond(void);
void AI_Smart_Reversal(void);
void AI_Smart_SkullBash(void);
void AI_Smart_SkullBash_Conv(uint8_t* hl);
void AI_Smart_HealBell(void);
void AI_Smart_HealBell_Conv(uint8_t* hl);
void AI_Smart_PriorityHit(void);
void AI_Smart_PriorityHit_Conv(uint8_t* hl);
void AI_Smart_Thief(void);
void AI_Smart_Thief_Conv(uint8_t* hl);
void AI_Smart_Conversion2(void);
void AI_Smart_Conversion2_Conv(uint8_t* hl);
void AI_Smart_Disable(void);
void AI_Smart_Disable_Conv(uint8_t* hl);
void AI_Smart_MeanLook(void);
void AI_Smart_MeanLook_Conv(uint8_t* hl);
void AICheckLastPlayerMon(void);
bool AICheckLastPlayerMon_Conv(void);
void AI_Smart_Nightmare(void);
void AI_Smart_Nightmare_Conv(uint8_t* hl);
void AI_Smart_FlameWheel(void);
void AI_Smart_FlameWheel_Conv(uint8_t* hl);
void AI_Smart_Curse(void);
void AI_Smart_Curse_Conv(uint8_t* hl);
void AI_Smart_Protect(void);
void AI_Smart_Protect_Conv(uint8_t* hl);
void AI_Smart_Foresight(void);
void AI_Smart_Foresight_Conv(uint8_t* hl);
void AI_Smart_PerishSong(void);
void AI_Smart_PerishSong_Conv(uint8_t* hl);
void AI_Smart_Sandstorm(void);
void AI_Smart_Sandstorm_Conv(uint8_t* hl);
void AI_Smart_Endure(void);
void AI_Smart_FuryCutter(void);
void AI_Smart_FuryCutter_Conv(uint8_t* hl);
void AI_Smart_Rollout(void);
void AI_Smart_Rollout_Conv(uint8_t* hl);
void AI_Smart_Swagger(void);
void AI_Smart_Attract(void);
void AI_Smart_Attract_Conv(uint8_t* hl);
void AI_Smart_Safeguard(void);
void AI_Smart_Safeguard_Conv(uint8_t* hl);
void AI_Smart_Magnitude(void);
void AI_Smart_Earthquake(void);
void AI_Smart_Earthquake_Conv(uint8_t* hl);
void AI_Smart_BatonPass(void);
void AI_Smart_Pursuit(void);
void AI_Smart_Pursuit_Conv(uint8_t* hl);
void AI_Smart_RapidSpin(void);
void AI_Smart_RapidSpin_Conv(uint8_t* hl);
void AI_Smart_HiddenPower(void);
void AI_Smart_HiddenPower_Conv(uint8_t* hl);
void AI_Smart_RainDance(void);
void AI_Smart_RainDance_Conv(uint8_t* hl);
void AI_Smart_SunnyDay(void);
void AI_Smart_SunnyDay_Conv(uint8_t* hl);
void AI_Smart_WeatherMove(void);
void AI_Smart_WeatherMove_Conv(uint8_t* hl, const move_t* moves);
void AIBadWeatherType(void);
void AIBadWeatherType_Conv(uint8_t* hl);
void AIGoodWeatherType(void);
void AIGoodWeatherType_Conv(uint8_t* hl);
void AI_Smart_BellyDrum(void);
void AI_Smart_BellyDrum_Conv(uint8_t* hl);
void AI_Smart_PsychUp(void);
void AI_Smart_PsychUp_Conv(uint8_t* hl);
void AI_Smart_MirrorCoat(void);
void AI_Smart_MirrorCoat_Conv(uint8_t* hl);
void AI_Smart_Twister(void);
void AI_Smart_Gust(void);
void AI_Smart_Gust_Conv(uint8_t* hl);
void AI_Smart_FutureSight(void);
void AI_Smart_FutureSight_Conv(uint8_t* hl);
void AI_Smart_Stomp(void);
void AI_Smart_Stomp_Conv(uint8_t* hl);
void AI_Smart_Solarbeam(void);
void AI_Smart_Solarbeam_Conv(uint8_t* hl);
void AI_Smart_Thunder(void);
void AI_Smart_Thunder_Conv(uint8_t* hl);
void AICompareSpeed(void);
bool AICompareSpeed_Conv(void);
void AICheckPlayerMaxHP(void);
bool AICheckPlayerMaxHP_Conv(void);
void AICheckEnemyMaxHP(void);
bool AICheckEnemyMaxHP_Conv(void);
void AICheckMaxHP(void);
bool AICheckMaxHP_Conv(uint16_t hp, uint16_t maxHP);
void AICheckPlayerHalfHP(void);
bool AICheckPlayerHalfHP_Conv(void);
void AICheckEnemyHalfHP(void);
bool AICheckEnemyHalfHP_Conv(void);
void AICheckEnemyQuarterHP(void);
bool AICheckEnemyQuarterHP_Conv(void);
void AICheckPlayerQuarterHP(void);
bool AICheckPlayerQuarterHP_Conv(void);
void AIHasMoveEffect(void);
bool AIHasMoveEffect_Conv(uint8_t b);
void AIHasMoveInArray(void);
bool AIHasMoveInArray_Conv(const move_t* hl);
void AI_Opportunist(void);
void AI_Aggressive(void);
void AIDamageCalc(void);
void AI_Cautious(void);
void AI_Status(void);
void AI_Risky(void);
void AI_None(void);
void AIDiscourageMove(void);
void AIDiscourageMove_Conv(uint8_t* hl);
void AIGetEnemyMove(void);
const struct Move* AIGetEnemyMove_Conv(move_t a);
void AI_80_20(void);
bool AI_80_20_Conv(void);
void AI_50_50(void);
bool AI_50_50_Conv(void);
//#include "data/battle/ai/status_only_effects.h"
//#include "data/battle/ai/encore_moves.h"
//#include "data/battle/ai/rain_dance_moves.h"
//#include "data/battle/ai/sunny_day_moves.h"
//#include "data/battle/ai/useful_moves.h"
//#include "data/battle/ai/stall_moves.h"
//#include "data/battle/ai/reckless_moves.h"
//#include "data/battle/ai/constant_damage_effects.h"
//#include "data/battle/ai/residual_moves.h"
//#include "data/battle/ai/risky_effects.h"
