void AIScoring(void);
void AI_Basic(void);
void AI_Setup(void);
void AI_Types(void);
void AI_Offensive(void);
void AI_Smart(void);
void AI_Smart_EffectHandlers(void);
// void AI_Smart_Sleep(uint8_t* hl);
// void AI_Smart_LeechHit(uint8_t* hl);
// void AI_Smart_LockOn(uint8_t* hl);
// void AI_Smart_Selfdestruct(uint8_t* hl);
// void AI_Smart_DreamEater(uint8_t* hl);
// void AI_Smart_EvasionUp(uint8_t* hl);
// void AI_Smart_AlwaysHit(uint8_t* hl);
// void AI_Smart_MirrorMove(uint8_t* hl);
// void AI_Smart_AccuracyDown(uint8_t* hl);
// void AI_Smart_ResetStats(uint8_t* hl);
// void AI_Smart_Bide(uint8_t* hl);
// void AI_Smart_ForceSwitch(uint8_t* hl);
// void AI_Smart_Heal(uint8_t* hl);
// void AI_Smart_MorningSun(uint8_t* hl);
// void AI_Smart_Synthesis(uint8_t* hl);
// void AI_Smart_Moonlight(uint8_t* hl);
// void AI_Smart_Toxic(uint8_t* hl);
// void AI_Smart_LeechSeed(uint8_t* hl);
// void AI_Smart_LightScreen(uint8_t* hl);
// void AI_Smart_Reflect(uint8_t* hl);
// void AI_Smart_Ohko(uint8_t* hl);
// void AI_Smart_TrapTarget(uint8_t* hl);
// void AI_Smart_RazorWind(uint8_t* hl);
// void AI_Smart_Unused2B(void);
// void AI_Smart_Confuse(uint8_t* hl);
// void AI_Smart_SpDefenseUp2(uint8_t* hl);
// void AI_Smart_Fly(uint8_t* hl);
// void AI_Smart_SuperFang(uint8_t* hl);
// void AI_Smart_Paralyze(uint8_t* hl);
// void AI_Smart_SpeedDownHit(uint8_t* hl);
// void AI_Smart_Substitute(uint8_t* hl);
// void AI_Smart_HyperBeam(uint8_t* hl);
// void AI_Smart_Rage(uint8_t* hl);
// void AI_Smart_Mimic(uint8_t* hl);
// void AI_Smart_Counter(uint8_t* hl);
// void AI_Smart_Encore(uint8_t* hl);
// void AI_Smart_PainSplit(uint8_t* hl);
// void AI_Smart_Snore(uint8_t* hl);
// void AI_Smart_SleepTalk(uint8_t* hl);
// void AI_Smart_DefrostOpponent(uint8_t* hl);
// void AI_Smart_Spite(uint8_t* hl);
// void AI_Smart_DestinyBond(uint8_t* hl);
// void AI_Smart_Reversal(uint8_t* hl);
// void AI_Smart_SkullBash(uint8_t* hl);
// void AI_Smart_HealBell(uint8_t* hl);
// void AI_Smart_PriorityHit(uint8_t* hl);
// void AI_Smart_Thief(uint8_t* hl);
// void AI_Smart_Conversion2(uint8_t* hl);
// void AI_Smart_Disable(uint8_t* hl);
// void AI_Smart_MeanLook(uint8_t* hl);
// bool AICheckLastPlayerMon(void);
// void AI_Smart_Nightmare(uint8_t* hl);
// void AI_Smart_FlameWheel(uint8_t* hl);
// void AI_Smart_Curse(uint8_t* hl);
// void AI_Smart_Protect(uint8_t* hl);
// void AI_Smart_Foresight(uint8_t* hl);
// void AI_Smart_PerishSong(uint8_t* hl);
// void AI_Smart_Sandstorm(uint8_t* hl);
// void AI_Smart_Endure(uint8_t* hl);
// void AI_Smart_FuryCutter(uint8_t* hl);
// void AI_Smart_Rollout(uint8_t* hl);
// void AI_Smart_Swagger(uint8_t* hl);
// void AI_Smart_Attract(uint8_t* hl);
// void AI_Smart_Safeguard(uint8_t* hl);
// void AI_Smart_Magnitude(uint8_t* hl);
// void AI_Smart_Earthquake(uint8_t* hl);
// void AI_Smart_BatonPass(uint8_t* hl);
// void AI_Smart_Pursuit(uint8_t* hl);
// void AI_Smart_RapidSpin(uint8_t* hl);
// void AI_Smart_HiddenPower(uint8_t* hl);
// void AI_Smart_RainDance(uint8_t* hl);
// void AI_Smart_SunnyDay(uint8_t* hl);
// void AI_Smart_WeatherMove(uint8_t* hl, const move_t* moves);
// void AIBadWeatherType(uint8_t* hl);
// void AIGoodWeatherType(uint8_t* hl);
// void AI_Smart_BellyDrum(uint8_t* hl);
// void AI_Smart_PsychUp(uint8_t* hl);
// void AI_Smart_MirrorCoat(uint8_t* hl);
// void AI_Smart_Twister(uint8_t* hl);
// void AI_Smart_Gust(uint8_t* hl);
// void AI_Smart_FutureSight(uint8_t* hl);
// void AI_Smart_Stomp(uint8_t* hl);
// void AI_Smart_Solarbeam(uint8_t* hl);
// void AI_Smart_Thunder(uint8_t* hl);
bool AICompareSpeed(void);
bool AICheckPlayerMaxHP(void);
bool AICheckEnemyMaxHP(void);
bool AICheckMaxHP(uint16_t hp, uint16_t maxHP);
bool AICheckPlayerHalfHP(void);
bool AICheckEnemyHalfHP(void);
bool AICheckEnemyQuarterHP(void);
bool AICheckPlayerQuarterHP(void);
bool AIHasMoveEffect(uint8_t b);
bool AIHasMoveInArray(const move_t* hl);
void AI_Opportunist(void);
void AI_Aggressive(void);
void AIDamageCalc(void);
void AI_Cautious(void);
void AI_Status(void);
void AI_Risky(void);
void AI_None(void);
// void AIDiscourageMove(uint8_t* hl);
// const struct Move* AIGetEnemyMove(move_t a);
// bool AI_80_20(void);
//#include "data/battle/ai/status_only_effects.h"
//#include "data/battle/ai/encore_moves.h"
//#include "data/battle/ai/rain_dance_moves.h"
//#include "data/battle/ai/sunny_day_moves.h"
//#include "data/battle/ai/useful_moves.h"
//#include "data/battle/ai/stall_moves.h"
//#include "data/battle/ai/reckless_moves.h"
//#include "data/battle/ai/constant_damage_effects.h"
//#include "data/battle/ai/residual_moves.h"
//#include "data/battle/ai/risky_effects.h"
