void DummyPredef35(void);
void DummyPredef36(void);
void UpdateTimeOfDayPal(void);
void v_TimeOfDayPals(void);
bool v_TimeOfDayPals_Conv(void);
void v_UpdateTimePals(void);
void FadeInPalettes(void);
void FadeOutPalettes(void);
void BattleTowerFade(void);
void FadeInQuickly(void);
void FadeBlackQuickly(void);
void FillWhiteBGColor(void);
void ReplaceTimeOfDayPals(void);
void ReplaceTimeOfDayPals_Conv(void);
void GetTimePalette(void);
uint8_t GetTimePalette_Conv(void);
void DmgToCgbTimePals(void);
void DmgToCgbTimePals_Conv(const uint8_t* hl);
void ConvertTimePalsIncHL(void);
void ConvertTimePalsIncHL_Conv(const uint8_t* hl, uint8_t b);
void ConvertTimePalsDecHL(void);
void ConvertTimePalsDecHL_Conv(const uint8_t* hl, uint8_t b);
void GetTimePalFade(void);
const uint8_t* GetTimePalFade_Conv(uint8_t c);
