void DummyPredef35(void);
void DummyPredef36(void);
void UpdateTimeOfDayPal(void);
bool v_TimeOfDayPals(void);
void v_UpdateTimePals(void);
void FadeInPalettes(void);
void FadeOutPalettes(void);
void BattleTowerFade(void);
void FadeInQuickly(void);
void FadeBlackQuickly(void);
void FillWhiteBGColor(void);
void ReplaceTimeOfDayPals(void);
// uint8_t GetTimePalette(void);
// void DmgToCgbTimePals(const uint8_t* hl);
void ConvertTimePalsIncHL(const uint8_t* hl, uint8_t b);
void ConvertTimePalsDecHL(const uint8_t* hl, uint8_t b);
// const uint8_t* GetTimePalFade(uint8_t c);
